### ISSUE TITLE
add THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA for Dovecot

### ISSUE THREAD

**Issue by changloong** [hardware/mailserver#10]
It will be great if we can add THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA ad default or optional.

for postfix,  please consider add discard_ehlo for localhost.

In `/etc/postfix/main.cf`:
```cf
smtpd_discard_ehlo_keyword_address_maps = hash:/etc/postfix/discard_ehlo
```
and in `/etc/postfix/discard_ehlo`:
```cf
127.0.0.1 starttls,silent-discard 
172.17.0.1 starttls,silent-discard 
```

**Comment by hardware** [comment]
**THREAD=ORDEREDSUBJECT**, **THREAD=REFERENCES** and **SORT** extensions are already enabled by default. For quota support, it's in the roadmap ;)

```
openssl s_client -connect mail.domain.tld:993 -tlsextdebug

. login user@domain.tld password
. OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in
. logout
* BYE Logging out
. OK Logout completed.
```

> for postfix, please consider add discard_ehlo for localhost

Good idea, I'll add it.

**Comment by Wonderfall** [comment]
I can't explain why, but this commit fucked up everything running on localhost.
What is going on?

**Comment by hardware** [comment]
Can you provide some errors/warning messages from `docker logs` command ?

I fixed a misktake in 0727134 commit, now everything should work with the last commit 6b6129a.

**Comment by Wonderfall** [comment]
Nothing on server-side; all clients running on localhost return that STARTTLS is not supported by this server (Rainloop, Isso...). Removing this commit was the solution.

**Comment by hardware** [comment]
I rollback to previous commit, problem solved.
