### ISSUE TITLE
domainname is not supported in docker stack : need env var for DOMAIN and FQDN

### ISSUE THREAD

**Issue by izanagi1995** [hardware/mailserver#100]
Hello again @hardware,

There is a little problem with the "domainname" option in docker stack (with compose v3). This option is not supported in stacks!
So the FQDN is equals to the hostname (mail by example)

Can you bring an optional environment variable to set DOMAIN and FQDN env var

See https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/startup#L27-L28

**Comment by hardware** [comment]
> This option is not supported in stacks

Are you sure ?

https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#single-value-keys-analogous-to-a-docker-run-counterpart
https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-macaddress-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir

**Comment by izanagi1995** [comment]
Yes I am
```
docker stack deploy -c docker-stack.yml dockify
Ignoring unsupported options: domainname, links
```
😕

**Comment by hardware** [comment]
You are running the latest docker version ? You can open an issue here : https://github.com/moby/moby/issues

I will add this two env variable to work around this problem.
