### ISSUE TITLE
Running Mailserver on AWS EC2 instance which already has a site running under apache php

### ISSUE THREAD

**Issue by inglesuniversal** [hardware/mailserver#102]
Hello: I have a webste at AWS EC2 instance... and I have my Email service under WORKMAIL which is AWS Email Service... The thing is that with 7 tiny account I pay over 15 USD a month... Do you think that I can run and install your script? Can I run your script with my site which is currently hosted there? How do I go about setting up the MX files or any other files that Amazon created for me before? Can I host my Email from my second AWS EC2 instance without causing any server errors? thanks.

**Comment by hardware** [comment]
> Do you think that I can run and install your script? 

Yes. But you must have a linux distribution compatible with docker.

> Can I run your script with my site which is currently hosted there ? 

Yes.

> How do I go about setting up the MX files or any other files that Amazon created for me before

MX files ?

Follow this guide if you want to setup a DNS server : 
https://github.com/hardware/mailserver/wiki/NSD-initial-configuration
