### ISSUE TITLE
Warnings while deploying into Amazone ECS

### ISSUE THREAD

**Issue by bvn13** [hardware/mailserver#104]
How to deploy?
Why it skips the whole config?

# ecs-cli compose --project-name mail_maildomain_tk service up                                                             
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=mailserver
WARN[0000] Skipping unsupported YAML option for service...  option name="depends_on" service name=mailserver
WARN[0000] Skipping unsupported YAML option for service...  option name=domainname service name=mailserver
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=mailserver
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=mariadb
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=mariadb
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=nginx
WARN[0000] Skipping unsupported YAML option for service...  option name="depends_on" service name=nginx
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=nginx
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=nsd
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=nsd
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=postfixadmin
WARN[0000] Skipping unsupported YAML option for service...  option name="depends_on" service name=postfixadmin
WARN[0000] Skipping unsupported YAML option for service...  option name=domainname service name=postfixadmin
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=postfixadmin
WARN[0000] Skipping unsupported YAML option for service...  option name="container_name" service name=rainloop
WARN[0000] Skipping unsupported YAML option for service...  option name="depends_on" service name=rainloop
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=rainloop
INFO[0001] Using ECS task definition                     TaskDefinition="ecscompose-mail_maildomain_tk:1"
INFO[0002] Created an ECS service                        service="ecscompose-service-mail_maildomain_tk" taskDefinition="ecscompose-mail_maildomain_tk:1"
INFO[0002] Updated ECS service successfully              desiredCount=1 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0002] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0033] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0063] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0094] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0124] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0155] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0185] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0215] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0246] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0276] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0307] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0337] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0368] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0398] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0429] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0459] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0490] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0520] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0551] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
INFO[0581] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName="ecscompose-service-mail_maildomain_tk"
FATA[0611] Timeout waiting for service ecscompose-service-mail_maildomain_tk to get stable

**Comment by hardware** [comment]
You can report this issue here : https://github.com/aws/amazon-ecs-cli/issues/237

**Comment by yinshiua** [comment]
ecs-cli skips unsupported fields like "network". Please look at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html for reference. Thanks!
