### ISSUE TITLE
alias not owned by user

### ISSUE THREAD

**Issue by zerpex** [hardware/mailserver#111]
Hi,

I set up a test server with your container and it seems all good... but I got this message while trying to send an email from an alias (receiving emails from this alias works fine) :

  2017-05-16T13:15:50.450851+00:00 mail postfix/submission/smtpd[706]: NOQUEUE: reject: RCPT from unknown[172.19.0.1]: 553 5.7.1 <kapoue@xxx>: Sender address rejected: not owned by user zer@xxx; from=<kapoue@xxx> to=<zer@xxx> proto=ESMTP helo=<[192.168.42.52]>

My guess is a wrong smtpd_sender_restrictions parameter in postfix, but my skills aren't good enough to go further :D

Any idea ?

**Comment by hardware** [comment]
Because `smtpd_sender_login_maps` query does not lookup for aliases, only mailboxes for security reasons.

**Comment by navossoc** [comment]
@hardware Kinda related...

There is a similar issue with "domain alias".

Should we allow the aliased domain to send emails too?
(receiving emails on domain alias is ok)

If so, I can open an issue later.

**Comment by navossoc** [comment]
@taniki I don't recall if I really did some tests about it, but yes, it is possible.

I was looking something related at the time:
https://github.com/hardware/mailserver/pull/322

Probably tweaking the `smtpd_sender_restrictions`.
For that you will need to read the docs and figure it out how it works (it took me some time, it was really painful hahaha).

[]'s
