### ISSUE TITLE
Certificat Nginx NO_SUCH_FILE

### ISSUE THREAD

**Issue by Yfksw65** [hardware/mailserver#112]
Erreur dans le fichier de log de nginx error.log 

`2017/05/16 14:35:54 [emerg] 9#9: BIO_new_file("/etc/nginx/conf/certs/live/mail.ledomaine.fr/key.pem") failed (SSL: error:02000002:system library:OPENSSL_internal:No such file or directory:fopen('/etc/nginx/conf/certs/live/mail.ledomaine.fr/key.pem','r') error:1100006e:BIO routines:OPENSSL_internal:NO_SUCH_FILE)
`

Alors que le fichier existe bien : 

```
root@vps:/mnt/docker/nginx# ll /mnt/docker/nginx/certs/live/mail.ledomaine.fr/
total 28
-rwx------ 1 991 991 2159 May 16 16:30 cert1.pem
lrwxrwxrwx 1 991 991   45 May 16 16:11 cert.pem -> ../../archive/mail.ledomaine.fr/cert1.pem
-rwx------ 1 991 991 1647 May 16 16:30 chain1.pem
lrwxrwxrwx 1 991 991   46 May 16 16:11 chain.pem -> ../../archive/mail.ledomaine.fr/chain1.pem
-rwx------ 1 991 991 3806 May 16 16:28 fullchain1.pem
lrwxrwxrwx 1 991 991   50 May 16 16:11 fullchain.pem -> ../../archive/mail.ledomaine.fr/fullchain1.pem
-rwx------ 1 991 991 7074 May 16 16:11 key.pem
-rwx------ 1 991 991 3268 May 16 16:18 privkey1.pem
lrwxrwxrwx 1 991 991   48 May 16 16:11 privkey.pem -> ../../archive/mail.ledomaine.fr/privkey1.pem
-rwx------ 1 991 991  543 May 16 16:11 README

```

Une idée ?

**Comment by hardware** [comment]
Le chemin est incorrect `/etc/nginx/conf/certs/live/mail.ledomaine.fr/key.pem`, il faut mettre `/certs/live/mail.domain.tld/privkey.pem`  dans ton vhost nginx.

**Comment by Yfksw65** [comment]
Exactement. 

Merci beaucoup
