### ISSUE TITLE
TLS library problem: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknow

### ISSUE THREAD

**Issue by Yfksw65** [hardware/mailserver#113]
Hello,

J'essai de configurer l'envoi des mail avec le CRM Dolibarr seulement il semble que j'ai une erreur de certificat alors que j'utilise un certificat letsencrypt

2017-05-17T22:42:58.696983+00:00 mail postfix/submission/smtpd[320]: warning: TLS library problem: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1315:SSL alert number 48:

Ci-dessous ma configuration sous dolibarr + erreur 
<img width="1004" alt="capture d ecran 2017-05-18 a 00 50 46" src="https://cloud.githubusercontent.com/assets/19516908/26179457/27415122-3b64-11e7-8b41-036a72f352cc.png">
<img width="969" alt="capture d ecran 2017-05-18 a 00 51 08" src="https://cloud.githubusercontent.com/assets/19516908/26179460/293dc668-3b64-11e7-8c30-e4a7803e7614.png">

D'après mes recherches, il s'agirait d'une erreur de présentation (certification auto signée par exemple)  du certificat de la part du serveur mail sauf que dans /mnt/docker/mail/ssl/ j'ai placé mes certificats let's encrypt

**Comment by hardware** [comment]
Il faut le mettre comme ceci ; 

```
mailserver:
  image: hardware/mailserver
  volumes:
    - /mnt/docker/nginx/certs:/etc/letsencrypt
```

` /mnt/docker/nginx/certs` c'est arbitraire.

**Comment by Yfksw65** [comment]
Hello,

C'est bien le cas 

   volumes:
      - /mnt/docker/mail:/var/mail
      - /mnt/docker/mail/opendkim:/etc/opendkim/keys
      - /mnt/docker/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb

**Comment by hardware** [comment]
C'est pas bon alors parce que tu as mis tes certificats LE dans `/mnt/docker/mail/ssl/`

**Comment by Yfksw65** [comment]
C'est vrai
```
root@vps:/mnt/docker/mail/ssl# ll
total 12
drwxr-xr-x 2 1024 1024 4096 May 18 00:41 dhparams
drwxr-xr-x 3 1024 1024 4096 May 18 00:41 live
drwxr-xr-x 2 1024 1024 4096 May 18 00:13 selfsigned
```

du coup je peux virer live et selfsigned ? dhparams sert à quoi ? 

Merci

**Comment by hardware** [comment]
C'est les paramètres Diffie-Hellman pour l'utilisation de la Forward Secrecy : http://www.postfix.org/FORWARD_SECRECY_README.html
