### ISSUE TITLE
Configurable spam/ham folder

### ISSUE THREAD

**Issue by koubas** [hardware/mailserver#114]
I want SA not to learn ham from the root folder but from Ham folder, because some people (or inactive account) may keep they spam messages in root.

My proposal is to make Spam and Ham folders configurable, with defaults set to mimic the current hardcoded configuration.

I can implement that feature my self, is here an interest to merge it?

cheers

**Comment by hardware** [comment]
> is here an interest to merge it ?

Yes, why not. Don't forget to create automatically the ham folder with `auto=create` :

```bash
# /rootfs/etc/dovecot/conf.d/15-mailboxes.conf

mailbox Ham {
    auto = create
}
```

If this directory is required by the user.

**Comment by hardware** [comment]
**Obsolete since 1.1-beta**

More information : https://github.com/hardware/mailserver/issues/110#issuecomment-309279757

**Comment by koubas** [comment]
If anyone is interested, I have the patch ready here: https://github.com/koubas/mailserver/tree/configurable-spam-folders
I haven't created the PR as I found it obsolete after reading through the 1.1 codebase too :)
