### ISSUE TITLE
Remove Dovecot PID file on startup

### ISSUE THREAD

**Issue by cdauth** [hardware/mailserver#115]
When the container is shut down by force (for example because the server reboots), `/var/run/dovecot/master.pid` is not removed. This causes dovecot to fail starting the next time with the error message:

```
mailserver_1    | 2017-05-22T12:42:48.035452+00:00 mail dovecot: master: Fatal: Dovecot is already running with PID 195 (read from /var/run/dovecot/master.pid)
```

The startup script should remove this file.

**Comment by hardware** [comment]
Thanks for reporting this.
