### ISSUE TITLE
Clé DKIM trop longue pour OVH ? 

### ISSUE THREAD

**Issue by Yfksw65** [hardware/mailserver#116]
J'ai un petit problème avec ma clé DKIM : 

```
mail._domainkey	IN	TXT	( "v=DKIM1; k=rsa; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3D924haJ80mtXMm+YrRdb2ISgyxAtzXLzVc9wkBf/3W1uVOtcJ97trF7sRoDH5a0bkXWDV41APfY4Ja2lvYpmHV9cCDnM5egK09x7HgJrlOM3OnMk4VtCm+9hAbAafsKeayuRy4ONboy6OsLFHDOWxpai8e/vNxKXeSmEeyVdHqZaFekvbfM81FYdPn7JIfcKcrqgPknQHs642"
	  "DJIxDvBF7qolwHc0APYQhxEW1hARCf8vLWKrnz1p+xe9TlYvXQK26HaCUnJXk85oayhtgQ9m7eYsHjuJxwxy3rXeu3B7xtgIZVupzpGSMwMVBcDhfkyboVujryz8DfJIkO8ANdwwIDAQAB" )  ; ----- DKIM key mail for mondomaine.fr
```

Lorsque je crée le TXT chez OVH je ne peux pas entré toute la clé ou alors je rentre la mauvaise.

J'ai compris que je devais entrée 

`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3D924haJ80mtXMm+YrRdb2ISgyxAtzXLzVc9wkBf/3W1uVOtcJ97trF7sRoDH5a0bkXWDV41APfY4Ja2lvYpmHV9cCDnM5egK09x7HgJrlOM3OnMk4VtCm+9hAbAafsKeayuRy4ONboy6OsLFHDOWxpai8e/vNxKXeSmEeyVdHqZaFekvbfM81FYdPn7JIfcKcrqgPknQHs642`

et

`DJIxDvBF7qolwHc0APYQhxEW1hARCf8vLWKrnz1p+xe9TlYvXQK26HaCUnJXk85oayhtgQ9m7eYsHjuJxwxy3rXeu3B7xtgIZVupzpGSMwMVBcDhfkyboVujryz8DfJIkO8ANdwwIDAQAB`

En tant que p=

C'est bien cela ?

**Comment by Hydrog3n** [comment]
Salut, la clé est bien trop longue pour OVH tu dois rajouter une var d'env `-e OPENDKIM_KEY_LENGTH=1024` en docker run ou avec docker-compose 

```
environement:
  - OPENDKIM_KEY_LENGTH=1024
```

Du coup la clé sera plus courte et passera dans OVH. C'est à ovh d'augmenter leur champs TXT.

**Comment by Yfksw65** [comment]
Ok je vois.
Si je l'ajoute dès a présent ca va me régénérer une clé ?

**Comment by Yfksw65** [comment]
J'ai ma réponse, oui ca ma bien régénérer une nouvelle (clé, suppression des anciennes  + docker-compose up -d)

Je viens de l'ajouter sur OVH :) 

J'attend la propagation et test pour valider

**Comment by Yfksw65** [comment]
Bon très rapide, 10/10 sur Mail-Tester

Merci beaucoup Hydrog3n !

**Comment by Hydrog3n** [comment]
Pas de soucis ;)
