### ISSUE TITLE
Reverse Proxy config and example docker-compose.yml have wrong ports for nginx.

### ISSUE THREAD

**Issue by Lordmau5** [hardware/mailserver#119]
As for the specification, the default syntax is `HOST:CONTAINER`, but your example and wiki entry have it as `CONTAINER:HOST`.

With the default, an error is popping up, saying that port 80 is already bound.

Docker-compose documentation:
https://docs.docker.com/compose/compose-file/#ports

**Comment by hardware** [comment]
I do not see any error in this example :

```
ports:
    - "80:8000"
    - "443:4430"
```
80 = HOST
8000 = CONTAINER

> With the default, an error is popping up, saying that port 80 is already bound.

Because you already have a program that listens on port 80.

**Comment by Lordmau5** [comment]
Oh my bad. Yea, I was trying to setup NGINX on the main system and have the internal NGINX of the container be on port 8000. Of course, since the default config was different, the container couldn't start since the port was in use already.

Changing the config managed to get the container working :)

Due to it being a local VM for testing, I didn't fully manage to get routing to work, but that's not a big deal, I can handle that at some other point :)


Thanks for the quick reply!
