### ISSUE TITLE
Spam doesn't seem to be learn

### ISSUE THREAD

**Issue by mammique** [hardware/mailserver#120]
Hi, I've fed my Spam folder with garbage emails, however when I receive the very same spam it won't be marked as spam, the X-Spam-Score remains about the same… Is the spam stack learning from Spam folder? Or maybe I need to tune it?

Thank you,

Camille.

**Comment by hardware** [comment]
Spam is learn once a day : https://github.com/hardware/mailserver/blob/master/rootfs/etc/cron.d/spamassassin

But this is not the right method, in the next version, spam e-mail will be learn with Dovecot Antispam plugin and realtime mailtrain with Rspamd.

https://wiki2.dovecot.org/Plugins/Antispam

**Comment by hardware** [comment]
Duplicate : https://github.com/hardware/mailserver/issues/110

**Comment by mammique** [comment]
Thanks for you reply, yes I've read that before posting, but some spams are there in multiple versions for many days, it doesn't seem to increase the X-Spam-Score. Is there any way to tune this? Realtime would be great indeed, will the X-Spam-Score algorithm be different with rspamd?

Merci,

Camille.

**Comment by hardware** [comment]
> Thanks for your reply, yes I've read that before posting, but some spams are there in multiple versions for many days, it doesn't seem to increase the X-Spam-Score.

On my server it works great by learning takes sometimes.

> will the X-Spam-Score algorithm be different with rspamd ?

I don't know, probably.

**Comment by mammique** [comment]
OK je vais attendre un peu pour voir si ça s'améliore à la longue.

Merci,

Camille.

**Comment by hardware** [comment]
Le passage à Rspamd est prévu après la sortie de Debian Stretch. Je suis en train de le tester sur une VM de test pour voir comment l'intégrer à l'image docker et voir un peu comment il réagit. Je vais commencer par une phase beta d'ici la fin du mois de juin et si tout est bon, la v1.1 devrait sortir cet été :)

**Comment by mammique** [comment]
Génial, bravo et merci !
