### ISSUE TITLE
Port not accessible

### ISSUE THREAD

**Issue by hsaklecha** [hardware/mailserver#124]
I have deployed this server on cent os and opened the port 8888 for my network, but i am not able to access the port, niether i see it opened on my machine, is there any setting to be done with this docker container in docker-compose.yml

**Comment by denji** [comment]
`docker version`, `docker info`

`firewall-cmd --get-active-zones` ->  `firewall-cmd --permanent --zone=<ACTIVE-ZONE> --list-all`

**Comment by hsaklecha** [comment]
How does this will help, i have to know the way to expose 8888 from docker container on my server so that i can access it outside.
