### ISSUE TITLE
Add automatic GPG encryption with Zeyple

### ISSUE THREAD

**Issue by farfeduc** [hardware/mailserver#129]
Could it be possible to add this feature ?
 -> https://github.com/infertux/zeyple

Thanks

**Comment by hardware** [comment]
Automatic GPG encryption will be available this week-end in 1.1 version.

```
ENABLE_ENCRYPTION=true
```

**Comment by hardware** [comment]
@farfeduc Zeyple is now available in 1.1-beta version.  

https://github.com/hardware/mailserver/tree/v1.1#automatic-gpg-encryption-of-all-your-e-mails

Enjoy !

![encrypt](http://i.imgur.com/fv0ANyw.png)

**Comment by 1n5aN1aC** [comment]
I'm not sure if I can get any more excited for v1.1 !
