### ISSUE TITLE
Reset RainLoop admin password

### ISSUE THREAD

**Issue by italoandrade** [hardware/mailserver#131]
How can I reset the RainLoop admin password?

**Comment by hardware** [comment]
https://github.com/RainLoop/rainloop-webmail/issues/28

**Comment by italoandrade** [comment]
Yeah, I found that link, but I don't know how can I found this file on a docker :/

**Comment by hardware** [comment]
In your docker volume (look your docker-compose.yml)

**Comment by italoandrade** [comment]
Ok. How can I find the real path to the volume written on the dockercompose?

**Comment by hardware** [comment]
``` 
rainloop:
    volumes:
        - /mnt/docker/rainloop:/rainloop/data
``` 

`/mnt/docker/rainloop/_data_xxxx/default/configs/application.ini`

**Comment by italoandrade** [comment]
Thank you. It was solved..
