### ISSUE TITLE
Question: About spam learning

### ISSUE THREAD

**Issue by sknight80** [hardware/mailserver#137]
Hi,

I hope I used the right platform for my question.  I was wondering if the system can auto-learn which email is spam and which is not based on users?  If so, what should I set up?

Thanks,
Istvan

**Comment by denji** [comment]
ham - `/cur/` , spam - `/.Spam/cur/`
```
30 02 * * * root /usr/bin/sa-learn --ham /var/mail/vhosts/*/*/mail/cur/*
40 02 * * * root /usr/bin/sa-learn --spam /var/mail/vhosts/*/*/mail/.Spam/cur/*
```
