### ISSUE TITLE
cron error from logrotate

### ISSUE THREAD

**Issue by pjeby** [hardware/mailserver#139]
Just got this email from the container:

```
etc/cron.daily/logrotate:
invoke-rc.d: action rotate is unknown, but proceeding anyway.
invoke-rc.d: policy-rc.d denied execution of rotate.
```

Googling it finds me this [rsyslog fix committed in 2015](https://github.com/ouvrages/rsyslog/commit/ad4cc8949c9caa1e3c95389238f0b637a5325fa2), but which appears to not be applied in this container's `/etc/logrotate.d/rsyslog`.  But the build doesn't generate that file, so it appears that it's an older rsyslog version installed.  The file date in the container is December 2015, so perhaps the fix hadn't made it downstream to the debian package yet.

I must confess I lack the debian-fu to investigate further.  :)

**Comment by hardware** [comment]
I never had this error. Anyway, I will switch the master branch (1.0) to Debian Stretch, maybe this issue will be solved.

**Comment by hardware** [comment]
I think you can ignore this warning, this is probably nothing serious. If you have time, you can try the latest 1.1 version. 

`1.1-stable` will be released this week-end https://github.com/hardware/mailserver/issues/122

**Comment by vizv** [comment]
I got the error from time to time... (I have a catch-all email account setup).

I got this today:

```
...
Received: by ****.****.com (Postfix, from userid 0)
	id *************; Sun,  3 Sep 2017 06:33:22 +0000 (UTC)
From: root@****.com (Cron Daemon)
To: root@****.com
Subject: Cron <root@****> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <***>
Date: Sun,  3 Sep 2017 06:33:22 +0000 (UTC)

/etc/cron.daily/logrotate:
pkill: pidfile not valid
Try `pkill --help' for more information.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of rotate.
```

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/commit/160c222d36ba05b8465d87b0014c4b801f91aa33

**Comment by vizv** [comment]
Thanks, this should fix the problem, it's not a serious issue, but quite annoying.

**Comment by ksylvan** [comment]
How risky is it to run `1.1-latest` versus `1.1-stable`? ;-) I'm tempted to switch one of my servers to run `1.1-latest`.

**Comment by hardware** [comment]
I run the `1.1-latest` on 2 servers permanently, It's not very risky, all builds on this branch are validated through the CI automation system, so it's pretty safe. `1.1-stable` is useful when you want a more tested build.
