### ISSUE TITLE
Question: v1.1 migration and existing DKIM keys

### ISSUE THREAD

**Issue by ksylvan** [hardware/mailserver#140]
In v1.1-beta the DKIM keys are generated here: `/mnt/docker/mail/dkim/domain.tld/public.key`

In 1.0-stable, they were here: `/mnt/docker/mail/opendkim/domain.tld/mail.txt`

Would it work to rename the `/mnt/docker/mail/opendkim` directory to `/mnt/docker/mail/dkim` and rename the file `mail.txt` to `public.key` and the private key as well before bringing up the v1.1 beta mailserver stack?

I'm suggesting this so existing users don't have to update their DNS DKIM records with new keys.

If that works, I suggest the Wiki page here be updated: https://github.com/hardware/mailserver/wiki/Migrating-from-1.0-stable-to-1.1-beta

**Comment by hardware** [comment]
All of this is done automatically, no need to regenerate the key pair DKIM :wink:

https://github.com/hardware/mailserver/blob/b69538979127900650202a72e19f630de738d996/rootfs/usr/local/bin/run.sh#L156-L161

**Comment by ksylvan** [comment]
Fantastic! Thank you.
