### ISSUE TITLE
[Debian Stretch] [Version 1.0] SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by hardware** [hardware/mailserver#142]
Hi all,

I have an error when I build master branch with Debian Stretch. I do not see what can cause this issue. After hours of research, i can't find any solution. Maybe it's a bug with OpenSSL version with Debian Stretch but i haven't any problem with 1.1 branch.

Does anyone have any idea ?

**Error** : `SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252`
**Commit** : https://github.com/hardware/mailserver/commit/c47f209db8720a2bb1fdb0d64ed62f5cda20869f
**Build** : https://travis-ci.org/hardware/mailserver/builds/267346943

```
docker exec mailserver_default /bin/sh -c "openssl s_client -ign_eof -connect 0.0.0.0:587 -starttls smtp < /tmp/tests/email-templates/internal-user-to-existing-user.txt"
139858838807808:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 228 bytes and written 209 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1503431407
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
make: *** [Makefile:89: fixtures] Error 1
```

https://github.com/hardware/mailserver/blob/c47f209db8720a2bb1fdb0d64ed62f5cda20869f/Makefile#L92

**Comment by pjeby** [comment]
Everything I can find about that error message is about an incompatible cipher or protocol version, either AES or 3DES, or TLSv1 vs TLSv1_1.  At a guess, I'd say there's something in postfix's tls-related config that's not compatible with stock openssl.  I'd check the stock postfix conf on Jessie with `postconf|grep _tls_` to see how their settings differ.  The main.cf in this image sets a fair number of non-default TLS settings; maybe dial as many of them back to Jessie stock values as possible and see if it works, then put stuff back till it breaks again.

**Comment by hardware** [comment]
I thought the same thing but this exact same update-to-stretch process work well in another commit : 8010ea7 This is insane...

**Comment by hardware** [comment]
I think there is a little thing between this two commit who screw up everything, but I can not find what.
