### ISSUE TITLE
system clock in container

### ISSUE THREAD

**Issue by z0rg-company** [hardware/mailserver#143]
Hi! Yours project is really cool!
I using arch linux, and time in my containers is set to UTC. Little patch fixed this.
It's will be useful to add 
```
Volumes
- /etc/localtime:/etc/localtime:ro
```

to default docker-compose.yml. 

Thanks a lot!

**Comment by hardware** [comment]
Added in docker-compose.yml.

The system timezone is fairly irrelevant for postfixadmin, nsd and nginx.
