### ISSUE TITLE
Automatic updating of letsencrypt certs?

### ISSUE THREAD

**Issue by 1n5aN1aC** [hardware/mailserver#145]
Just a suggestion / feature request:

Your setup works GREAT, by the way, and now I'm trying to setup the cert to be automatically updated, but having a hard time setting up letsencrypt certificates to be automatically updated.

I feel like this SHOULD be as easy as adding another docker image to the docker-compose, and mapping the right folders through tot he right containers.  I even have a vhost in nginx-boringssl that's just static files for my webroot, so I should be able to just point the needed verification files there, but have had no success thus far.

Anyways, sorry for the long-winded way of suggesting / requesting automatic updating of letsencrypt certs!

**Comment by ksylvan** [comment]
Look at my work here: https://github.com/ksylvan/docker-mail-server

I install a `/usr/local/bin/renew` script on the target host that uses the `/usr/local/bin/certbot` which is a wrapper around the `letsencrypt` docker image.

Then a `cron` job to kick it off, and I get daily emails sent to `postmaster` that look like this:

```
From: "root" <root@sylvan.com>
Date: Sun, 20 Aug 2017 02:19:04 -0700
To: postmaster
Subject: Cert is still valid (for 71 days)

Saving debug log to /var/log/letsencrypt/letsencrypt.log
openssl not installed, can't check revocation

-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: mail.sylvan.com
    Domains: mail.sylvan.com,postfixadmin.sylvan.com,sylvan.com,webmail.sylvan.com,www.sylvan.com
    Expiry Date: 2017-11-05 03:18:00+00:00 (VALID: 71 days)
    Certificate Path: /etc/letsencrypt/live/mail.sylvan.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/mail.sylvan.com/privkey.pem
```
When the certificate is 5 days from expiry, the `certbot renew` process kicks off.

**Comment by 1n5aN1aC** [comment]
@ksylvan Thanks for that!  I've made some adaptations, and I think it's working pretty good!

I would still prefer everything related to the project be contained inside the docker-compose, but it's working, so I suppose I'm happy.

**Comment by ksylvan** [comment]
@1n5aN1aC happy to help. If you made any adaptations that you believe make things better or could be generally useful, feel free to give back a pull-request.

**Comment by hardware** [comment]
I don't think I'll add an ACME client in this docker image, this is not an easy task given the number of different cases. Most people manage themselves their certificates and the renewal procedure. I want to keep this docker image as simple as possible, even if it is less easy to configure.

**Comment by denji** [comment]
/etc/cron.d/mailserver

docker exec ...

**Comment by 1n5aN1aC** [comment]
Disappointed there isn't a practical way to do it other than stopping the nginx docker to do so on a cron jab or something. (at least that I've found)

However, you have spoken and I understand, thanks for your work!

**Comment by ksylvan** [comment]
In practice it's not a huge amount of downtime.

Stop the ngoni, renew the veers, start nginx... but only when you need to.

About 10-15 seconds every 3 months.

**Comment by denji** [comment]
https://community.letsencrypt.org/t/how-to-nginx-configuration-to-enable-acme-challenge-support-on-all-http-virtual-hosts/5622
