### ISSUE TITLE
Feature request: Integrate dovecot and rspamd to learn ham/spam

### ISSUE THREAD

**Issue by ksylvan** [hardware/mailserver#146]
Question: What would it take to set up the included `dovecot` and `rspamd` to work together so that in response to a user moving things in and out of their IMAP Spam folder, `rspamd` learns it as ham or spam?

Here is the kind of setup I'm talking about: https://kaworu.ch/blog/2014/03/25/dovecot-antispam-with-rspamd/

**Comment by denji** [comment]
https://github.com/hardware/mailserver/tree/v1.1/rootfs/etc/dovecot/sieve

**Comment by hardware** [comment]
It is already implemented : 

https://github.com/hardware/mailserver/blob/500ae4725b9b4168e6e7c1103fe8504ed9bdfe1b/rootfs/etc/dovecot/conf.d/90-sieve.conf#L15-L24

**Comment by denji** [comment]
@hardware without curl better?

* `rspamc learn_spam < /dev/stdin`
* `rspamc learn_ham < /dev/stdin`

**Comment by ksylvan** [comment]
Thanks for the detailed responses. Have an awesome day.

**Comment by hardware** [comment]
@denji yes, i think it could be better with rspamc client command. I noticed that curl causes some errors like "http error occurred: Not found" in rspamd logs.

**Comment by hardware** [comment]
Example : 

![screenshot_20170824_211414](https://user-images.githubusercontent.com/327354/29684171-47a18aae-8911-11e7-8f71-42e72bcf0cd6.png)

I fix this in the next commit.

**Comment by hardware** [comment]
I found something interesting, maybe it's not bug. Rspamd return 404 error when he has already learned a mail :

```
rspamc learn_spam < external-spam-to-existing-user.txt
Results for file: external-spam-to-existing-user.txt (0.000 seconds)
HTTP error: 404, <undef> has been already learned as ham, ignore it
```

With a new mail :

```
rspamc learn_ham another-mail-test.txt
Results for file: another-mail-test.txt (0.000 seconds)
success = true;
```

Anyway, i will use rspamc client command instead.
