### ISSUE TITLE
Postfix / OpenSSL 1.1.0 "no shared cipher" and "alert handshake failure" errors with ECDSA certificates

### ISSUE THREAD

**Issue by Wonderfall** [hardware/mailserver#147]
Bon le titre exagère un peu puisque maintenant le serveur mail est fonctionnel.
Cela dit, j'ai eu une erreur avec TLS qui bloquait le serveur SMTP, l'une d'elle est par exemple : 

```
2017-08-24T19:23:25.515590+00:00 drogon postfix/submission/smtpd[714]: warning: TLS library problem: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1382:SSL alert number 40
```

La chose à laquelle j'ai tout de suite pensé, c'est mon certificat LE qui utilise P-384, OCSP Must-Staple, tout ça tout ça, donc je me suis dit que ça venait peut-être de là. J'ai essayé de passer au self-signed en virant le volume et ça marche effectivement désormais. Cela dit je pense qu'on peut s'intéresser au problème plutôt que de le contourner ?

En vrac, j'ai d'autres erreurs dans les logs, telles que : 

```2017-08-24T19:31:16.475679+00:00 drogon rspamd[532]: <455c3c>; lua; rbl.lua:93: error looking up 106.81.4.46.zen.spamhaus.org: server fail```

La même chose avec `rspamd.com`.

Ah et aussi mes notifications de Ossec sont parfois rejetées et/ou marquées en spam, parfois non, je pense que c'est dû au rate limiting, mais pas sûr.

**Comment by hardware** [comment]
Salut @Wonderfall 

Oui je pense qu'il faut trouver une solution à ton problème de certificat, peut-être que c'est lié à un autre problème que j'arrive pas à régler sur la branche 1.0-debian-stretch (https://github.com/hardware/mailserver/issues/142). En tout cas, dans ma procédure d'intégration je test bien le serveur avec un certificat Let's Encrypt :

https://github.com/hardware/mailserver/blob/500ae4725b9b4168e6e7c1103fe8504ed9bdfe1b/Makefile#L78

Peux-tu me donner plus de précision sur le type de certificat que tu utilises et la méthode pour le génerer ?

> En vrac, j'ai d'autres erreurs dans les logs

Peux-tu me donner les logs ?

Merci pour ce retour en tout cas.

**Comment by Wonderfall** [comment]
Salut, la méthode est celle décrite dans mon article : https://psychedeli.cat/configuration-https-2017/
Pour les logs, ce sont des entrées comme j'ai postées ci-dessus, des timeouts notamment vers spamhnaus et rspamd.com.

**Comment by denji** [comment]
>  warning: TLS library problem: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1399:SSL alert number 46

unknown CA?

**Comment by Wonderfall** [comment]
>unknown CA?

Let's Encrypt. It worked with the previous image (1.0).

**Comment by hardware** [comment]
Peux-tu me donner ton custom.cnf d'openssl ? Sans les sous domaines, c'est pas utile :-)

**Comment by hardware** [comment]
Est-ce que ton nginx utilises exactement le même certificat ?

Peux-tu configurer le serveur SMTP pour tracer plus d'information sur l'activité TLS.

```bash
# /mnt/docker/mail/postfix/custom.conf

smtpd_tls_loglevel = 2
```

Voir le niveau 3 mais ça va commencer à être très verbeux parce qu'il dump au format ASCII le handshake TLS.

**Comment by Wonderfall** [comment]
Voilà ce que ça donne au niveau 2 : 

```
2017-08-27T14:58:41.542659+00:00 drogon postfix/submission/smtpd[575]: initializing the server-side TLS engine
2017-08-27T14:58:41.551184+00:00 drogon postfix/tlsmgr[577]: open smtpd TLS cache btree:/var/lib/postfix/smtpd_scache
2017-08-27T14:58:41.698056+00:00 drogon postfix/tlsmgr[577]: tlsmgr_cache_run_event: start TLS smtpd session cache cleanup
2017-08-27T14:58:41.756288+00:00 drogon postfix/submission/smtpd[575]: connect from unknown[172.18.0.1]
2017-08-27T14:58:41.783980+00:00 drogon postfix/submission/smtpd[575]: setting up TLS connection from unknown[172.18.0.1]
2017-08-27T14:58:41.784066+00:00 drogon postfix/submission/smtpd[575]: unknown[172.18.0.1]: TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:@STRENGTH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!RC2:!RC4:!MD5:!PSK:!SRP:!DSS:!AECDH:!ADH"
2017-08-27T14:58:41.784237+00:00 drogon postfix/submission/smtpd[575]: SSL_accept:before SSL initialization
2017-08-27T14:58:41.784250+00:00 drogon postfix/submission/smtpd[575]: SSL_accept:before SSL initialization
2017-08-27T14:58:41.784313+00:00 drogon postfix/submission/smtpd[575]: SSL3 alert write:fatal:handshake failure
2017-08-27T14:58:41.784320+00:00 drogon postfix/submission/smtpd[575]: SSL_accept:error in error
2017-08-27T14:58:41.784327+00:00 drogon postfix/submission/smtpd[575]: SSL_accept error from unknown[172.18.0.1]: -1
2017-08-27T14:58:41.784344+00:00 drogon postfix/submission/smtpd[575]: warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:1404:
2017-08-27T14:58:41.784448+00:00 drogon postfix/submission/smtpd[575]: lost connection after STARTTLS from unknown[172.18.0.1]
2017-08-27T14:58:41.784511+00:00 drogon postfix/submission/smtpd[575]: disconnect from unknown[172.18.0.1] ehlo=1 starttls=0/1 commands=1/2
```

Le custom.cnf d'OpenSSL : https://paste.targaryen.house/?7ecf62df650729d8#KWT8NpRjKOFdr3X3K3r0iXssMkAaIs3gdbd3+Eyo0yY=

**Comment by hardware** [comment]
On dirait que c'est les ciphers qui sont en cause :

> SSL routines:tls_post_process_client_hello:no shared cipher

Peux-tu essayer avec les paramètres suivants :

```
# /mnt/docker/mail/postfix/custom.conf

smtpd_tls_loglevel = 2
smtpd_tls_exclude_ciphers = aNULL
```

Mais je doute que ça soit soit parce que ceux que j'exclus sont tous déconseillés :

`aNULL,eNULL,EXPORT,DES,3DES,RC2,RC4,MD5,PSK,SRP,DSS,AECDH,ADH`

**Comment by hardware** [comment]
Pour les erreurs DNS, j'ai ajouté le nom du résolveur explicitement dans la conf de rspamd, j'ai aussi ajouté un second en backup au cas où.

```inc
# /etc/rspamd/local.d/options.inc

dns {
  enable_dnssec = true;
  timeout = 4s;
  retransmits = 5;
  # In this case, 84.200.69.80 (resolver1.dns.watch) public resolver
  # will be used as a backup when local resolver is down
  # https://dns.watch/
  nameserver = "master-slave:127.0.0.1:53:10,84.200.69.80:53:1";
}
```

J'en ai profité aussi pour activer DNSSEC et augmenter le timeout, par défaut il est à 1 seconde, ce qui est trop court.

**Comment by hardware** [comment]
J'ai réussi à reproduire ton problème en générant un certificat **ECDSA P-384** auto-signé de cette manière :

```
openssl req -new -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 \
      -days 3658 -sha256 -nodes -x509 \
      -subj "/C=FR/ST=France/L=Paris/O=Mailserver/OU=Mail/CN=*.${DOMAIN}/emailAddress=postmaster@${DOMAIN}" \
      -keyout "$KEYFILE" \
      -out "$CERTFILE"
```

Et effectivement, j'ai bien les mêmes erreurs.

**Serveur** :

```
error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared
cipher:ssl/statem/statem_srvr.c:1422
```

**Client** :

```
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake
failure:ssl/record/rec_layer_s3.c:1382:SSL alert number 40
```
Par contre en utilisant `ec_paramgen_curve:prime256v1`, la négociation se déroule sans soucis.

En fait il y a 2 causes à ce problème, d'abord OpenSSL depuis la version **1.1.0** (1.0.1 sous Jessie) qui accepte plus de traiter une courbe elliptique différente de celle qui est temporairement négociée (Server Temp Key) lors de l'échange Diffie Hellman.

La second problème se trouve au niveau de Postfix, par défaut il utilise la courbe **P-256 du NIST** (aka prime256v1) depuis la version 2.6 et Postfix ne peut utiliser **qu'un type de courbe lors de son exécution** :

> With Postfix prior to 3.2, only a single server-side curve can be configured, by specifying a suitable EECDH "grade".

L'auto négociation de la courbe avec OpenSSL ≥ 1.0.2 est disponible uniquement que depuis la version 3.2 de Postfix :

> Postfix ≥ 3.2 supports the curve negotiation API of OpenSSL ≥ 1.0.2. When using this software combination, the default setting of "smtpd_tls_eecdh_grade" changes to "auto", which selects a curve that is supported by both the server and client. The list of candidate curves can be configured via "tls_eecdh_auto_curves", which can be used to configure a prioritized list of supported curves (most preferred first) on both the server and client. The default list is suitable for most users.

Malheureusement cette version ne sera pas livrée avec Debian Stretch :(

Pour moi c'est aux développeurs d'OpenSSL de résoudre le problème et ne de pas imposer une telle contrainte. Par exemple, si je mets `secp384r1`, Postfix ne pourra plus que négocier avec des certificats utilisant P-384, c'est super contreignant.

Sinon la solution est simple pour toi, tu peux dire à Postfix d'utiliser P-384 :+1: 

```
# /mnt/docker/mail/postfix/custom.conf
tls_eecdh_strong_curve = secp384r1
```

Et ton problème sera résolu :+1: 
Je vais mettre à jour le readme en précisant cela.

**Sources** :

* https://github.com/openssl/openssl/issues/2033
* https://bugzilla.redhat.com/show_bug.cgi?id=1473971
* http://www.postfix.org/FORWARD_SECRECY_README.html

**Comment by hardware** [comment]
@Wonderfall j'ai mis une petite note dans le readme :

https://github.com/hardware/mailserver/commit/32765eeddaf93f8b6ec926edd2e80865b532c6c4#diff-04c6e90faac2675aa89e2176d2eec7d8R366

**Comment by Wonderfall** [comment]
Je confirme que ça marche à nouveau, merci !
