### ISSUE TITLE
Redis : le conteneur ne se lance pas avec le paramètre net.core.somaxconn=1024

### ISSUE THREAD

**Issue by Nebukad93** [hardware/mailserver#149]
Si le paramètre suivant est présent dans mon docker-compose :
```
sysctls:
- net.core.somaxconn=1024
```
J'obtiens l'erreur suivante pendant la création des conteneurs : 
`ERROR: for redis  Cannot start service redis: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"open /proc/sys/net/core/somaxconn: no such file or directory\""
`

Si je le commente, tout va bien.

**Comment by Wonderfall** [comment]
Je n'utilise pas non plus ce paramètre comme il est incompatible avec ma version de docker-compose (v1). Pourquoi est-il utile ?

**Comment by hardware** [comment]
Tu utilises bien la version 2.1 du fichier de docker-compose ?
https://docs.docker.com/compose/compose-file/compose-file-v2/#sysctls

Sinon tu peux retirer ce paramètre, il est utile que pour des questions de performances mais c'est inutile si ton serveur est peu utilisé.

Si tu regardes un peu les logs de redis, il va te sortir d'autres paramètres du kernel qui peuvent être aussi modifiés pour améliorer les performances. Le mieux c'est de laisser les paramètres par défaut de la distribution et de ton hébergeur au niveau de la gestion de la mémoire dans sysctls.conf.

J'ai eu des problèmes sur mon serveur de test en essayant de suivre toutes les recommandations de redis. 

Donc pour résumer, si `net.core.somaxconn` ne fonctionne pas chez toi, tu peux le retirer sans soucis du docker-compose.yml et appliquer les recommandations uniquement quand tu sais ce que tu fais :D

**Comment by hardware** [comment]
Je vais retirer la directive `sysctls`. En plus de pas être utile pour 95% des gens, si ça apporte des problèmes aussi, ça vaut pas le coup.

**Comment by Nebukad93** [comment]
Oui je suis bien en compose 2.1.
J'ai effectivement virer la directive et c'est passé nickel après.

Merci
