### ISSUE TITLE
MariaDB container IP not found with docker embedded DNS server

### ISSUE THREAD

**Issue by guillaumedc** [hardware/mailserver#150]
Hi,

Is it possible to use the mailserver without NSD?
My DNS records are already handle by an another server.
I have to precise that it previously run a mail server on my own with exim4 + dovecot + sieve + DKIM so DNS records are functionnal.

I tried to comment nsd container configuration in the docker-compose file but I got an error at runtime:
<pre><code>
[INFO] Database hostname not found in /etc/hosts, try to find container IP with docker embedded DNS server   
[ERROR] Container IP not found with embedded DNS server... Abort !
</code></pre>

Thanks by advance

**Comment by ksylvan** [comment]
I'm using the setup without the NSD container with no issues.

**Comment by hardware** [comment]
Can you give me the content of your docker-composer file and your docker version ?

**Comment by guillaumedc** [comment]
Docker version 17.06.1

I already have a MariaDB container running with a postfix user and database on it.   
So I didn't define an another one in the docker-compose.

<pre><code>
version: '2.1'

services
  mailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    domainname: domain.tld                  # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    restart: always
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
    # - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=xxxxx                        # MariaDB database password (required)
      - RSPAMD_PASSWORD=xxxxx               # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...   # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                    # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true               # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                 # Disable virus scanning
    # - DISABLE_SIGNING=true                # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true            # Disable greylisting policy
    # - DISABLE_RATELIMITING=true           # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - /srv/mail:/var/mail
      - /srv/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb
      - redis

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: domain.tld
    hostname: mail
    restart: always
    environment:
      - DBPASS=xxxxx
    depends_on:
      - mailserver
      - mariadb

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: always
    volumes:
      - /srv/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb

  # Web server
  # https://github.com/Wonderfall/dockerfiles/tree/master/boring-nginx
  # https://nginx.org/
  # Configuration : https://github.com/hardware/mailserver/wiki/Reverse-proxy-configuration
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /srv/nginx/sites-enabled:/sites-enabled
      - /srv/nginx/conf:/conf.d
      - /srv/nginx/log:/var/log/nginx
      - /srv/nginx/certs:/certs
    depends_on:
      - mailserver
      - postfixadmin
      - rainloop

  # Cache Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - /srv/redis/db:/data
</code></pre>

**Comment by hardware** [comment]
> So I didn't define an another one in the docker-compose.

```
[ERROR] Container IP not found with embedded DNS server... Abort !
```

That's why it doesn't work. You must have your mariadb container on the same docker private network. Otherwise mariadb container IP can not be obtained with the internal docker DNS resolver.

If you want it to work, add an extra hosts like this :

```yml
mailserver:
    extra_hosts:                 - Required for external database (on other server or for local databases on host without docker)
      - "mariadb:xx.xx.xx.xx"     - Replace with IP address of MariaDB server
```

**Comment by guillaumedc** [comment]
Sorry, I didn't copy the right config.

Of course, I used extra_hosts.
Actually, I used an already existing redis accessible via IP too.

<pre><code>
    extra_hosts:                            # - Required for external database (on other server or for local databases on host without docker)
      - mariadb:172.19.0.2                  # - Replace with IP address of MariaDB server
      - redis:172.19.0.3                    # - Replace with IP address of Redis server
</code></pre>

**Comment by hardware** [comment]
Give me the result of following commands please :

```bash
# docker exec -ti mailserver bash

cat /etc/resolv.conf
cat /etc/hosts
cat /var/mail/postfix/spool/etc/hosts
cat /var/mail/postfix/spool/etc/resolv.conf
dig A mariadb
ping mariadb
ping 172.19.0.2 
ping redis
ping 172.19.0.3
docker logs your_mariadb_container
```

**Comment by hardware** [comment]
I tried to reproduce your issue on my end but all this methods works without any problem.

**10.1.1.12** is my backup database instance.

```yml
# Recommended way
extra_hosts:
    - mariadb:10.1.1.12
    - redis:10.1.1.12

# docker exec mailserver cat /etc/hosts | grep "10.1.1"
# 10.1.1.12	mariadb
# 10.1.1.12	redis

# docker exec mondedie-mail getent hosts 10.1.1.12
# 10.1.1.12       mariadb

# Logs :
# [INFO] Database hostname found in /etc/hosts
```

```yml
# Not recommended but works too
environment:
    - DBHOST=10.1.1.12
    - REDIS_HOST=10.1.1.12

# Logs :
# [INFO] Database hostname not found in /etc/hosts, try to find container IP with docker embedded DNS server
# [INFO] Container IP found, adding new record in /etc/hosts
```

```yml
# With docker-compose file v1 and databases in the same file
links:
    - redis:redis
    - mariadb:mariadb

# Logs :
# [INFO] Database hostname found in /etc/hosts
```

```yml
# With docker-compose file v2, default values, mariadb/redis in the same file

# [INFO] Database hostname not found in /etc/hosts, try to find container IP with docker embedded DNS server
# [INFO] Container IP found, adding new record in /etc/hosts
```

The last method works because the `run.sh` script can resolve and inject databases hostname thanks to an embedded DNS server (127.0.0.1:53) in user-defined networks.

```bash
# dig A mariadb @127.0.0.11 +short
172.19.0.x

# dig A redis @127.0.0.11 +short
172.19.0.x

# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

After the full execution of `run.sh`, Unbound is used instead of docker embedded DNS server :

```
# cat /etc/resolv.conf 
nameserver 127.0.0.1
```

https://github.com/hardware/mailserver/blob/447661582689a47aa74ba8d8ebe89815cd5d85d2/rootfs/etc/unbound/unbound.conf#L1-L3

But in all cases I need to inject all databases hostname in **/etc/hosts** file because Postfix run in a chroot jail, the processes run at a fixed low privilege and with file system access limited to the Postfix queue directories (/var/mail/postfix/spool).

https://github.com/hardware/mailserver/blob/447661582689a47aa74ba8d8ebe89815cd5d85d2/rootfs/services/postfix/run#L11-L14

https://github.com/hardware/mailserver/blob/447661582689a47aa74ba8d8ebe89815cd5d85d2/rootfs/usr/local/bin/run.sh#L225-L240

I hope it more clear now.

**Comment by guillaumedc** [comment]
I fixed all addresses of my contaiers with a static IP on the same network and it works!
Sorry for the inconvenience.
Thanks for you quick responses!
