### ISSUE TITLE
Erreur 4.7.1 Ratelimit \"user\" exceeded

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#152]
J'ai une erreur sur le Ratelimit, au bout de 10mails envoyés a la suite, dans les logs j'ai un message affichant **Ratelimit \"user\" exceeded** .
Du coup je comprend pas trop pourquoi mais je reçois 5mails sur 10 lorsque je les envoyé a la suite...

La config pour le Rate limiting est :
default_destination_rate_delay = 1s
default_destination_recipient_limit = 10

Par défaut le default_destination_recipient_limit = 10 est a 50 sur postfix me semble, serait il possible de le modifier ?
https://postfix.traduc.org/index.php/postconf.5.html#default_destination_recipient_limit
Merci !

**Comment by hardware** [comment]
Tu peux personnaliser la valeur comme tu le souhaites via le fichier custom.conf :

```ini
# /mnt/docker/mail/postfix/custom.conf

default_destination_rate_delay = 0s
default_destination_recipient_limit = 50
```

**Comment by tsedgwick1** [comment]
Ok merci pour l'info ! :)
J'ai du également modifié le smtputf8_enable=no sinon j'avais des caractères bizarres au lieu des caractères spéciaux, accents..
Autre chose lorsque je suis sur Gmail après la migration j'ai ma signature dkim qui est en fail alors que sur mail-tester les résultats montre que la signature est bien valide, je comprend pas trop pourquoi.

**Comment by hardware** [comment]
Peux-tu me donner le header du mail Gmail avec les résultats DKIM dedans ?

**Comment by tsedgwick1** [comment]
Oui pas de soucis ! 
https://paste.mondedie.fr/?f928170c164bf8b1#lwu0kj7ojdMDdf8D/RtS2aHjvoFL7Vdcwlcp++moJtk=
Je suis enregistré sur OVH et j'ai directement une entrée dkim, avant la migration ça posait pas de problème.
Mais étant donné que le chemin a changé pour la clé j'ai remis la nouvelle qui est en 1024bits au lieu de 2048.

**Comment by hardware** [comment]
Peux-tu envoyer un mail à checkmyauth@auth.returnpath.net ? Mets Test / Test en sujet et message. Tu vas recevoir un mail avec les résultats.

**Comment by hardware** [comment]
Je clos cette issue vu que ton problème initial est résolu. Pour ton problème avec DKIM, si tout est Ok avec mail-tester et auth.returnpath.net mais pas avec gmail c'est probablement du à la propagation de ton enregistrement DKIM sur le réseau, ça devrait être bon en attendant un peu.

**Comment by tsedgwick1** [comment]
Je n'ai pas répondu parce que j'avais pas de réponse de checkmyauth@auth.returnpath.net peut être que leur service est down.. ?
En effet c'est bon ça a été résolu après quelques jours la propagation s'est faite sans problème. 
Merci encore ! :)

**Comment by hardware** [comment]
Ah oui mince, faut utiliser `check-auth@verifier.port25.com`, l'autre est down depuis un moment déjà.

**Comment by j-schumann** [comment]
Sorry for warming up this old topic, but I receive the same error message, even after adjusting the postfix config as suggested.
A google search suggested the message comes from rspamd instead of postfix itself: https://rspamd.com/doc/modules/ratelimit.html
The configured user limit in https://github.com/hardware/mailserver/blob/master/rootfs/etc/rspamd/local.d/ratelimit.conf is two mails per user and minute, which is too low for me when cron jobs etc send multiple notifications using the same sender.

Is there a way to customize the rspamd config similar to the postfix/custom.conf, e.g. to add something to whitelisted_user?

**Comment by hardware** [comment]
You can override ratelimit.conf with a docker volume. I didn't find a way to customize rspamd in the same way as postfix.

**Comment by j-schumann** [comment]
Ok, thanks for the information. I already have a custom dockerfile with multiple adjustments/addons for the mailserver, just wanted to know if there is a preferred way as overwriting the complete file may cause problems with updates.
Can be closed again 👍
