### ISSUE TITLE
Timezone in containers

### ISSUE THREAD

**Issue by slima** [hardware/mailserver#154]
It would be great if could set timezone for containers via docker-compose file.

**Comment by hardware** [comment]
The system timezone is fairly irrelevant for all of docker images in this docker-compose file.

But you can add the following line in your docker-compose.yml to use the host OS timezone :

```yml
volumes:
  - /mnt/docker/mail:/var/mail
  - /etc/localtime:/etc/localtime:ro               
```

**Comment by slima** [comment]
Oh, thanks you!

**Comment by ksylvan** [comment]
To add another comment to this closed thread: having everything in UTC actually makes more sense.

It's only in the presentation layer (e.g RainLoop web UI, etc.) that the time zone makes any difference and that's already handled browser-side.
