### ISSUE TITLE
mailserver docker and wordpress docker

### ISSUE THREAD

**Issue by rogafe** [hardware/mailserver#158]
Hi, I am new to docker and i would to use mail server and WordPress and the same server can I do it ? 

PS: I am not a English native speaker sorry for my English

**Comment by hardware** [comment]
Like any other applications, create a noreply address with Postfixadmin (+ a sieve rule to discard all messages) and configure SMTP module on WordPress panel : 

| OPTION | VALUE |
| -- | -- |
| FROM EMAIL | noreply@domain.tld |
| Mailer | SMTP |
| SMTP Host | mail.domain.tld |
| SMTP Port | 587 |
| Encryption | Use TLS encryption (STARTTLS)  |
| Authentication | Use SMTP authentication |
| Username | noreply@domain.tld |
| Password | ************* |

**Comment by rogafe** [comment]
Ok thank you i will try it

**Comment by rogafe** [comment]
but i dont know how to install it do i have to modify the dockerfile or do i have to put the file to a specified folder ?

**Comment by ksylvan** [comment]
Maybe. :-)

Or you can just set up a bare Debian machine somewhere, set up your laptop with Ansible, and use my repo (mentioned in the README) to install everything.

**Comment by rogafe** [comment]
@ksylvan did you know if Ansible work fine with bash subsystem for windows ?
i will try it ( debian 8 or 9 ? )

**Comment by rogafe** [comment]
hi @ksylvan thanks you i will give it a try

**Comment by ksylvan** [comment]
Debian 9.

I think it should work with bash on Win 10. As long as you can install python 2 and `pip install ansible` on your control host (your local machine).
