### ISSUE TITLE
Postfix TLS with Let's Encrypt

### ISSUE THREAD

**Issue by jodumont** [hardware/mailserver#161]
Hi;

when i'm testing my services smtps and imaps with https://www.htbridge.com/ssl/
it say smtps use a self-sign certificate even i'm using Let's Encrypt

I was able to correct this by adding inside : **/mnt/docker/mail/postfix/custom.conf**
smtpd_tls_cert_file = /etc/letsencrypt/live/mail.domain.tld/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/mail.domain.tld/privkey.pem

## I wonder if it's possible to automatize this  
- for the IMAP it seams to be.

When I looked inside https://github.com/hardware/mailserver/blob/master/rootfs/etc/postfix/main.cf
and founded these two variables
- smtpd_tls_cert_file = {{ CERTFILE }}
- smtpd_tls_key_file = {{ KEYFILE }}

But my research and knowledge stuck more or less here

**Comment by hardware** [comment]
> I wonder if it's possible to automatize this

It's already automated since the creation of this docker image.

Please, give me the result of this commands : 
```
docker logs mailserver (just the first INFO lines)
docker exec mailserver postconf -h smtpd_tls_CAfile
docker exec mailserver postconf -h smtpd_tls_cert_file
docker exec mailserver postconf -h smtpd_tls_key_file
docker exec mailserver sh -c "timeout 1 openssl s_client -ign_eof -connect 0.0.0.0:587 -starttls smtp"
```

And your docker-compose file.

**Comment by ksylvan** [comment]
This has always worked for me, without a postfix `custom.conf` set up.
