### ISSUE TITLE
Use mail server to send notification from system users

### ISSUE THREAD

**Issue by guillaumedc** [hardware/mailserver#162]
Previously, I had a setup using exim4 and based on system users.
Cron jobs delivered reports directly sending mails.

Now that I use docker containers for postfix and users registered into a database, this mechanic does not work anymore.
Would it be possible to restore this behavior?

Thanks by advance

**Comment by hardware** [comment]
I think this is not possible with a docker image because this is an isolated linux system but you can try to setup sendmail mta run as a daemon on your host with a socket (don't use a port to not interfere with Docker). Sendmail should forward /etc/aliases entries locally. I don't know if this method works, but in theory it should.

http://www.sendmail.org/~ca/email/man/sendmail.html

**Comment by denji** [comment]
ssmtp

**Comment by hardware** [comment]
@guillaumedc this should be the solution, thanks @denji.

https://wiki.archlinux.org/index.php/SSMTP
https://wiki.archlinux.org/index.php/Msmtp

**Comment by ksylvan** [comment]
I use `ssmtp` configured on the host machine and it works great.

**Comment by guillaumedc** [comment]
Thanks to all of you for the quick responses.
I setup ssmtp and I am confident that it will do the trick.
I will see that tomorrow morning after backups crons execution ;)

**Comment by guillaumedc** [comment]
I configured ssmtp and I can send mails from system users but cron still can't.
Inside syslog, I can read:
```
Sep 14 13:31:01 hostname sSMTP[18104]: RCPT TO:<xxx@domain.tld> (553 5.7.1 <root@domain.tld>: Sender address rejected: not owned by user yyy@domain.tld)
Sep 14 13:31:01 hostname CRON[18101]: (root) MAIL (mailed 45 bytes of output but got status 0x0001 from MTA#012)
```

yyy@domain.tld is the mail account I use on remote SMTP server to send mails.
It works well if, as root user, I execute:
```
mail xxx@domain.tld < testmail
```

My revaliases config contains:
```
root:yyy@domain.tld:domain.tld:587
```

How did you managed to make it work?
Is it mandatory that the local user matches with the remote user in the ssmtp config?
I would prefer not to use root account in mail server (but maybe it's just a name and we don't care?).

**Comment by hardware** [comment]
> Is it mandatory that the local user matches with the remote user in the ssmtp config?

Yes, with the default configuration of this docker image, yes it is. Postfix reject when the client is not logged in as that MAIL FROM address owner or when the client is logged in, but the client login name doesn't own the MAIL FROM address.

But with an alias and using the domain rewrite directive, it should works : 

```ini
# Config file for sSMTP sendmail

# The person who gets all mail for userids < 1000
# Make this empty to disable rewriting
root=admin@domain.tld

# The place where the mail goes
mailhub=mail.domain.tld:587

# Where will the mail seem to come from
rewriteDomain=domain.tld

# Email 'From header's can override the default domain
FromLineOverride=yes

hostname=xxxxxxxx
UseTLS=Yes
UseSTARTTLS=Yes
AuthUser=admin@domain.tld
AuthPass=xxxxxxxxxxx


```

**Comment by guillaumedc** [comment]
I finally used MSMTP to send mailsfrom local machine using mail server in Docker container.
Thank for help provided.
