### ISSUE TITLE
Error zeyple : permission denied

### ISSUE THREAD

**Issue by AnthoDingo** [hardware/mailserver#164]
Hello,

Some error with permission : 
```
# docker exec -ti mailserver encryption.sh import-key YOUR_KEY_ID hkp://pgp.mit.edu
gpg: WARNING: unsafe ownership on homedir '/var/mail/zeyple/keys'
gpg: failed to create temporary file '/var/mail/zeyple/keys/.#lk0x000055d483b50a60.mail.bosco.ovh.889': Permission denied
gpg: keyblock resource '/var/mail/zeyple/keys/pubring.kbx': Permission denied
gpg: failed to create temporary file '/var/mail/zeyple/keys/.#lk0x000055d483b53920.mail.bosco.ovh.889': Permission denied
gpg: connecting dirmngr at '/var/mail/zeyple/keys/S.dirmngr' failed: Permission denied
gpg: keyserver receive failed: No dirmngr
```

```
# ls -la
total 52
drwxr-xr-x 13 1024 1024 4096 sept. 11 18:44 .
drwxr-xr-x  6 root root 4096 sept. 11 18:56 ..
drwxr-xr-x  3 1024 1024 4096 sept. 11 18:58 clamav
drwxr-xr-x  6 1024 1024 4096 sept. 11 18:44 dkim
drwxr-xr-x  2 1024 1024 4096 sept. 11 18:59 dovecot
drwx------  2 1024 1024 4096 août  13 23:01 gross
drwxr-xr-x  3 1024 1024 4096 sept. 11 18:44 postfix
drwx------  2 1024 1024 4096 avril 25 00:07 postgrey
drwxr-x---  2 1024 1024 4096 sept. 11 19:01 rspamd
drwxr-xr-x  2 1024 1024 4096 sept. 11 18:59 sieve
drwxr-xr-x  4 1024 1024 4096 août  13  2016 ssl
drwxr-xr-x  7 1024 1024 4096 août  13  2016 vhosts
drwxr-xr-x  3 1024 1024 4096 sept. 11 18:44 zeyple
```

Wrong system user ?

**Comment by hardware** [comment]
`/var/mail/zeyple` is the homedir of zeyple user, so you have a wrong UID/GID on this folder (1024 = vmail user).

https://github.com/hardware/mailserver/blob/7a0df58a8861e032fef39c03feee89efd5fbfa8f/rootfs/usr/local/bin/encryption.sh#L14-L18

https://github.com/hardware/mailserver/blob/16bcd42284876a0292c7b6d328d6983fef8545f2/rootfs/usr/local/bin/run.sh#L434

Same for clamav, dovecot, rspamd, you have a wrong UID/GID on this folders too.

**Comment by hardware** [comment]
Only the `1.0-legacy` version of this docker image chown the entire /var/mail folder and subfolders to vmail user because clamav, rspamd, postfix/spool and zeyple directories didn't exist a few months ago, so i think you have used this older version on your docker volume after migrated to 1.1.

https://github.com/hardware/mailserver/blob/6ac2ba89f0bbcf9dd1d6109a1204893df0b67e0f/rootfs/usr/local/bin/startup#L321

Or have you applied these permissions manually ?

**Comment by AnthoDingo** [comment]
All my apologies, error on my part with an old script
Issue can be close.
