### ISSUE TITLE
Rspamd learning retention

### ISSUE THREAD

**Issue by stevenmunro** [hardware/mailserver#165]
I'm wondering where the spam/ham statistics are actually kept. I just need assurance that a reboot of the mailserver is not going to make it a baby again. 

Also, is there a way to import these statistics from https://rspamd.com/rspamd_statistics/ ?

**Comment by denji** [comment]
https://github.com/vstakhov/rspamd/blob/1.6.4/conf/statistic.conf

**Comment by stevenmunro** [comment]
> https://github.com/vstakhov/rspamd/blob/1.6.4/conf/statistic.conf

Sorry, I have no idea what I'm supposed to do with this.

**Comment by hardware** [comment]
> I'm wondering where the spam/ham statistics are actually kept.

In your redis database : 

https://github.com/hardware/mailserver/blob/31f40aa6cba17384d9a2d72f14c2b756fe589b7f/rootfs/etc/rspamd/local.d/statistic.conf#L1-L12

So you can't add https://rspamd.com/rspamd_statistics/ files in your DBDIR (/var/mail/rspamd).

**Comment by hardware** [comment]
So you can't add https://rspamd.com/rspamd_statistics/ files in your DBDIR (/var/mail/rspamd) when redis is enabled in statistic settings. You must use the default statistics configuration using sqlite3 as backend.

You can specify an empty `statistic.conf` file like this : 

```yml
mailserver:
  volumes:
    - /path/to/empty/statistic.conf:/etc/rspamd/local.d/statistic.conf:ro
```

to use the default configuration file and then you'll be able to download and load rspamd pre-built files in your DBDIR :

```
cd /mnt/docker/mail/rspamd
wget https://rspamd.com/rspamd_statistics/bayes.ham.sqlite
wget https://rspamd.com/rspamd_statistics/bayes.spam.sqlite 
```

**Comment by hardware** [comment]
Does that answer your question ?

**Comment by denji** [comment]
https://github.com/hardware/mailserver/issues/216#issuecomment-367534035
