### ISSUE TITLE
status=bounced (SMTPUTF8 is required, but was not offered by host mail.* [private/dovecot-lmtp])

### ISSUE THREAD

**Issue by slima** [hardware/mailserver#166]
Hello, I have in postix logs:

status=bounced (SMTPUTF8 is required, but was not offered by host mail.* [private/dovecot-lmtp])

Where mail.* is my mailserver.

In mail.cf i have:

smtputf8_enable             = yes
smtputf8_autodetect_classes = all

any clue?

**Comment by slima** [comment]
Okey, so the problem occurs when reciving mail via php script with utf8 in headers.

And, when I change:
 
smtputf8_autodetect_classes = all
to
smtputf8_autodetect_classes = sendmail, verify

messages are accepted.

**Comment by hardware** [comment]
Ok, I think the default value of `smtputf8_autodetect_classes ` directive is better for compatibility according to the documentation of postfix :

http://www.postfix.org/SMTPUTF8_README.html#detecting
http://www.postfix.org/postconf.5.html#smtputf8_autodetect_classes

I fix this asap.
