### ISSUE TITLE
sieve filter not working

### ISSUE THREAD

**Issue by cracker0dks** [hardware/mailserver#167]
Hey,
I changed the default.sieve and restarted my mail docker container but it has no effect. I tested my script here: https://www.fastmail.com/cgi-bin/sievetest.pl and even recompiled it inside the container with no error but also no effect. 

I also checked that it is running with telnet...

My script is a simple redirect:

```
require ["body"];
if body :contains "something" {
        redirect "someone@gmail.com";
    }
```

anyone knows why ? is this my fault?

**Comment by hardware** [comment]
Can you try to write your sieve rule with rainloop helper or with https://addons.mozilla.org/fr/thunderbird/addon/sieve/

Both work on my end.

**Comment by cracker0dks** [comment]
thanks for your response. I saw that I had a 4 weeks old version so I updated and its working fine now. Thanks a lot :)
