### ISSUE TITLE
Fail2ban iptables based firewalling does not work

### ISSUE THREAD

**Issue by ksylvan** [hardware/mailserver#168]
I use ufw but this same problem happens with firewalld.

Based on looking at the nginx access log, I automatically identified and banned IP adddresses from accessing my server. However, bacause the Docker NAT rules giving access to containers and ports precede the other iptables deny rules, the attempt to bar those IP addresses is ineffective. 

Details here: https://github.com/moby/moby/issues/4737

**Comment by hardware** [comment]
With ossec and iptables + docker NAT, I use the following rules to limit traffic on ports 80 and 443 :

```
/sbin/iptables -N http-flood
/sbin/iptables -I FORWARD -p tcp --syn --dport 80 -m connlimit --connlimit-above 1 -j http-flood
/sbin/iptables -I FORWARD -p tcp --syn --dport 443 -m connlimit --connlimit-above 1 -j http-flood
/sbin/iptables -A http-flood -m limit --limit 10/s --limit-burst 10 -j RETURN
/sbin/iptables -A http-flood -m limit --limit 1/s --limit-burst 10 -j LOG --log-prefix "HTTP-FLOOD "
/sbin/iptables -A http-flood -j DROP
```

And this works well. It is necessary to add your rules **before** (iptables -I) docker rules and all in **FORWARD** chain.

But your issue isn't related to hardware/mailserver, maybe you'll find help on Docker Community Forums.

**Comment by ksylvan** [comment]
Thanks. What I want is to have `fail2ban` and `ufw` manage the ban list. It certainly was surprising to me to have `ufw` say that a certain IP was banned and to see their `access.log` entries later.

**Comment by ksylvan** [comment]
Transferring this to me on my repo, since I'd like to have the Ansible setup be a run-and-play solution that sets everything up correctly.

**Comment by ksylvan** [comment]
FYI: I added new configuration files set up by the Ansible playbooks so that the `fail2ban` jails that monitor docker services now use a new  `/usr/local/bin/ufw-docker-hack` shell script which inserts/deletes banned IP addresses into the `DOCKER-USER` table in addition to the ufw rules.

This is a hack, but works well in keeping the ability to see what is happening with banned IPs by running `ufw status`.
