### ISSUE TITLE
Urgent : échec des requêtes DNS

### ISSUE THREAD

**Issue by Wonderfall** [hardware/mailserver#169]
J'ai migré mailserver sur un autre serveur, a priori configuré de la même façon, sauf que toutes les requêtes à l'intérieur ont l'air d'échouer. Un `dig rspamd.com` par exemple échoue, et j'ai des logs du style : 

```
2017-09-16T22:00:33.194476+00:00 drogon postfix/smtpd[844]: connect from mail-182-80.mailgun.info[23.253.182.80]
2017-09-16T22:00:33.712958+00:00 drogon postfix/smtpd[844]: Anonymous TLS connection established from mail-182-80.mailgun.info[23.253.182.80]: TLSv1.2 with cipher ECDHE-ECDSA-AES256-GCM-SHA384 (256/256 bits)
2017-09-16T22:00:34.006193+00:00 drogon postfix/smtpd[844]: warning: notify.docker.com.dbl.spamhaus.org: RBL lookup error: Host or domain name not found. Name service error for name=notify.docker.com.dbl.spamhaus.org type=A: Host not found, try again
2017-09-16T22:00:34.013566+00:00 drogon postfix/smtpd[844]: warning: 80.182.253.23.zen.spamhaus.org: RBL lookup error: Host or domain name not found. Name service error for name=80.182.253.23.zen.spamhaus.org type=A: Host not found, try again
```

Donc au final je ne reçois même plus mes mails ! Plus étrange encore, si je change le resolv.conf pour mettre par exemple un autre serveur DNS qui fonctionne, ça marche puis... ça ne marche pas, et je ne délire pas, vraiment : après avoir fait cette modification, j'ai pu m'envoyer un mail depuis Protonmail, mais j'ai toujours ces erreurs dans les logs et je ne reçois toujours pas les mails.

Si tu as une idée, je suis preneur, je me casse la tête sur ça depuis des heures et j'ai pas vraiment le temps...

EDIT : Après encore plusieurs essais pour remplacer totalement Unbound y compris dans Postfix, ça a l'air de marcher quand je fais `dig` mais j'ai toujours des timeouts dans les logs et certains mails passent, mais ni SPF ni DKIM n'ont pu être vérifiés, et les erreurs RBL sont toujours là... Bref l'enfer.

**Comment by hardware** [comment]
Redémarre le conteneur et donne moi le résultat de ces commandes après quelques minutes :

```bash
docker exec -ti mailserver unbound-control status
docker exec -ti mailserver unbound-control stats_noreset
ls -la /etc/unbound/root.hints
ls -la /etc/unbound/root.key
dig rspamd.com @127.0.0.1
dig rspamd.com @127.0.0.11 # <- si tu utilises la v2 du docker-compose
dig mondedie.fr @127.0.0.1 +nocmd +noall +dnssec +comments
```

As-tu un parfeu qui pourrait bloquer sur le port 53 en tcp/udp ?

> Plus étrange encore, si je change le resolv.conf pour mettre par exemple un autre serveur DNS qui fonctionne, ça marche puis... ça ne marche pas

Le contenu du fichier `resolv.conf` est modifié pendant le démarrage du conteneur, ça peut expliquer pourquoi ça marche au début et pas après. Et si tu veux faire le test, il faut modifier les 2 fichiers `resolv.conf`, celui natif au système et celui qui est dans le chroot de postfix `/var/mail/postfix/spool/etc/resolv.conf`.

Si ça fonctionne, ça veut dire que le problème vient d'Unbound. Peut-être que les serveurs racines bloque toutes tes demandes de résolutions pour une raison qu'il faudrait déterminer. Ce que tu peux faire c'est essayer de forwarder les requêtes vers dns.watch par exemple :

```yml
# /etc/unbound/unbound.conf
forward-zone:
  name: "."
  forward-addr: 84.200.69.80      
  forward-addr: 84.200.70.40
```

**Comment by Wonderfall** [comment]
J'ai un pare-feu, mais même en le désactivant ça ne change rien.
Pour l'astuce de changer les DNS, c'est ce que j'ai fait en modifiant le fichier de Postfix directement puis en redémarrant, mais comme je l'avais dit, j'ai toujours des erreurs RBL...

Voici pour les commandes : 

``` 
$docker exec -ti mailserver unbound-control status
version: 1.6.0
verbosity: 0
threads: 1
modules: 2 [ validator iterator ]
uptime: 699 seconds
options: control(ssl)
unbound (pid 447) is running...
```

```
docker exec -ti mailserver unbound-control stats_noreset
thread0.num.queries=422
thread0.num.cachehits=0
thread0.num.cachemiss=422
thread0.num.prefetch=0
thread0.num.zero_ttl=0
thread0.num.recursivereplies=267
thread0.requestlist.avg=17.3436
thread0.requestlist.max=29
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=29
thread0.requestlist.current.user=28
thread0.recursion.time.avg=55.206689
thread0.recursion.time.median=51.7183
thread0.tcpusage=0
total.num.queries=422
total.num.cachehits=0
total.num.cachemiss=422
total.num.prefetch=0
total.num.zero_ttl=0
total.num.recursivereplies=267
total.requestlist.avg=17.3436
total.requestlist.max=29
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=29
total.requestlist.current.user=28
total.recursion.time.avg=55.206689
total.recursion.time.median=51.7183
total.tcpusage=0
time.now=1505657725.582398
time.up=723.478204
time.elapsed=723.478204
```

```
$ docker exec -ti mailserver ls -la /etc/unbound/root.hints
-rw-r--r-- 1 unbound unbound 3316 Sep 17 14:02 /etc/unbound/root.hints
```

```
$ docker exec -ti mailserver ls -la /etc/unbound/root.key
-rw-r--r-- 1 unbound unbound 166 Sep 17 14:02 /etc/unbound/root.key
```

```
$ docker exec -ti mailserver dig rspamd.com @127.0.0.1

; <<>> DiG 9.10.3-P4-Debian <<>> rspamd.com @127.0.0.1
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
$ dig mondedie.fr @127.0.0.1 +nocmd +noall +dnssec +comments

; <<>> DiG 9.10.3-P4-Debian <<>> mondedie.fr @127.0.0.1 +nocmd +noall +dnssec +comments
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by Wonderfall** [comment]
J'ai une sorte de problème similaire à https://github.com/hardware/mailserver/issues/1
Sauf qu'aucune des commandes n'a fonctionné chez moi (en remplaçant eth0 par enp4s0).

**Comment by hardware** [comment]
Il y a un truc bizarre dans tes stats :

```
thread0.num.queries=422
thread0.num.cachehits=0
thread0.num.cachemiss=422
thread0.num.recursivereplies=267
```

Il y a eu 422 requêtes DNS depuis le démarrage, il y a eu 422 demandes récursives (résultat pas dans le cache), 0 requêtes via le cache et 267 réponses aux demandes de récursion ce qui n'est pas normal, là tu as 60% de réponse.

Sur mon serveur après un redémarrage j'ai :

```
thread0.num.queries=633
thread0.num.cachehits=333
thread0.num.cachemiss=300
thread0.num.recursivereplies=300
```

**Comment by Wonderfall** [comment]
Je pense que tu avais raison, ça devait venir de l'hébergeur (Hetzner).
J'ai changé de place une nouvelle fois le serveur mail (Scaleway, il en fera du chemin...) et ça fonctionne (par contre Scaleway bloque par défaut SMTP, c'est lourd).
