### ISSUE TITLE
mailserver-quicksetup script

### ISSUE THREAD

**Issue by rubentrancoso** [hardware/mailserver#170]
Maybe you guys should be interested in a script to automate the installation steps.
The one I did can be viewed [here](https://github.com/rubentrancoso/mailserver-quicksetup) and in the case you want to have it integrated to this repository let me know.

cheers
and thanks for the great job

I finally have my 'mailtoaster'!

**Comment by ksylvan** [comment]
Did you see my Ansible playbooks here? https://github.com/ksylvan/docker-mail-server

It automates the setup of everything (including your letsencrypt SSL certificates).

I can go from creating a server (I use vultr, not Digital Ocean, but where the server resides is not important) to running the Ansible playbooks to install the stack, and getting the postfixadmin setup done in about 30 minutes.

**Comment by hardware** [comment]
> I finally have my 'mailtoaster' !

This is great :)

I could add your project to the readme when it will be a little more mature.

You have a typo error here : https://github.com/rubentrancoso/mailserver-quicksetup/blob/master/remote_install.sh#L121 `plublic.key -> public.key`

Thanks for your contribution.

**Comment by rubentrancoso** [comment]
@ksylvan thanks by the heads up...
Ansible still is barrier for me, but I will take a look on it and eventually learn it at all. Note that my intention here was to suppress as much as possible any manual intervention for easiness and disaster recovery for example. So at the end I hope to cover every single step.

@hardware I will be working on it. 
I'm more a developer than a sysadmin with super bash skills.
I did it just as a tool to make my life easy, so I can be missing something regarding your vision on the project obviously.  Any sugestion is welcome!  
For now it can be useful for someone with similar tastes as mine :)

**Comment by denji** [comment]
@ksylvan terraform better for me.

**Comment by ksylvan** [comment]
@rubentrancoso Awesome.

Yeah, the ansible route works for all that too and makes it easy for me to apply fixes/enhancements to the mail server setup on multiple servers.

**Comment by hardware** [comment]
I added a community section in the readme : https://github.com/hardware/mailserver#community-projects :+1:
