### ISSUE TITLE
DNS lookup issues for clamAV and rspamd

### ISSUE THREAD

**Issue by stevenmunro** [hardware/mailserver#174]
unbound appears to be working correctly, but rspamd and clamav can't resolve anything.

However when I use unbound to lookup the address from within the docker mailserver container, it returns a response. 

help please! I can't figure this one out.

**Comment by stevenmunro** [comment]
from the mailserver logs

`upstreams; rspamd_resolve_addrs: address resolution for rspamd.com failed: Temporary failure in name resolution`

`freshclam[471]: Can't query current.cvd.clamav.net`
`freshclam[471]: Invalid DNS reply. Falling back to HTTP mode.`

`rspamd[583]: <qwxppg>; map; rspamd_map_dns_callback: cannot resolve rspamd.com`

**Comment by hardware** [comment]
Please, give me the result of these commands :

```
s6-svstat /services/unbound
docker exec -ti mailserver unbound-control status
docker exec -ti mailserver unbound-control stats_noreset
ls -la /etc/unbound/root.hints
ls -la /etc/unbound/root.key
dig rspamd.com @127.0.0.1
dig rspamd.com @127.0.0.11
dig mondedie.fr @127.0.0.1 +nocmd +noall +dnssec +comments
```

Try to remove all docker iptables rules with :

```
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X
```

And restart docker service.

**Comment by stevenmunro** [comment]
Look I'll be brutally honest, I'm using Rancher to launch this configuration. I was hoping to be able to contribute to this project by suggesting (in future) that this project works on Rancher. 

I've had great success so far, everything appears to work (I've had to manually create the components (I couldn't use your docker-compose). There are sidekick components etc..

However then there is this issue with DNS lookups within postfix. 

Further study, this issue appears to resolve itself after a little while. When I immediately start the mailserver container, I can do a 'nslookup' on external hosts no problem (this is while Postfix is still loading up) .. and then all of a sudden as soon as it's all loaded (I presume when outbound has been brough into the mix) nothing from nslookup will resolve. Give it 15-20 minutes, it'll come right. 

I appreciate the time and effort you put into this project. I have run mail servers before but never have I run one as a series of docker containers. 

I am sorry that I am using Rancher. But my intentions were as I mentioned before, was to have this running perfectly and then contribute to the project and provide a HOWTO..

If we could troubleshoot this particular issue, that would great.

**Comment by stevenmunro** [comment]
Having said that. I will respond in due course with the output of the commands you've provided.

**Comment by hardware** [comment]
Maybe your server provider temporarily limit your DNS recursive requests to the root servers (like #169) with a firewall or something like that. `unbound-control stats_noreset` should give some hints on your problem.

**Comment by hardware** [comment]
I will add an environment variable to disable unbound for non-compatible environments, 
maybe it will solve your problem.

**Comment by stevenmunro** [comment]
Could we upgrade unbound to the latest version too? :)

**Comment by hardware** [comment]
I tried to compile the last version but i have some problems with libexpat and unbound-anchor command. But I don't think it will solve your problem anyway.

**Comment by hardware** [comment]
Can you try the new environment variable `DISABLE_DNS_RESOLVER` ?

**Comment by stevenmunro** [comment]
> DISABLE_DNS_RESOLVER

`30/09/2017 08:41:17[INFO] Unbound DNS resolver is disabled`

Looks good so far, however I'm seeing these in the log output.

`30/09/2017 08:43:282017-09-29T19:43:28.531280+00:00 mail rspamd[601]: <8bdba4>; lua; asn.lua:63: error querying dns: server fail`

**Comment by hardware** [comment]
Can you try this :

```
docker exec mailserver dig rspamd.com
docker exec mailserver dig rspamd.com @127.0.0.1
docker exec mailserver dig rspamd.com @127.0.0.11
```

Do you have DNS issues at the host level ? What is your hosting provider ? What are your nameservers (/etc/resolv.conf) ?

**Comment by stevenmunro** [comment]
> docker exec mailserver dig rspamd.com

`; <<>> DiG 9.10.3-P4-Debian <<>> rspamd.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41374
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rspamd.com.			IN	A

;; ANSWER SECTION:
rspamd.com.		5	IN	A	88.99.142.95

;; Query time: 1 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Fri Sep 29 20:16:40 UTC 2017
;; MSG SIZE  rcvd: 55`

> docker exec mailserver dig rspamd.com @127.0.0.1

`;; connection timed out; no servers could be reached`

> docker exec mailserver dig rspamd.com @127.0.0.11

`;; connection timed out; no servers could be reached`

**Comment by stevenmunro** [comment]
I have no issues with DNS on host server. Hosted on AWS EC2.
On the mailserver container, cat /etc/resolv.conf reveals 

`search  a-mailserver.rancher.internal mailserver.a-mailserver.rancher.internal rancher.internal ap-southeast-2.compute.internal
nameserver 169.254.169.250`

**Comment by hardware** [comment]
The outputs of the last two commands are normal, rancher seems to use its own dns resolver `169.254.169.250:53`.

Give me the number of CPU cores of your server and the number of rspamd workers, please.

```
docker exec mailserver nproc
docker exec mailserver ps aux | grep rspamd
```

Can you monitor your DNS queries with tcpdump ?

```bash
# docker exec -ti mailserver bash
apt-get update && apt-get install tcpdump
tcpdump -n port 53
```

Did you see a normal amount of DNS requests ? If you see a lot of repeated DNS queries, try to disable RBL module with :

```yml
# /tmp/rbl.conf
enabled = false;
```

And mount the file :

```yml
volumes:
  - /tmp/rbl.conf:/etc/rspamd/local.d/rbl.conf:ro
```

**Comment by stevenmunro** [comment]
If I do 
> volumes:
  - /etc/resolv.conf:/etc/resolv.conf:ro

I get this
`30/09/2017 14:23:11[ERROR] Container IP not found with embedded DNS server... Abort !`

Also, tried to mount options.inc locally so I could make changes to the name servers;
`/tmp/options.inc:/etc/rspamd/local.d/options.inc:ro`

and I get this
`30/09/2017 15:32:52sed: cannot rename /etc/rspamd/local.d/sedwznvst: Device or resource busy`

small variation on restart

`30/09/2017 15:35:53sed: cannot rename /etc/rspamd/local.d/sedVjwudP: Device or resource busy`

I mounted rbl.conf with no issues

`/tmp/rbl.conf:/etc/rspamd/local.d/rbl.conf:ro`

I'm not sure what is going on here. How can I make some of these things in rspamd persistent.

**Comment by hardware** [comment]
Override `options.inc` file is not needed anymore since the last commit using `DISABLE_DNS_RESOLVER`.  

Can you give me the number of CPU cores of your server and the number of rspamd workers ?

```
docker exec mailserver nproc
docker exec mailserver ps aux --forest | grep [r]spamd
```

> I mounted rbl.conf with no issues

Did you see an abnormal amount of dns queries with tcpdump ?

**Comment by hardware** [comment]
Any news ?
