### ISSUE TITLE
Today my mailserver container crash, and not auto restart

### ISSUE THREAD

**Issue by slima** [hardware/mailserver#176]
Hello, Today my mailserver container crashed.

In kern.log I have:

 br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
 veth6709071: renamed from eth0
 br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
 device veth8619bd3 left promiscuous mode
 br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
 auplink[13906]: segfault at 7ffc87958978 ip 00007fbfb113d579 sp 00007ffc87958980 error 6 in libc-2.23.so[7fbfb1044000+1c0000]

In syslog:

docker[452]: time="2017-09-29T11:58:09.026914250+02:00" level=warning msg="container kill failed because of 'container not found' or 'no such process': Cannot kill container c7e7f04352f5416adf82a86388c1076835c45fffb9c282524d67fda679e67914: rpc error: code = 2 desc = no such process"
docker[452]: time="2017-09-29T11:58:09.177309544+02:00" level=warning msg="container kill failed because of 'container not found' or 'no such process': Cannot kill container c7e7f04352f5416adf82a86388c1076835c45fffb9c282524d67fda679e67914: rpc error: code = 2 desc = no such process"
docker[452]: time="2017-09-29T11:58:09.309460242+02:00" level=warning msg="container kill failed because of 'container not found' or 'no such process': Cannot kill container c7e7f04352f5416adf82a86388c1076835c45fffb9c282524d67fda679e67914: rpc error: code = 2 desc = no such process"
kernel: [2413417.344918] br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
kernel: [2413417.345054] veth6709071: renamed from eth0
kernel: [2413417.635234] br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
kernel: [2413417.635567] device veth8619bd3 left promiscuous mode
kernel: [2413417.635571] br-1d6c0c9dca4a: port 6(veth8619bd3) entered disabled state
kernel: [2413417.919673] auplink[13906]: segfault at 7ffc87958978 ip 00007fbfb113d579 sp 00007ffc87958980 error 6 in libc-2.23.so[7fbfb1044000+1c0000]
docker[452]: time="2017-09-29T11:58:14.356414282+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/aea07b2e648d88b8f0a07e2982549bfc71dc2c1d528bbadb620c5f1bdec11c92: signal: segmentation fault (core dumped)"
ntpd[878]: Deleting interface #120 veth8619bd3, fe80::78d6:72ff:fe9f:2079%183#123, interface stats: received=0, sent=0, dropped=0, active_time=871911 secs

In docker-compose I have: restart: unless-stopped

Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-93-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: poczta-panta
ID: TKKJ:FVZA:IKNL:NSXX:HIFP:WU22:6R32:WOAL:6BEP:BJYE:LY6R:TRHG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Do you have any advice?

**Comment by hardware** [comment]
if this is the first time you encounter this kind of problem, you can ignore this. On my server, my container crashed only once in 2 years. I advise you to use overlay2 or btrfs storage driver instead of aufs.

**Comment by slima** [comment]
I switched to overlay2

But I'm worred, because container not restart automaticly.

**Comment by hardware** [comment]
Sadly, the container didn't restart after a segmentation fault of the storage driver.

**Comment by slima** [comment]
Thanks for health check hint.

I can't provide you any details of container state, because I`m on hollyday today, and secound administrator took the actions.

He said:
docker ps doesn't list mailserver container
docker ps -a list, with 'exited 4h ago'

So I advice him to to 'docker start mailserver'

'docker events' was empty.
