### ISSUE TITLE
Cannot customize /var/mail/sieve/default.sieve 

### ISSUE THREAD

**Issue by j-schumann** [hardware/mailserver#177]
When adjusting <code>/var/mail/sieve/default.sieve</code> it is overwritten by <code>/rootfs/usr/local/bin/run.sh</code> each time it runs.
Because the default.sieve is stored in the docker volume I thought it's meant to be persisted between runs/container creations?
Is there another way to customize the sieve rules? Or could the run.sh be adjusted to not overwrite an existing default.sieve?

**Comment by hardware** [comment]
I added a way to customize this file with the last commit : 940aabf. 

Add your custom rules in `/var/mail/sieve/custom.sieve`. Do not forget, all the rules in this file are applied to **all user accounts**.

**Comment by j-schumann** [comment]
Thanks, updated the container and will see if it works 👍
