### ISSUE TITLE
How to regenerate DKIM keys

### ISSUE THREAD

**Issue by stevehu** [hardware/mailserver#180]
I got error from https://www.mail-tester.com that indicates "Your DKIM signature is not valid". I have added a TXT record in cloudflare and get the key from mydomain.net instead of domain.tld in /mnt/docker/mail/dkim folder. I guess we need to use the key in domain.tld folder but that key contains "\t" and cannot be used by cloudflare. 

Here is the content of public.key in domain.tld and you can see there are two \t there. 

```
mail._domainkey IN TXT ( "v=DKIM1; k=rsa; "
	"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDih4oU/tVDLIjUJAcATIIbJYv5wN31
XoVnTcbYSGT5z58JzyHFoB67Mjwdwzil03QdmXvY0Tp7jGbX3FkX2FWobw0XCVvxR3Tlz4XWYvXDIVO
zemjzRdt9vilO29NFYuml5HBvEU6E46sCPS0imgAYvBvFDy9tishYccIe3eD2+wIDAQAB" ) ;
```
I am wondering if there is a way to regenerate the keys. Thanks.

**Comment by denji** [comment]
[`rspamadm dkim_keygen`](https://rspamd.com/doc/modules/dkim.html#dkim-keys-management) / [`opendkim-genkey`](http://www.opendkim.org/opendkim-genkey.8.html).

**Comment by hardware** [comment]
Remove your old key in domain.tld folder and restart the container.

**Comment by stevehu** [comment]
Removing the old key and restarting the containers won't work as nothing is generated. The following command work inside the container. 
```
rspamadm dkim_keygen -s mail -d domain.tld -k private.key
```

Thanks for your help.
