### ISSUE TITLE
Why is 'soft reject' defined in rspamd metric actions?

### ISSUE THREAD

**Issue by fatalbanana** [hardware/mailserver#183]
Hi,

Why is 'soft reject' in rspamd metric actions?
https://github.com/hardware/mailserver/blob/master/rootfs/etc/rspamd/local.d/metrics.conf#L3

In this configuration, messages with score between 15 and 20 are permanently deferred which seems unlikely desirable behaviour.

**Comment by hardware** [comment]
I thought I could use it after reading the documentation : https://rspamd.com/doc/configuration/metrics.html 

I will correct that, thanks. It could explain #179 issue  ?

**Comment by fatalbanana** [comment]
This part of WebUI only works properly if actions are "greylist"/"add header"/"reject" - that may be the issue.
