### ISSUE TITLE
RELAY_NETWORKS not working as I expect

### ISSUE THREAD

**Issue by ksylvan** [hardware/mailserver#187]
I have the following in docker-compose for the mailserver image:

```
- RELAY_NETWORKS=172.16.0.0/16
```

But I see this, when a container at 172.18.0.5 tries to send mail vis SMTP:

```
mailserver      | 2017-11-07T17:34:22.084636+00:00 mail postfix/smtpd[601]: NOQUEUE: reject:
RCPT from unknown[172.18.0.5]: 553 5.7.1 <sitemail@xxxx.com>:
Sender address rejected: not logged in; from=<sitemail@xxxx.com> to=<somebody@gmail.com> proto=SMTP helo=<mail.xxxx.com>
```

What do I need to do to fix this?

**Comment by hardware** [comment]
Add `permit_mynetworks` **before** `reject_sender_login_mismatch` :

```ini
# /mnt/docker/mail/postfix/custom.conf

smtpd_sender_restrictions=reject_non_fqdn_sender,reject_unknown_sender_domain,permit_mynetworks,reject_sender_login_mismatch,reject_rhsbl_sender dbl.spamhaus.org
```

**Comment by ksylvan** [comment]
Thank you!

**Comment by atomtigerzoo** [comment]
Why is `permit_mynetworks` not added to the default config of postfix so that relaying works out of the box when adding ips/ranges to RELAY_NETWORKS?

**Comment by hardware** [comment]
Because `permit_mynetworks`, in this case, disable the spoofing protection (allowing to use forged sender addresses), this is not a default acceptable behavior.

**Comment by atomtigerzoo** [comment]
Sorry, to ask again, but somehow it doesn't seem to work here :/

Trying to send emails with the login of user `hello@example-two.com` from the mailbox of another user fails with:

    5.7.1 <hello@example-one.com>: Sender address rejected: not owned by user hello@example-two.com

Custom sender restrictions are loaded by postfix:

    $ docker-compose exec mailserver postconf -n | grep restr
    smtpd_sender_restrictions = reject_non_fqdn_sender,reject_unknown_sender_domain,permit_mynetworks,reject_sender_login_mismatch,reject_rhsbl_sender dbl.spamhaus.org

How can I send over one default outgoing smtp account with all accounts on the server?

**Comment by alrayyes** [comment]
Just encountered the same issue myself. Maybe a good idea to update documentation? Now the impression is given that relaying works out of the box when RELAY_NETWORKS is enabled.
