### ISSUE TITLE
might also consider integrating NSD web interface 

### ISSUE THREAD

**Issue by outbackdingo** [hardware/mailserver#189]
involves adding nginx/php/mysql for a working NSD web interface

http://www.lissyara.su/articles/freebsd/programms/nsdadmin/

**Comment by hardware** [comment]
It seems this project is no longer being maintained.

**Comment by outbackdingo** [comment]
no longer maintained and working or not working are quite different
there is also https://github.com/obi12341/docker-pdns  powerdns and poweradmin
which are actively maintained and working.

**Comment by hardware** [comment]
If you want to use powerdns, you are free to use it. I give nsd as an example. For my personal usage i don't need an UI to manage my DNS settings.

**Comment by ksylvan** [comment]
@outbackdingo did integrate powerdns into the stack in my Ansible playbooks and scripts.
