### ISSUE TITLE
Add greylisting support

### ISSUE THREAD

**Issue by tidge789** [hardware/mailserver#19]
Do you have any intention to add greylisting to this mail stack? I am currently migrating a production mailserver to a docker-based one using this image and right now the only difference between both servers is the one that is currently used uses greylisting in conjunction with spamassassin for filtering spams.

I don't know, in 2016, if greylisting is still efficient and recommended. What are your thoughts on this?

Thanks.

**Comment by hardware** [comment]
Why not, works great against spammers/bots but requires decent pre-greylisting whitelists (with dnswl.org for example) to prevent false positive delays. 

The smtp protocol doesn't have a standard way for greylisting servers to tell sending servers when to try again. There's no guarantee that a message will get to you in a reasonable amount of time. I'm always afraid that my password reset emails delayed until after they time out and sometimes, 
some forums/websites they simply aren't resent at all...

I think it might be a good idea for mid/high mailservers but not really helpful for personal/small sized servers. 

I can add an external policy server to Postfix (like postgrey), disabled by default but can be activated with an environment variable like **ENABLE_POSTGREY**.

**Comment by tidge789** [comment]
Alright, sounds good to me.

I guess my server falls in the range of small sized servers so it may not be necessary for me to use greylisting. I never managed a mailserver without greylisting so I was kind of afraid of migrating to a new system and having my users begin receiving spams while they didn't before. I guess i'll try it without greylisting and by the time I make up my mind I could just enable it easily with an environment variable.

Thanks for considering it. So far I'm very pleased with how easy it is to setup a functioning mailserver using you image.

**Comment by hardware** [comment]
@tidge789 It's done, you can activate Postgrey policy server with **ENABLE_POSTGREY** env variable.

 I will merge `dev` to `master` this week-end ;)
