### ISSUE TITLE
old emails import ?

### ISSUE THREAD

**Issue by zerpex** [hardware/mailserver#191]
Hi,

I installed your mailserver in replacement of another postfix container that did not use databases at all and I wonder if there is a way to inject all previews mails (flat eml files) into the database. And if it' possible, how ? :)

Note : preview container is stopped, so I have to work with email files directly.

z.

**Comment by slima** [comment]
Hello, emails aren't stored in database.

Emails are in Maildir, in (by default) /mnt/docker/mail/vhosts/tld/username/mail

**Comment by hardware** [comment]
As slima says, emails are not stored in database. What mailbox format do you use ? what docker image do you use before ?

https://wiki.dovecot.org/MailboxFormat
https://wiki.dovecot.org/Migration/MailFormat

hardware/mailserver use [Maildir format](https://wiki.dovecot.org/MailboxFormat/Maildir) with this location : `/var/mail/vhosts/%d/%n/{{ VMAIL_SUBDIR }}`

**Comment by denji** [comment]
fake-auth + imapsync

**Comment by zerpex** [comment]
Ok, found it, thanks a lot.
I was able to import all my mail !
