### ISSUE TITLE
Mail en double - Outlook

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#192]
Tout d'abord encore merci pour tout le travail fourni sur ce projet de serveur de mail !

Actuellement installé en version 1.1 dans ma société, un problème apparaît régulièrement mais surtout aléatoirement, avec le client mail Outlook 2013 ou 2016, certains utilisateurs reçoivent des mails en double voir triple ou quadruple. Ce problème se manifeste **aléatoirement** (généralement une fois sur deux) mais toujours avec les mêmes comptes mail, j'ai pourtant fait les dernières mises a jour sur le serveur..

Je lance des tests avec le client Thunderbird.
Mon fichier custom.conf :
message_size_limit=102400000
default_destination_rate_delay=0s
default_destination_recipient_limit=50
smtputf8_enable=no

Si vous avez une solution je suis preneur. :)

**Comment by hardware** [comment]
Est-ce qu'en passant par le webmail les mails apparaissent aussi en double ? Est-ce qu'il est possible de supprimer les messages en double ou est-ce qu'ils reparaissent systématiquement ? Est-ce que tu constates les mêmes problèmes avec un client mail différent (thunderbird) ? Quels sont les paramètres IMAP d'Outlook ? Est-ce qu'il y a des choses suspectes dans les logs du conteneur lorsque ça arrive ?

**Comment by tsedgwick1** [comment]
1. Les mails apparaissent en double sur le webmail également. 
2. Il est possible de supprimer les messages en double sans qu'ils réapparaissent.
3. Actuellement nous effectuons des tests depuis Outlook mais ça a l'air de fonctionner (pas de retour négatif pour le moment).
4. Paramètre IMAP sur outlook
Serveur entrant 993 SSL
Serveur sortant 587 TLS
Sur Thunderbird 
Serveur entrant 993 SSL
Serveur sortant 587 STARTTS

**Comment by hardware** [comment]
J'ai jamais eu un tel comportement de mon côté. Il faudrait isoler un compte en utilisant que le webmail ou thunderbird sur celui-ci pendant quelques jours et vérifier que le problème ne se reproduit pas.

**Comment by tsedgwick1** [comment]
C'est ce que je vais faire mais je sais pas s'il y aurait une option a modifier pour que le délai entre chaque mails envoyé sois légèrement plus long..

**Comment by hardware** [comment]
Il faut modifier `default_destination_rate_delay`. Mais je vois pas le rapport avec le problème de doublon, même si cette directive est par défaut sur 0 seconde.

**Comment by tsedgwick1** [comment]
Petit retour sur la situation, apparemment le fait de retirer cette option et redémarrer le container a résolu le problème. Je ne vois pas trop le rapport mais ça semble corrigé. Merci ! :)
