### ISSUE TITLE
does anyone have problems with rspamd webui?

### ISSUE THREAD

**Issue by AndrewSav** [hardware/mailserver#193]
I have a weird issues with rspamd web ui. When you logging into web ui and go to the history tab and then refresh a few time it freezes the whole linux box. The only thing I can do after that is reboot - I cannot even ssh to it. After reboot the rspamd web ui works fine, but if you return in a day, the same thing happens again. Total freeze of the box that has to be rebooted.

Did anyone experience anything similar?

**Comment by denji** [comment]
* https://github.com/vstakhov/rspamd/issues/new
* https://github.com/vstakhov/rspamd/tree/master/interface

**Comment by hardware** [comment]
I experienced the same issue with 1GB RAM virtual machine. With 1.5GB RAM the problem does not occur.  Do you have enough memory ?

**Comment by zerpex** [comment]
I missed something apparently... how do you reach rspamd webui ?

**Comment by hardware** [comment]
@zerpex with the 11334 port through your reverse proxy.

https://github.com/hardware/mailserver/wiki/Migrating-from-1.0-stable-to-1.1-stable#rspamd-webui--add-a-new-nginx-virtual-host

**Comment by AndrewSav** [comment]
@hardware I'm running on of these cheap hostings with 1GB of memory, so that explains it. Kind of.
I noticed that clam takes most of the memory, I wonder if I could switch it off. Is it possible, or your setup won't work without it?

**Comment by zerpex** [comment]
@hardware Thanks a lot, I missed that !

**Comment by ksylvan** [comment]
@AndrewSav adding more swap space might alleviate the issue, but it'll be much better to run this stack on a 2GB host.

**Comment by AndrewSav** [comment]
@ksylvan disabling clam should help since that's what uses the most of the memory. Hence I'd like to know if it's possible to disable it in this setup.

**Comment by hardware** [comment]
> Hence I'd like to know if it's possible to disable it in this setup.

Switch `DISABLE_CLAMAV` to `true`

**Minimum system requirements :**

| Tag | Without ClamAV | With ClamAV |
| ---- | -------------- | ----------- |
| 1.0-legacy | 512 MiB | 1 GiB |
| 1.1-stable | 1.5 GiB | 2 GiB |

If redis is on a separated server :

| Tag | Without ClamAV | With ClamAV |
| ---- | -------------- | ----------- |
| 1.1-stable | 512 MiB | 1 GiB |

**Comment by AndrewSav** [comment]
Thank you, all.

**Comment by AndrewSav** [comment]
@hardware I increased memory to 2GB _and_ disabled ClamAV, and I don't have freezes now. Yet, the History tab is still not working for me:

![image](https://user-images.githubusercontent.com/658865/36195435-5372cfa6-11d2-11e8-87c6-a7511901b5cc.png)

Any ideas?

**Comment by denji** [comment]
Redis-Server timeout?

**Comment by AndrewSav** [comment]
I might add there is a know issue here: https://github.com/vstakhov/rspamd/issues/1967 but apparently not many people trip on it, so I'd like to know what's different about my setup.

```
curl "https://domain.tld/history" -H "authority: domain.tld" -H "password: password"
```

Is more or less the query that times out in browser.  I'm getting 6MB json with exactly 2000 records with curl. In browser console it times out in exactly 20 seconds.

```
Measure-Command { cmd /c curlcmd /c curl "https://domain.tld/history" -H "authority: domain.tld" -H "password: password" }
```

show between 30 and 40 seconds per run.
