### ISSUE TITLE
NSD authoritative DNS server - automatic relationship with mailserver?

### ISSUE THREAD

**Issue by stevenmunro** [hardware/mailserver#194]
Sorry my understanding of how and where the NSD server sits in this mailserver configuration is limited.

I currently configure the SPF, DKIM and DMARC records on an external DNS service. Am I correct to assume that if NSD was set up, that these records would be automatically populated? (if it were to be configured as authoritative for the domain)

**Comment by hardware** [comment]
> Am I correct to assume that if NSD was set up, that these records would be automatically populated?

These records are not automatically populated, you have to set the dns zone as shown here :

https://github.com/hardware/mailserver/wiki/NSD-initial-configuration

**Comment by ozgurkazancci** [comment]
> > Am I correct to assume that if NSD was set up, that these records would be automatically populated?
> 
> These records are not automatically populated, you have to set the dns zone as shown here :
> 
> https://github.com/hardware/mailserver/wiki/NSD-initial-configuration

Sorry for the bump, got the same question (looking for a manual regarding SPF, DKIM and DMARC configuration for nsd) the link is broken though. Any other link you could provide please? Many thanks.
