### ISSUE TITLE
Changing postfixadmin conf?

### ISSUE THREAD

**Issue by HeyLittleMonkey** [hardware/mailserver#196]
I want to change the password guidelines, but when I mount
`
    volumes:
      - /mnt/docker/postfix/conf:/postfixadmin
`
to do so, the dir is empty after restarting and the webpage returns an error. Any ideas why this happens?

**Comment by hardware** [comment]
This is the default behavior of Docker. If you mount an empty directory, all the data in this directory inside the container will be overwritten with nothing.

> I want to change the password guidelines

Look  `PASSVAL_MIN_LEN`, `PASSVAL_MIN_CHAR` and `PASSVAL_MIN_DIGIT`.

https://github.com/hardware/postfixadmin#environment-variables

**Comment by HeyLittleMonkey** [comment]
Thanks for the explanation. I overlooked the PASSVAL_MIN_DIGIT variable, exactly what I wanted.
