### ISSUE TITLE
adding users from config? 

### ISSUE THREAD

**Issue by hanscees** [hardware/mailserver#197]
Hi,
what a wonderful image! But its rather complex to understand since it is quite an ecosystem of different parts.

Perhaps there is a faq I have missed, if so apologies.
My question is, can I add users in a configfile or something when setting this up? Or do you only add the domains and then later add users via the php postfix website included? 

Thanks!

**Comment by AndrewSav** [comment]
Users are stored in the MySql instance, there no config. If you need to script them to automate the process you can add them there. Look at postfix/postfixadmin documentation and examine the database structure yourself. I have not done it, but my gut feeling, that it is not very complicated.

**Comment by hardware** [comment]
> Or do you only add the domains and then later add users via the php postfix website included?

With postfixadmin webapp : 

https://github.com/hardware/postfixadmin
https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
