### ISSUE TITLE
Domaine supplémentaire - Connexion impossible

### ISSUE THREAD

**Issue by Rathorian** [hardware/mailserver#198]
Bonjour,

J'ai ajouté un domaine supplémentaire au serveur de mail avec la variable "ADD_DOMAINS".
Redémarré le serveur, ajouté la clé DKIM, etc... à ma zone DNS, ajouté le domaine dans postfixadmin et Rainloop, créé une adresse mail et tout rédemarré.

Impossible de me connecter à ma nouvelle adresse mail sur Rainloop. L'erreur est "L'Authentification a échouée".

Dans les logs de mailserver j'ai : 
`2017-11-26T10:05:11.880999+00:00 ns1 dovecot: imap-login: Login: user=<contact@domaine.fr>, method=PLAIN, rip=172.18.0.7, lip=172.18.0.13, mpid=589, TLS, session=<gxvk699eHqGsEgAH>
2017-11-26T10:05:11.890693+00:00 ns1 dovecot: imap(contact@domaine.fr): Error: User initialization failed: Namespace '': mkdir(/var/mail/vhosts/domaine.fr/contact/mail) failed: Permission denied (euid=1000(vmail) egid=1000(vmail) missing +w perm: /var/mail/vhosts/domaine.fr, dir owned by 0:0 mode=0755)
2017-11-26T10:05:11.890742+00:00 ns1 dovecot: imap: Error: Invalid user settings. Refer to server log for more information.`

Dans le dossier "/home/user/docker/mail/vhosts/domaine.fr" je n'ai pas le dossier de mon adresse mail comme dans mon premier domaine (celui par défaut), à priori il n'a pas été créer automatiquement....

Serais-tu comment régler ce petit problème ?
Merci

**Comment by hardware** [comment]
Ça veut dire que dovecot n'a pas les droits pour écrire dans le répertoire `/var/mail/vhosts/domaine.fr`. Pourtant que je corrige bien les droits si c'est nécessaire :

https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/run.sh#L502-L504

> mkdir(/var/mail/vhosts/domaine.fr/contact/mail) failed: Permission denied (euid=1000(vmail) egid=1000(vmail) missing +w perm: /var/mail/vhosts/domaine.fr, dir owned by 0:0 mode=0755

Actuellement le propriétaire de ton répertoire est l'utilisateur **root** (0:0 - 0755) alors que dovecot ne peut écrire que dans des répertoires de l'utilisateur **vmail**.

Vérifie bien les permissions.

**Comment by Rathorian** [comment]
C'est étonnant, car du coup il doit avoir un problème avec les "chmod" dans le script pour les ajouts de domaine supplémentaire.

Voici mon docker-compose pour mailserver : https://paste.mondedie.fr/?df026fb5e800e029#PKEvLOlF+wZHnCygsm1azk/6fRxNc1lQSMItMmUO3mU=

L'utilisateur "rathorian" a pour UID/GID : 1000

Voici le retour des dossiers du répertoires "mail" et "vhosts" : 
Dossier mail : https://paste.mondedie.fr/?18726589482880d2#O/sddvMagOrybYYlpVrQ/jrqXaARu42Y/UZzEgaXEh0=
Dossier vhosts : https://paste.mondedie.fr/?81d982b20d7eb14f#Z7+SSDd1qkGtECp1aHStVen3bVg/t/neC3RlTaflAKA=

Du coup même si je change les droits du domaine2 dans "mail/vhosts/domaine2.fr", je suis pas sur que le reste soit bon au niveau des droits....

**Comment by hardware** [comment]
En deux ans j'ai personne n'a eu de problème de droits au niveau des vhosts mail, je pense que sur ce coup tu as juste eu pas de chance, parce que c'est pas mon script qui créé ce répertoire, c'est dovecot qui le fait donc au pire supprime le puis reconnecte toi en IMAP.

Ou sinon redémarre le conteneur et le `chown -R vmail:vmail /var/mail/vhosts` fera son job.

**Comment by Rathorian** [comment]
J'ai essayé comme tu m'as dit mais ça n'a pas fonctionné.

Donc après avoir supprimé totalement le domaine supplémentaire sur Postfixadmin, Rainloop et sur le conteneur mailserver, j'ai refait une tentative avec exactement les même manipulations et ça a fonctionné.

J'ai du quand même refaire le "chown" sur le dossier du domaine supplémentaire dans "/var/mail/vhosts" car il me l'a recréé avec les droits root comme au début mais cette fois la connexion à fonctionné après ce changement.

Je voulais pas t'accuser concernant une erreur dans le script, je suis juste étonné que le domaine principal soit correctement configuré immédiatement mais que pour le domaine supplémentaire il ne le soit pas.

Merci

**Comment by hardware** [comment]
Ah mais tu arrives à reproduire ce bug systématiquement ? Et toujours avec le second domaine ?

Dans les tests unitaires je fais le test avec 3 domaines, donc si il y avait un problème, travis-ci l'aurait détecté depuis longtemps. Donc soit le problème est très récent (moins d'une semaine), soit tu utilises un système de fichier qui provoque ce bug. Je vais faire des tests de mon côté, si tu est obligé de faire un chown, c'est qu'il y a bien un problème.

**Comment by Rathorian** [comment]
Les 2 fois ou j'ai essayé l'installation du domaine supplémentaire, il fallait effectivement que je face le "chown" oui.
Mon système de fichier est BTRFS.

Après pour le reste, je suis une bille ^^

**Comment by hardware** [comment]
J'ai pas le bug lorsque les 3 domaines sont créés en même temps, donc c'est pour ça qu'il y a aucun problème pendant la phase de test, par contre lorsque je crée un second domaine lorsqu'il y en a déjà un d'existant, là j'arrive à reproduire le problème.

```
drwxr-xr-x  2 vmail vmail 4096 Aug 26 12:24 domain.tld
drwxr-xr-x  2 root  root  4096 Nov 27 12:55 domain2.tld
```

Merci d'avoir remonté ça, je vais essayer de corriger ce bug.

**Comment by hardware** [comment]
Ce problème est résolu avec le commit b66c9e7 disponible sur avec le tag `1.1-latest`.

**Comment by Rathorian** [comment]
Merci beaucoup pour la rapidité !

Comme tu as pu le voir sur mon docker-compose, je suis sur le tag `1.1-stable`, j'attendrais les prochaines mises à jour.
