### ISSUE TITLE
Error: Can't connect to database

### ISSUE THREAD

**Issue by cloudtestsoftware** [hardware/mailserver#199]
Hi Guys,

I was trying couple of days to use all of these examples given and not able to launch docker container successfully.

Lastly I tried below config given by but seeing error in PHP Admin setup screen. Can anyone please help me what wrong in the db setup configuration

Postfix Admin Setup Checker

Running software:

PHP version 7.1.9
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: presence config.local.php - OK
Depends on: MySQL 4.1 - OK
**Error: Can't connect to database
**Please edit the $CONF['database_*'] parameters in config.local.php.
DEBUG INFORMATION:
Connect: php_network_getaddresses: getaddrinfo failed: Name does not resolve****

Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Please fix the errors listed above.

﻿version: '2.1'
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy:alpine'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/mnt/docker/certs:/etc/nginx/certs:ro'
      - '/mnt/docker/nginx/vhost.d:/etc/nginx/vhost.d'
      - '/mnt/docker/nginx/html:/usr/share/nginx/html'
    depends_on:
      - postfixadmin
      - rainloop
      - mailserver
  letsencrypt-nginx-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy
    restart: always
    environment:
      ACME_TOS_HASH: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
    volumes_from:
      - nginx-proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/mnt/docker/certs:/etc/nginx/certs'
    depends_on:
      - nginx-proxy
  mailserver:
    image: 'hardware/mailserver:1.1-stable'
    container_name: mailserver
    domainname: mydomian.com
    hostname: mail
    restart: always
    ports:
      - '25:25'
      - '143:143'
      - '587:587'
      - '993:993'
      - '4190:4190'
    environment:
      - DBPASS=db2345XXNy!
      - RSPAMD_PASSWORD=db2345XXNy!
      - ADD_DOMAINS=mydomian.com
      - 'VIRTUAL_HOST=spam.mydomian.com,mail.mydomian.com'
      - VIRTUAL_PORT=11334
      - HTTPS_METHOD=redirect
    volumes:
      - '/mnt/docker/mail:/var/mail'
      - '/mnt/docker/certs:/etc/letsencrypt/live'
    depends_on:
      - mariadb
      - redis
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: mydomian.com
    hostname: postfixadmin
    restart: always
    environment:
      DBPASS: db2345XXNy!
      DBHOST: mariadb
      VIRTUAL_HOST: postfixadmin.mydomian.com
      HTTPS_METHOD: redirect
    depends_on:
      - mailserver
      - mariadb
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: always
    environment:
      VIRTUAL_HOST: webmail.mydomian.com
      LETSENCRYPT_EMAIL: me@mydomian.com
      LETSENCRYPT_HOST: 'mail.mydomian.com,webmail.mydomian.com,postfixadmin.mydomian.com,spam.mydomian.com'
      HTTPS_METHOD: redirect
    volumes:
      - '/mnt/docker/rainloop:/rainloop/data'
    depends_on:
      - mailserver
      - mariadb
  mariadb:
    image: 'mariadb:10.1'
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=db2345XXNy!
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix11
      - MYSQL_PASSWORD=db2345XXNy!
    volumes:
      - '/mnt/docker/mysql/db:/var/lib/mysql'
  redis:
    image: 'redis:3.2-alpine'
    container_name: redis
    restart: always
    command: 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=1024
    volumes:
      - '/mnt/docker/redis/db/:/data'

**Comment by hardware** [comment]
> Error: Can't connect to database
> Please edit the $CONF['database_'] parameters in config.local.php.
> DEBUG INFORMATION:
> Connect: php_network_getaddresses: getaddrinfo failed: Name does not resolve

Try to resolve and ping your mariadb container from the postfixadmin container.

```bash
# docker exec -ti postfixadmin sh

getent hosts $DBHOST
ping $DBHOST
```

**Comment by minha-eveningglow** [comment]
I have a similar problem my setup page says:

```
Error: Can't connect to database
Please edit the $CONF['database_*'] parameters in config.local.php.
DEBUG INFORMATION:
Connect: Access denied for user 'postfix'@'172.19.0.5' (using password: YES)
```

I just copied sample docker_compose.yml  and changed domain.tld & password.

When I chekced the conatiner host file, ip address is there:
```
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.19.0.5 mail.domain.tld mail
```

**Comment by AndrewSav** [comment]
@minha-eveningglow double check the password in both places?
