### ISSUE TITLE
How to initialize database

### ISSUE THREAD

**Issue by konstantinj** [hardware/mailserver#2]
Hi,

just wanted to use your mailserver image but I wonder how to initialize the database. In the readme you suggest to generate a new password and then UPDATE the admin user. But the database was never filled with any data, neither is there a structure.

How is this image supposed to work?

**Comment by hardware** [comment]
you can use [postfixadmin](https://github.com/hardware/postfixadmin) to initialize the database, then manage your mailboxes and virtual domains.
