### ISSUE TITLE
Yahoo - Problem

### ISSUE THREAD

**Issue by Moimemeici** [hardware/mailserver#202]
Hello Hardware,
sorry for disturb and for my English 
I have problem when I sending email for yahoo.
i have an error, I don't have Log at moment but it's yahoo don't accepted mail.
best regard

**Comment by denji** [comment]
Whitelist https://github.com/vstakhov/rspamd/blob/1.6.5/conf/surbl-whitelist.inc#L795-L801

**Comment by hardware** [comment]
Without some logs and error messages from Yahoo, I can't help you :)

**Comment by Moimemeici** [comment]
sorry, 
but i have this message: 

https://help.yahoo.com/kb/postmaster/SLN3436.html

> 
> This is the mail system at host xxx.xxxx.fr.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>                    The mail system
> 
> <kamel.xxxx@yahoo.com>: host mta6.am0.yahoodns.net[74.6.137.64] said: 553 5.7.2
>     [TSS06] All messages from 62.210.211.239 will be permanently deferred;
>     Retrying will NOT succeed. See
>     https://help.yahoo.com/kb/postmaster/SLN3436.html (in reply to MAIL FROM
>     command)

**Comment by hardware** [comment]
Yahoo blacklisted your server. Complete the Yahoo bulk sender form to remove your IP address from the blacklist : http://help.yahoo.com/l/us/yahoo/mail/postmaster/bulkv2.html

And read this : https://help.yahoo.com/kb/postmaster/review-practices-senders-sln3435.html
