### ISSUE TITLE
Use SOGo instead of Rainloop

### ISSUE THREAD

**Issue by l2v-z** [hardware/mailserver#203]
Hi!
Maybe is a good idea to replace rainloop with SOGo (https://sogo.nu/)?
I'm tried to install sogo on my test sever without docker. Looking good.

**Comment by jodumont** [comment]
Hi l2v-z;

I'm thinking moving from [mailcow](https://github.com/mailcow/mailcow-dockerized) to hardware/mailserver mostly for the inverse

Also you could run SOGo independently of you're mail server and comment line from 62 to 70 and 107 in the [docker-compose.sample.yml](https://github.com/hardware/mailserver/blob/master/docker-compose.sample.yml) without any further issue

**Comment by jodumont** [comment]
Nothing wrong with mailcow;
I just work too perfectly out of the box for me

I prefer when I could make it mine (custom, config) and with mailcow I had few issue during update because I did this.

but mailcow still a awesome project a recommend to anyone want a mail service out of the box.

**Comment by hardware** [comment]
SOGo has cool features but it depends on a LDAP server and needs 2GB of memory to run (4GB to run all services in the docker-compose file), rainloop is lighter and easier to maintain in this docker image. As jodumont said, you could run SOGo independently yourself.
