### ISSUE TITLE
Whitelist domain postmaster

### ISSUE THREAD

**Issue by Dryusdan** [hardware/mailserver#205]
Hello
Today, I encounter a lot of problem with rspamd who block all of my postmaster auto mail... But postmaster mail is not spam...
I found on rspamd doc a settings to whitlelist mail : 

```
settings {
	whitelist {
		priority = low;
		rcpt = "postmaster@${DOMAIN}";
		want_spam = yes;
	}
}
```
I write this file on `/etc/rspamd/local.d/settings.conf`. But I don't know where I can write startup code to create this file. 

Regards :)

**Comment by hardware** [comment]
I added the postmaster address in the whitelist : 54922221e3eb4fb1694ff3f544d1639bb81190ba
