### ISSUE TITLE
Yahoo Server Mail rejected 

### ISSUE THREAD

**Issue by Moimemeici** [hardware/mailserver#206]
Hello, sorry i don't have lot time at the moment.

i make test and see the return.

i have this message:

https://help.yahoo.com/kb/postmaster/SLN3436.html

    

> This is the mail system at host xxx.xxxx.fr.
> 
>     I'm sorry to have to inform you that your message could not
>     be delivered to one or more recipients. It's attached below.
> 
>     For further assistance, please send mail to postmaster.
> 
>     If you do so, please include this problem report. You can
>     delete your own text from the attached returned message.
> 
>                    The mail system
> 
>     kamel.xxxx@yahoo.com: host mta6.am0.yahoodns.net[74.6.137.64] said: 553 5.7.2
>     [TSS06] All messages from 62.xxx.xxx.xxxx will be permanently deferred;
>     Retrying will NOT succeed. See
>     https://help.yahoo.com/kb/postmaster/SLN3436.html (in reply to MAIL FROM
>     command)

My server is not blacklisted, and i have 10/10 mail-tester

**Comment by hardware** [comment]
Yahoo blacklisted your server. Complete the Yahoo bulk sender form to remove your IP address from the blacklist : http://help.yahoo.com/l/us/yahoo/mail/postmaster/bulkv2.html

And read this : https://help.yahoo.com/kb/postmaster/review-practices-senders-sln3435.html

**Comment by Moimemeici** [comment]
que dois je mettre ici ? je ne sais pas à quoi cela correspond ?
Privacy Policy URL

**Comment by hardware** [comment]
Peux-tu faire un screen du formulaire s'il te plait ?

**Comment by Moimemeici** [comment]
Je vais tenter de leur répondre dans la soirée

> Hi Benrabah,
> Thank you for contacting Yahoo Customer Care.
> Without a specific SMTP error message, we can't effectively troubleshoot the issue that resulted in the delivery failure.
> Provide the following information in your response:
> 
>     Detailed description of the problem (including when it started).
>     The sending IP(s) affected.
>     What types of emails are being sent from the affected IP(s)?
>     The output of a manual SMTP test with telnet from your mail server to our servers showing the SMTP conversation leading up to, including the rejection message. Telnet to this host and port number: telnet mta5.am0.yahoodns.net 25
>     Log messages from your mail server showing which IP you connected to and what responses you got from the remote server at the time you received the failures.
> 
> Without the requested information, we'll be unable to investigate the problem. 
> I'm looking forward to your reply.  
> 
> Have a great day!
> Regards,
> Jessica
> Yahoo Customer Care
