### ISSUE TITLE
clamav-unofficial-sigs

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#207]
More clamav signature databases: https://github.com/extremeshok/clamav-unofficial-sigs

> clamav-unofficial-sigs.sh script that currently supports updating third-party signature databases provided by Sanesecurity, FOXHOLE, OITC, Scamnailer, BOFHLAND, CRDF, Porcupine, Securiteinfo, MalwarePatrol, Yara-Rules Project, etc.

**Comment by hardware** [comment]
I added clamav-unofficial-sigs updater with the last commit e0088fe34d3fa735c74c61456b169c9feb071b79.

@denji You can review the changes and test this new feature with `1.1-latest` docker tag.

```ini
# /mnt/docker/mail/clamav-unofficial-sigs/user.conf

user_configuration_complete="yes"
```
**clamav-unofficial-sigs log file :**
```
docker exec mailserver cat /var/log/clamav-unofficial-sigs/clamav-unofficial-sigs.log | less
```

**Docker log :** 
```
docker logs -f mailserver

[INFO] clamav-unofficial-sigs is enabled (user configuration found)
[...]
s6-supervise : clamav unofficial signature update running
s6-supervise : virus database downloaded, spawning clamd process
[...]
clamd[xxxxxx]: SIGHUP caught: re-opening log file.
s6-supervise : clamav unofficial signature update done
```

https://github.com/hardware/mailserver#third-party-clamav-signature-databases
