### ISSUE TITLE
Petit problème !

### ISSUE THREAD

**Issue by jimmy-rich** [hardware/mailserver#208]
Salut, 

J'ai vu que tu était français du coup je t'écrie en français.

Je suis un peut perdu au niveau de l'installation, et t'il compatible avec https://portainer.io ?

J'ai déjà essayé plusieurs fois manuellement de l'installer sur mon VPS OVH mes concrètement à chaque fois y'a un autre problème..

Merci à toi d'avance !

Bonne soirée

**Comment by xataz** [comment]
Salut,

Il faudrait plus d'information sur les opérations que tu as essayé pour pouvoir t'aider.
Autrement oui c'est compatible portainer, mais pas de template existant

**Comment by jimmy-rich** [comment]
Salut,

Pour être franc j'ai essayé beaucoup de chose, je comprend rien du tout les étape à suivre..

**Comment by hardware** [comment]
Si tu comprends pas du tout le readme, ça veut dire que cette image docker n'est pas faite pour toi. Regarde plutôt une solution clé en main comme [Mail-in-a-Box](https://mailinabox.email/) ou [Mailcow](https://mailcow.email/). Mon image docker est plus orientée pour les gens qui ont déjà un setup mail fonctionnel sans docker et qui souhaitent passer leur infrastructure mail sous Docker.

Regarde https://mondedie.fr/, il y a des tutos qui pourraient t'aider. Je peux pas tout expliquer dans le readme sinon il ferait 3km de long.

**Comment by hardware** [comment]
Je viens de remplacer Nginx par Traefik, l'installation devrait être plus facile. Si tu comprends la partie DNS, le reste se déroule assez facilement.

**Comment by jimmy-rich** [comment]
Hello,

Je vais donc réessayé car j'ai essayé avec Mailcow mes la partie DNS plante totalement.. (Je reçois les mail mes il ne parte pas). 

Mailcow explique mal la partie DNS je trouve.

Je te fait un retour dans la soirée !
