### ISSUE TITLE
Add integration/unit tests

### ISSUE THREAD

**Issue by hardware** [hardware/mailserver#21]

**Comment by arckosfr** [comment]
- Try to maintain hardware/rainloop image (not dockerfile) up-to-datee (its actually not).

**Comment by hardware** [comment]
@arckosfr : you can now update with one-click https://github.com/hardware/rainloop/commit/e548bd3f0040f9293db3ec5c444bc7180d8fc41e :)

**Comment by Wonderfall** [comment]
But it's not GPL anymore. :(

**Comment by hardware** [comment]
@Wonderfall : yes :( but it's a good for personal or hobby sized usage.

**Comment by hardware** [comment]
@Wonderfall Automatically build trigger with witch POST event ?

**Comment by Wonderfall** [comment]
Stallman might come and kick your ass while you sleep, and his spirit will haunt you until your death, so if I was you I'd consider this seriously!

You can get a trigger URL/Token in the "Build Settings" tab on Docker Hub.

**Comment by hardware** [comment]
I rollback to community edition, thank for this idea.

**Comment by hardware** [comment]
I'm giving up with integration/unit tests, maybe I'll add it when this docker image will be more used by the community..
