### ISSUE TITLE
Missing Steps

### ISSUE THREAD

**Issue by DarkBlaez** [hardware/mailserver#212]
The core instructions are missing steps for a fresh install.

# Create a new docker network for Traefik
docker network create http_network

# Create the required folders and files
mkdir -p /mnt/docker/traefik/acme && cd /mnt/docker
touch docker-compose.yml traefik/traefik.toml traefik/acme/acme.json
chmod 600 docker-compose.yml traefik/traefik.toml traefik/acme/acme.json

This will not yield a successful install/run. Only in subsequent steps does it mention to copy/obtain docker-compose, traefik.toml. However, need to make a reference much sooner given the sequence of steps above will not yeail any result other than non-success

DB

**Comment by hardware** [comment]
> need to make a reference much sooner

Where ? The steps above do not require to have the contents of the docker-compose and traefik.toml files.
