### ISSUE TITLE
Rainloop - Change User Password

### ISSUE THREAD

**Issue by Moimemeici** [hardware/mailserver#213]
#### Classification
* [x] Question

#### Reproducibility
* [x] Not applicable

It's possible make Plugin on rainloop for change password ?
https://github.com/RainLoop/rainloop-webmail/tree/master/plugins/postfixadmin-change-password

I don't test for the moment but it's good idea the user change password alone non ?
Other Question, it's possible make OpenLdap with your Mailserver ?

**Comment by hardware** [comment]
> It's possible make Plugin on rainloop for change password ?

I added postfixadmin-change-password few days ago :

https://github.com/hardware/rainloop/commit/fb32a710da86e8d4f55ac0fab250e127ce9d319e

> Other Question, it's possible make OpenLdap with your Mailserver ?

It's open for contributors with a pull request. For my needs, i don't need OpenLDAP support.
