### ISSUE TITLE
traefik certificates not being loaded into mailserver

### ISSUE THREAD

**Issue by 1n5aN1aC** [hardware/mailserver#214]
Having a bit of trouble transitioning to traefik.

In the readme.md, you mention that to make the mailserver use the certs managed by traefik, I simply need to add the following to my docker-compose:

    volumes:
      - /mnt/docker/traefik/acme:/etc/letsencrypt/acme

However, after adding the following, SMTP is still a self-signed wildcard:  (Though webmail works)

    volumes:
          - ${VOLUMES_ROOT_PATH}/mail:/var/mail
          - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme

Here's the relevant startup logs from `docker logs -f mailserver`

    [INFO] No Let's encrypt live directory found
    [INFO] Using /var/mail/ssl/selfsigned/ folder
    [INFO] Found DKIM key pair for domain mailmag.net - skip creation
    [.....]

Any idea why it's not able to find the acme.json?  It is chmodded to 600, like the instructions state.

**Comment by denji** [comment]
acme.json type `folder` or `file`?

**Comment by 1n5aN1aC** [comment]
@denji I've got /mnt/docker/traefik/acme/acme.json which is an actual valid json file with the keys & certs stored in it.

**Comment by Rathorian** [comment]
I have exactly the same problem and according to the file "acme.json" the certificates are created but they do not use them.

Is this a problem from the old configuration I had with certbot that requires to delete some files in the folder "mail" or others ....

**Comment by Rathorian** [comment]
I found, I forgot to add the specific volume for Let's Encrypt on the container "mailserver":

```- ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme```

But I have an error in the generation of certificates:

```docker logs -f mailserver
[INFO] Search for SSL certificates generated by Traefik
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] ...
[INFO] acme.json found, dumping into pem files
[ERROR] mail.rathorian.fr.crt or mail.rathorian.fr.key not found !
[ERROR] Look /mnt/docker/traefik/acme/dump.log for more information```

I have absolutely no file named "dump.log" generated in the folder "docker / traefik / acme" so I do not know how to solve the problem without logging ...

**Comment by Rathorian** [comment]
Going directly to the container of Traefik, I found the file "dump.log" but what it returns is not great:

```
writing RSA key
writing RSA key
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting private key for postfixadmin.domaine.fr
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting private key for postfixadmin.domaine.fr
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting private key for postfixadmin.domaine.fr
Extracting cert bundle for spam.domaine.fr
Extracting private key for spam.domaine.fr
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting private key for postfixadmin.domaine.fr
Extracting cert bundle for spam.domaine.fr
Extracting private key for spam.domaine.fr
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting private key for postfixadmin.domaine.fr
Extracting cert bundle for spam.domaine.fr
Extracting private key for spam.domaine.fr
```

**Comment by 1n5aN1aC** [comment]
I would like to comment that I have solved my issue!  (not @Rathorian's though. :( )

My issue was simply that I had my dockertag set to `1.1-stable` instead of `1.1-latest` which was causing it to use the old run script, and not even trying to import the acme.json.

Unfortunately, I don't have any ideas what @Rathorian's issue is, since it looks like it's finding & extracting the certs.....

**Comment by Rathorian** [comment]
OK.

For me it seems that a restart of the containers has made everything work properly. (I hope)

**Comment by hardware** [comment]
> My issue was simply that I had my dockertag set to 1.1-stable instead of 1.1-latest which was causing it to use the old run script, and not even trying to import the acme.json.

@1n5aN1aC Probably because you did not pull the docker image recently. Don't forget to pull your docker images regularly for security and updates.

> Going directly to the container of Traefik, I found the file "dump.log" but what it returns is not great.

@Rathorian  Where did you find the log file ? It should be here : `/etc/letsencrypt/acme/dump.log` in your docker volume ` - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme`

```
writing RSA key
Extracting cert bundle for postfixadmin.domaine.fr
Extracting cert bundle for spam.domaine.fr
```

> For me it seems that a restart of the containers has made everything work properly. (I hope)

Because you added `traefik.frontend.rule=Host:mail.${DOMAIN}` which has generated a certificate for `mail.domain.tld` sub domain. Before doing that, the mailserver could not find the certificat bundle for `mail.domain.tld` because you did not specify this sub domain in your docker-compose.yml.

**Comment by hardware** [comment]
@Rathorian @1n5aN1aC I added more information in the readme.

https://github.com/hardware/mailserver#ssl-certificates
