### ISSUE TITLE
Poor rspamd results for a single mailbox 

### ISSUE THREAD

**Issue by digitalkram** [hardware/mailserver#216]
#### Classification
* [X] Question
#### Reproducibility
* [X] not applicable 
#### Docker information
Not relevant 
#### Description
Running 20 mailboxes across 5 domains there is a good rspamd filter accuracy for 19 mailboxes with nearly no spam delivered to inbox. 
For one account however there is a flood of spam (~20 pcs/day) coming to mailbox with "no action" taken. 
How is that possible and is there anything I can do to resolve this issue? 
I know that is quite a generic question and maybe more relevant for rspamd community but any input is very much appreciated.. 
Score of spam seems to be max 3-4/20 usually but some are even negative
#### Steps to reproduce
n/a

#### Expected results
Same filter accuracy on all mailboxes 

#### Actual results
Single mailbox is receiving significantly more spam then others 

#### Debugging information
n/a

#### Configuration (docker-compose.yml, traefik.toml...etc)
Everything default. Let me know if something helpful can be provided..

Thanks a lot in advance!

**Comment by hardware** [comment]
Can you scan some e-mails in the user's INBOX or spam folder and post the result ?

```
docker exec -ti mailserver rspamc symbols /var/mail/vhosts/domain.tld/john.doe/mail/cur
docker exec -ti mailserver rspamc symbols /var/mail/vhosts/domain.tld/john.doe/mail/.Spam/cur/*
```

**Comment by digitalkram** [comment]
hi

thanks for your response! 

Spam:
https://pastebin.com/raw/dq7QTsqu
(mail.censored.com is my server, problem@domain.com is the problematic account)

Ham:
https://pastebin.com/raw/dcEEGGfk
(from inbox, some spam might not yet be moved to Spam...)

Does that shed some light on it?

**Comment by hardware** [comment]
Can you give me some example of mail with "no action" taken but that you think is spam. I need maildir filename for each mail, example `1512578141.M475606P30012.mail.domain.tld,S=64906,W=66412:2,S`.

**Comment by digitalkram** [comment]
i will ask user to sort undetected spam into a seperate folder an dget back to you. he moved all to spam so i can't decide which was detected and which wasn't

**Comment by hardware** [comment]
> he moved all to spam

Ok, with that i was able to check some emails in Spam folder with properties set to `Spam=false` and `Action=no action or greylist`. Most of these mails have a negative bayesian classifier (BAYES_HAM) and they don't have enough symbols increasing the score. 
 
Your user must train rspamd to handle correctly this kind of e-mails by putting them in the Spam directory. He will have less spam after some time. 

My docker image is configured to perfom an auto ham learning when a message have a negative score, but you can change that :

https://rspamd.com/doc/configuration/statistic.html#autolearning

https://github.com/hardware/mailserver/blob/c5fad7eb17ddef039ae61132fe1f60510f86e6b4/rootfs/etc/rspamd/local.d/statistic.conf#L10-L12

**Comment by denji** [comment]
* https://rspamd.com/rspamd_statistics/

`rspamadm` utility can convert fuzzy hashes from SQLite storage to Redis using `fuzzyconvert` tool.

## Rspamadm fuzzyconvert

This command migrates fuzzy hashes from SQLite to Redis. Typical invocation would be something like `rspamadm fuzzyconvert -d /var/lib/rspamd/fuzzy.db -h 127.0.0.1:6379 -e 2419200` where `-e` is your hash expiry time in seconds.

~~~
Application Options:
  -d, --database     Input sqlite
  -e, --expiry       Time in seconds after which hashes should be expired
  -h, --host         Output redis ip (in format ip:port)
  -D, --dbname       Database in redis (should be numeric)
  -p, --password     Password to connect to redis
~~~

**Comment by digitalkram** [comment]
hi hardware

thanks for your reply. I meanwhile asked the user to copy undetected Spam to a dedicated folder to seperate it from the ones that go to .Spam automagically.

27 pcs in 22 hours ended in this dedicated folder. Actually he is doing the move to .Spam manually as he was hopign the filter learns and this is for at least 3 months now.

Maybe the autolearn to ham for negative scores is an issue in this case.

As I had the all in a dedicated place I tried to teach them to the filter like this (does that work?):
```bash
find . -type f -name '*mail.digitalkr.am*' | while read line; do docker exec -i mailserver rspamc learn_ham < $line ; done
```

The majority of files were giving this output:
```
Results for file: stdin (0.000 seconds)
HTTP error: 410, <bb56062e90e5326726ab7e2d95437c79@disegnidacolorare.info> is skipped for bayes classifier: already in class ham; probability 100.00%
```

And only five (probably those with a score > 0) gave this output:
```
Results for file: stdin (0.000 seconds)
success = true;
```

So I should disabled that ham leaning on negative score, right?

And is there a way to learn definite Spam anyways even if it is learned as ham before? Som kind of a force flag? Tried to google it but found nothing obvious...

Thanks again!

Cheers,

**Comment by hardware** [comment]
> 27 pcs in 22 hours ended in this dedicated folder. Actually he is doing the move to .Spam manually as he was hopign the filter learns and this is for at least 3 months now.

If your user train rspamd every day but that there is no change after several months, ask on rspamd mailing list if there is a better approach in this case.

**Comment by digitalkram** [comment]
I will but obviously I should also disable auto ham learning as it refuses to learn spam that it learned before as ham..

thanks
