### ISSUE TITLE
rspamd name resolution issues all of the sudden

### ISSUE THREAD

**Issue by digitalkram** [hardware/mailserver#217]
#### Classification
* [X] Question
#### Reproducibility
* [X] Always (at the moment)
#### Docker information
docker info
```
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 28
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 151
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.92-mainline-rev1
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.62GiB
Name: hostname
ID: CKIB:2BAP:23T7:AKZW:PVTK:6MS2:6UYY:KN5B:34IE:PHFK:4COB:BQRP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
docker images hardware/mailserver --digests --filter  "dangling=false"
```
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:8e6a2d3f4abe210ebd34c960ce166d881c5ee0934965d34b14ecbcafe353f8c4   b28018fb9e77        6 weeks ago         331MB
```

#### Description
[This is a different isntallation then the one with the rspamd issue!]
Since a few days there are various DNS related log messages in the log and sending small plain text emails takes 20-30 seconds:
```
2018-02-23T08:28:33.571608+00:00 mail rspamd[605]: <62a0bb>; lua; asn.lua:63: error querying dns: server fail
2018-02-23T08:28:45.932841+00:00 mail rspamd[605]: <62e7c8>; lua; asn.lua:63: error querying dns: server fail
2018-02-23T08:28:58.265498+00:00 mail rspamd[605]: <62e7c8>; lua; emails.lua:48: Error querying DNS: server fail
2018-02-23T08:28:58.296785+00:00 mail rspamd[605]: <62e7c8>; lua; emails.lua:48: Error querying DNS: server fail
2018-02-23T08:28:58.296840+00:00 mail rspamd[605]: <62e7c8>; lua; emails.lua:48: Error querying DNS: server fail

2018-02-13T04:31:34.522529+00:00 mail postfix/smtpd[18307]: warning: hostname static.user75.64.140.104.dsli.com does not resolve to address 64.140.104.75: Name or service not known
2018-02-13T05:48:18.489586+00:00 mail postfix/smtpd[18469]: warning: hostname hn.kd.ny.adsl does not resolve to address 222.139.205.241: Name or service not known
```
Fun fact 1:  It was working for days before
Fun fact 2: the names that "do not reolve" to a specific IP actually do when checked with nslookup (both on host and inside of mailserver container)

#### Steps to reproduce
no idea

#### Expected results
No such message in log
Fast mail sending
#### Actual results
Messages like this in the log
Slow mail sending

Any input appreciated! Thanks a lot in advance

EDIT: Based on #174 I tried to use DISABLE_DNS_RESOLVER which actually resovled the problem of slow mail sending (unbound resolver disabled) but still the errors about resolution issues are in the log
And I'll check with the plattform provider if they block/limit queries

**Comment by digitalkram** [comment]
hi hardware

I'll try to go with option 1 and if they refuse to with option 3. 

Regarding the PTR stuff. I assumed that it is as you said. However there are also the same messages for a few hosts I know (including the mailserver itself) where there is a correct PTR record (forward and reverse lookup work and matrch) that is why I was confused. But maybe that is due to the other issue..?

Thanks again for your help!

Cheers

**Comment by hardware** [comment]
> But maybe that is due to the other issue..?

I don't think so if you switch DISABLE_DNS_RESOLVER to true. 

> However there are also the same messages for a few hosts I know (including the mailserver itself) where there is a correct PTR record

Any examples ? Do you have this message for ALL domains ?

**Comment by digitalkram** [comment]
Plattform claimed they do not limit. The resolution issue itself for the lua stuff is now working again so it was an intermittent issue only obviously and probably outside of the mailserver setup itself
Still there is the message indicating a PTR issue also for the mailserver hostname itself.
