### ISSUE TITLE
AD / LDAP Support 

### ISSUE THREAD

**Issue by jeffwji** [hardware/mailserver#218]
If not yet, do you have plan?

**Comment by denji** [comment]
Similar question has already been asked #33.

@hardware How about isolated of the ability to conduct testing based on FreeIPA distro?

**Comment by hardware** [comment]
> If not yet, do you have plan?

No, but contribution are welcome.

**Comment by stas630** [comment]
I'm using the ldap!
DBHOST=openldap!

docker-compose.yml:
--------
  mailserver:
    container_name: mailserver
    build:
      context: ${VOLUMES_ROOT_PATH}/dovecot
      dockerfile: Dockerfile.mailserver
    environment:
      - DBHOST=openldap
...
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
    depends_on:
      - openldap
#      - mariadb
      - redis
--------

cat dovecot/Dockerfile.mailserver 
----
FROM hardware/mailserver:1.1-stable
RUN apt-get update && apt-get install -y -q --no-install-recommends dovecot-ldap postfix-ldap \
&& apt-get autoremove -y \
&& apt-get clean \
&& rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/debconf/*-old

COPY auth-sql.conf.ext /etc/dovecot/conf.d
COPY dynamicmaps.cf /etc/postfix
-----

touch auth-sql.conf.ext  in  dovecot/ (Empty file)

cat dovecot/dynamicmaps.cf
---
sqlite	postfix-sqlite.so	dict_sqlite_open	
pcre	postfix-pcre.so	dict_pcre_open	
mysql	postfix-mysql.so	dict_mysql_open	
ldap	postfix-ldap.so		dict_ldap_open
---

mail/dovecot/conf.d/10-auth.conf
---
disable_plaintext_auth = yes                                                                                 
auth_mechanisms = plain login                                                                                
!include /var/mail/dovecot/conf.d/auth-ldap.conf.ext
---

mail/dovecot/conf.d/auth-ldap.conf.ext
-----
passdb {                                                                                                     
  driver = ldap                                                                                              
  args = /var/mail/dovecot/conf.d/dovecot-ldap.conf.ext                                                      
}
userdb {                                                                                                     
  driver = ldap                                                                                              
  args = /var/mail/dovecot/conf.d/dovecot-ldap.conf.ext                                                      
}
------

mail/dovecot/conf.d/auth-ldap.conf.ext
----
hosts = openldap                                                                                             
auth_bind = yes                                                                                              
auth_bind_userdn = uid=%n,dc=%Dd                                                                             
base = dc=%Dd                                                                                                
ldap_version = 3                                                                                             
pass_attrs = uid=user
dn = cn=admin,dc=ru                                                                                          
dnpass = xxxxxxxxx
ldap_version = 3                                                                                             
scope = subtree
user_attrs = mailQuotaSize=quota_rule=*:storage=%$M,mailQuotaCount=quota_rule2=*:messages=%$,uid=5000,=gid=5000,=home=/var/mail/vhost/%d/%Ln
user_filter = (&(objectClass=inetOrgPerson)(uid=%n))
#For using doveadm -A:
#iterate_attrs = =user=%{ldap:uid}
#iterate_attrs = mail=user
#iterate_filter = (objectClass=posixAccount)
-----
mail/dovecot/conf.d/90-quota.conf
---
plugin {

  #quota = dict:User quota::proxy::sqlquota
  quota = maildir:User quota
  quota_rule = *:storage=5GB
  quota_rule2 = Trash:storage=+100M
  quota_grace = 10%%
  quota_exceeded_message = The quota of this mailbox is exhausted. Contact your system administrator.
  quota_warning =  storage=90%% quota-warning 90 %u
  quota_warning2 = storage=80%% quota-warning 80 %u
  quota_warning3 = storage=70%% quota-warning 70 %u
  quota_warning4 = storage=60%% quota-warning 60 %u

}
service quota-warning {

  executable = script /usr/local/bin/quota-warning.sh
  user = vmail

  unix_listener quota-warning {
    user = vmail
  }

}
-------

mail/postfix/custom.conf
--------
smtpd_sender_login_maps = hash:/var/mail/postfix/hash/virtual_sender_login,ldap:/var/mail/postfix/ldap/virtual_sender_login.cf
virtual_mailbox_domains = hash:/var/mail/postfix/hash/virtual-mailbox-domains
virtual_mailbox_maps    = ldap:/var/mail/postfix/ldap/virtual-mailbox-maps.cf
virtual_alias_maps      = hash:/var/mail/postfix/hash/virtual-alias-maps,
                          hash:/var/mail/postfix/virtual
--------

For Example
mail/postfix/ldap/virtual-mailbox-maps.cf 
---
bind = yes
bind_dn = cn=admin,dc=ru
bind_pw = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
server_host= openldap
#server_port= 389
search_base= dc=mydomain,dc=ru
query_filter= (&(objectClass=inetOrgPerson)(mail=%s))
result_attribute= uid
result_format= %s
version = 3
timeout=20
scope=one
-----

**Comment by hardware** [comment]
@PeerD @zxtwonder @loic-lopez @Aphris-Karu @stkac @johansmitsnl @sknight80 @davydov-vyacheslav  LDAP support made by @PeerD  has been merged into the master branch. You can switch to the latest image with `1.1-latest` docker tag to start using it. If no issue is reported, LDAP support will be pushed into the stable branch in september 2019.

Thank you to all contributors.

**Comment by johansmitsnl** [comment]
@hardware I have the image running now, keep you posted if something goes wrong.

**Comment by loic-lopez** [comment]
I have an instance running with a local database, how to migrate to LDAP?

**Comment by loic-lopez** [comment]
Also i'm using Atlassian Crowd for my LDAP server: [atlassian.com/en/software/crowd](https://www.atlassian.com/en/software/crowd)

**Comment by johansmitsnl** [comment]
I guess that this is out of scope for this issue and project as well. 
My guess is that you should search for "generic" mailserver solutions. This project is such a project but in a container.

**Comment by loic-lopez** [comment]
@johansmitsnl I don't understand your response, sorry, but Atlassian crowd offer multiple services like hosting a LDAP directory and much more, so I only would like to my users connects to the mail though Crowd.

**Comment by johansmitsnl** [comment]
> I have an instance running with a local database, how to migrate to LDAP?

@loic-lopez I was referring to this question.

To the `crowd` question, if you compose the right LDAP queries it should work. What I tried to say is that the mailserver project is not "different" in the way Postfix and Dovecot connect to a ldap server.

But I guess it is better to open a new issue then continue writing on a closed issue.
