### ISSUE TITLE
What is related with "tried to use disallowed plaintext auth"

### ISSUE THREAD

**Issue by MichelDiz** [hardware/mailserver#219]
#### Classification
_Please delete options that are not relevant._

* [X] Question

Rainloop failing to auth.

`spam dovecot: imap-login: Disconnected (tried to use disallowed plaintext auth): user=<micheldiz@site.com.br>, rip=10.42.40.225, lip=10.42.191.95, session=<LdXJ4UNm8qIKKijh>`

Using Rancher. Locally in a VirtualBox machine.

Observation: It's working via MacOs Mail. IMAP.

**Comment by denji** [comment]
* https://github.com/hardware/mailserver#custom-configuration-for-dovecot
 * https://github.com/hardware/mailserver/blob/54922221e3eb4fb1694ff3f544d1639bb81190ba/rootfs/etc/dovecot/conf.d/10-auth.conf#L1

**Comment by hardware** [comment]
You are trying to connect to imap without SSL/TLS or STARTTLS.

![](http://i.imgur.com/GFbbJzs.png)
