### ISSUE TITLE
Postfixadmin

### ISSUE THREAD

**Issue by Yfksw65** [hardware/mailserver#22]
Bonjour,

J'ai mis en place votre solution, cela fonctionne correctement à défaut d'une erreur sur postfixadmin, en effet lors de la création d'un utilisateur / envoi d'un message depuis l'interface j'ai l'erreur : 

Erreur lors de l'envoit du message! (adresse@domaine.com)

J'ai beau regarder les logs avec des docker logs -f, je ne vois rien.

Une idée ? 

Merci beaucoup pour votre fabuleux travail

**Comment by hardware** [comment]
Oui c'est normal, le conteneur postfixadmin est isolé du serveur mail donc il peut pas envoyer le message de bienvenue, suffit juste de décocher la case pour pas avoir cette erreur, ça n'a pas de conséquence.
