### ISSUE TITLE
GraphDB Proposal - Open for discussion.

### ISSUE THREAD

**Issue by MichelDiz** [hardware/mailserver#220]
#### Classification
* [X] Question
* [X] Feature/Enhancement

#### Description

What do you think of switching to a graph database?
I have used (for some time) a very good Graph database, called "Dgraph". It is a mixture of noSQL and NewSQL with a language equal to GraphQL.

This is to eliminate the use of Mariadb and Redis. For the Dgraph is the best of these two worlds. It was thought to be a Realtime Database.

We would just need to map the relationships of your application today and then I can build an approach.

Let me know what you think.

**Comment by hardware** [comment]
Neither postfix nor dovecot nor rspamd seems compatible with this kind of database.

**Comment by denji** [comment]
Cockroach, probably works well because it supports the pgsql protocol.
Dgraph used protocols (Grpc / HTTP + JSON / RDF)...

**Comment by MichelDiz** [comment]
True, I was silly for not thinking about these software. Would have to change them. Which generates round trips with others.

@denji I have no experience with CockroachDB.

In that case, It would have to create a "Bridge" between the Graph DB and the software as the "Prisma" does. Dgraph intends to add Gremlin and Cypher. What could be an option for "bridge".

Either way it would be better if the software had support from the top down.
