### ISSUE TITLE
[IPv6 Only] Rspamd tries to DKIM sign incoming emails

### ISSUE THREAD

**Issue by j-schumann** [hardware/mailserver#221]
#### Classification
* [X] Question
* [X] Minor bug

#### Reproducibility
* [X] Sometimes

#### Docker information
```
docker info
Server Version: 17.05.0-ce
Kernel Version: 4.4.0-97-generic
Operating System: Ubuntu 16.04.4 LTS

docker images hardware/mailserver --digests --filter "dangling=false"
hardware/mailserver   1.1-latest          sha256:f3a51071cf0fac8334a119037f18979                                                                                            b7d5f9d1ad968ed042ea668a57400f01c   de2385334fb9        7 days ago          334M                                                                                           B
```

#### Description
Rspamd tries to DKIM sign **incoming** emails, fails to find key (expected), mails still get delivered.
Happens only with domains that have a DKIM record / mails that are already DKIM signed.

Where does this come from? From ARC signing? Maybe this has something to do with https://github.com/vstakhov/rspamd/issues/1993?

Thanks in advance!

#### Steps to reproduce
1.Receive a mail from google.com/Gmail
2. Check mail.log / Rspamd webui

#### Expected results
No error message

#### Actual results
rspamd[726]: <0d54f0>; proxy; lua_dkim_sign_handler: cannot load dkim key /var/mail/dkim/google.com/private.key: cannot stat private key /var/mail/dkim/google.com/private.key: No such file or directory

#### Debugging information
```
Feb 21 12:05:01 postfix/smtpd[16632]: connect from unknown[172.18.0.1]
Feb 21 12:05:01 postfix/smtpd[16632]: Anonymous TLS connection established from unknown[172.18.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Feb 21 12:05:02 postfix/smtpd[16632]: 208422004F9FA6: client=unknown[172.18.0.1]
Feb 21 12:05:02 postfix/cleanup[16635]: 208422004F9FA6: message-id=<13830214959671084038@google.com>
Feb 21 12:05:02 rspamd[717]: <8e7db3>; proxy; lua_dkim_sign_handler: cannot load dkim key /var/mail/dkim/google.com/private.key: cannot stat private key /var/mail/dkim/google.com/private.key: No such file or directory
Feb 21 12:05:02 rspamd[717]: <8e7db3>; proxy; lua_dkim_sign_handler: cannot load dkim key /var/mail/dkim/google.com/private.key: cannot stat private key /var/mail/dkim/google.com/private.key: No such file or directory
Feb 21 12:05:04 postfix/qmgr[693]: 208422004F9FA6: from=<noreply-dmarc-support@google.com>, size=3611, nrcpt=1 (queue active)
Feb 21 12:05:04 dovecot: lmtp(16638): Connect from local
Feb 21 12:05:04 postfix/smtpd[16632]: disconnect from unknown[172.18.0.1] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Feb 21 12:05:04 dovecot: lmtp(info@mydomain): CZPaEmBSjVr+QAAAWYdMWg: sieve: msgid=<13830214959671084038@google.com>: stored mail into mailbox 'INBOX'
```

Dockerfile
```
FROM hardware/mailserver:1.1-latest

ENV ADD_DOMAINS=xxx

ENV DBHOST=mariadb
ENV DBNAME=postfix
ENV DBUSER=xxx
ENV DBPASS=xxx

ENV RSPAMD_PASSWORD=xxx
ENV REDIS_HOST=127.0.0.1

ENV DISABLE_GREYLISTING=true
ENV TZ=Europe/Berlin
ENV VMAILUID=5000
ENV VMAILGID=5000

COPY rootfs /
```
rootfs only contains some adjusted dovecot config, additional modules for icinga monitoring and adjusted ratelimit.conf for rspamd.

docker-compose.yml
```
  mailserver:
    build: mailserver/
    container_name: mailserver
    domainname: mydomain
    hostname: mail
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 500m
    security_opt:
      - apparmor:docker-default
    ports:
      - "25:25"
      - 143:143
      - 587:587
      - 993:993
      - 4190:4190
      - 11334:11334
    volumes:
      - /var/www/vhosts/mail.mydomain/docker:/var/mail
      - /dev/log:/dev/log
    depends_on:
      - mariadb
  redismail:
    container_name: redismail
    image: redis
    command: redis-server --appendonly yes
    restart: on-failure:5
    network_mode: service:mailserver
    cpu_shares: 128
    mem_limit: 128m
    read_only: true
    security_opt:
      - apparmor:docker-default
    volumes:
      - /var/www/vhosts/mail.mydomain/docker/redis:/data
```

**Comment by hardware** [comment]
> Where does this come from? From ARC signing? Maybe this has something to do with vstakhov/rspamd#1993?

Maybe, does your mail server acts as forwarder ?

Rspamd latest stable version ([1.6.6](https://github.com/vstakhov/rspamd/releases/tag/1.6.6)) have fixed a signing bug, it may be related to your issue :

```
* [Fix] Do not try to sign unknown domains
```

But you already use this version I presume.

```
hardware/mailserver 1.1-latest sha256:f3a51071cf0fac8334a119037f[...] 7 days ago
```

If you don't have the latest rspamd version, rebuild your custom Dockerfile.

> rootfs only contains some adjusted dovecot config, additional modules for icinga monitoring and adjusted ratelimit.conf for rspamd.

Dovecot configuration and rspamd modules can be customized without having to create a custom docker image.

https://github.com/hardware/mailserver#custom-configuration-for-dovecot

**Comment by j-schumann** [comment]
> Maybe, does your mail server acts as forwarder ?
No, the inbox is managed by this server, it is not even a forward to another address on this same server.

> If you don't have the latest rspamd version, rebuild your custom Dockerfile.
Yes, I already have rspamd 1.6.6, it happened with older versions but also with this version.

**Comment by hardware** [comment]
Did you ask on the rspamd mailing list ? I can't reproduce your problem on 3 different mail servers.

**Comment by j-schumann** [comment]
No, not yet. I'll try that, for now it's just an error message, the messages are still delivered and are not marked as spam.
Thanks for your support!

**Comment by navossoc** [comment]
I'm starting to see the same thing.
I don't have many details to provide, but I'm using the "default config" for now.

![image](https://user-images.githubusercontent.com/2457338/37206386-3b480660-2377-11e8-8046-b85df777016d.png)

**Comment by denji** [comment]
/cc @vstakhov, @moisseev, @fatalbanana

> rspamd[726]: <0d54f0>; proxy; lua_dkim_sign_handler: cannot load dkim key /var/mail/dkim/google.com/private.key: cannot stat private key /var/mail/dkim/google.com/private.key: No such file or directory

**Comment by fatalbanana** [comment]
Setting `sign_local = false` in `dkim_signing` configuration should help I suppose.

**Comment by vstakhov** [comment]
In fact, when you hide the real IP of a client, everything is expected to be broken. Don't do it, or this is a least bad problem you have...

**Comment by navossoc** [comment]
@vstakhov Are you referring to remove the headers with the ip on sent messages or something else? 
https://github.com/hardware/mailserver/blob/master/rootfs/etc/postfix/header_checks

**Comment by denji** [comment]
@vstakhov https://github.com/hardware/mailserver/blob/master/rootfs/etc/postfix/main.cf#L206-L214

`milter_mail_macros    = i {mail_addr} {client_addr} {client_name} {auth_authen}`

**Comment by denji** [comment]
@vstakhov `local_addrs`/`local_networks` Will need to add the local subnet for docker?

**Comment by vstakhov** [comment]
If you forward mail from some local MTA to another MTA that, in turn, calls Rspamd, then you need to patch the source IP based on received headers. There is no out-of-the-box functionality for that but you can do it using Lua API. `local_addrs` is irrelevant in this case.

**Comment by hardware** [comment]
> In fact, when you hide the real IP of a client, everything is expected to be broken. Don't do it, or this is a least bad problem you have...

@vstakhov  thanks for the advice, I will change that. 

However, header cleanup is only triggered when sending a mail using submission (587) or smtps (465) ports with a mail client, so that does not explain why rspamd, sometimes, try to sign incoming mails.

https://github.com/hardware/mailserver/blob/5554e33ef16a669dce5c01d1668b24fa1a7772c1/rootfs/etc/postfix/master.cf#L13-L29

**Comment by vstakhov** [comment]
Header cleanup? My question is why Rspamd has an email that pretends to be sent from `172.18.0.1`?

**Comment by denji** [comment]
It seems the problem is in the network settings Docker or compatibility rspamd with docker?

> pretends to be sent from 172.18.0.1

Docker NAT subnet `172.26.0.1/16`

**Comment by hardware** [comment]
Oh ok, We are not talking about the same thing. I did not see the local docker address in IP address field :)

@navossoc @j-schumann I can't reproduce this with my mail server : 

![capture](https://user-images.githubusercontent.com/327354/37219932-4bcb64b6-23c5-11e8-9bd0-543cd1f22e5f.PNG)

A always get the correct IP address in rspamd WebUI field and not a local docker address. Maybe your problem is related to this issue : 
[#43 - sometimes Postfix thinks 172.18.0.1 is the client_ip](https://github.com/hardware/mailserver/issues/43)

This is a docker ~bug~ behavior. Read this : https://github.com/moby/moby/issues/15086

**Comment by navossoc** [comment]
@vstakhov not sure who or what is spoofing that ip address, but...

172.18.0.0/16 and 172.19.0.0/16 are two networks on docker.
172.18.x - http_network
172.19.x = docker_mail_network

This is the last email I have received:

```
Return-Path: <navossoc@gmail.com>
Delivered-To: teste2@revenda.email
Received: from mail-nyc3.revenda.email
	by mail-nyc3.revenda.email (Dovecot) with LMTP id a2pjI/J1olo0SQAA7+qA6A
	for <teste2@revenda.email>; Fri, 09 Mar 2018 11:54:26 +0000
Authentication-Results: mail-nyc3.revenda.email
Received: from mail-qt0-x230.google.com (unknown [172.19.0.1])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail-nyc3.revenda.email (Postfix) with ESMTPS id 1A626B5B
	for <teste2@revenda.email>; Fri,  9 Mar 2018 11:54:25 +0000 (UTC)
Received: by mail-qt0-x230.google.com with SMTP id a23so10376033qtn.0
        for <teste2@revenda.email>; Fri, 09 Mar 2018 03:54:25 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=5+KErOVOO3puPIHf0zTxo10UMRiowm4yep6DYJ72394=;
        b=rnVIKqdIyhbAf3TND4sET16Ca+g0CUO8aIv4WNpHrxHv/KNbmvLCMg+O1D4vJBJ2GW
         t08CNwNCrimGG6bp5pXyC7vOX3SjwrYHBY/3CcYPKyuGj7nbnEt0OVki9VW0l5szBnWk
         C2HLAUOQUQaRCxlfOWcstz4Cq4YX1uHbgKD1Uv36eRUd0QTccpVg1vkHJ/H+Ac+uaT7f
         k1cJYStu+xwBbOObW0fgtSUtzMSjd9fNu2Q3OU6qF4Pn+G5RUKIPhi0BnFR/HmHcJc2T
         mG3oGP8lnVH27VvqQ5Z4a+zofYk7NtLCfGdzfIyk/mhQKdDwZtBV39xeWvEnlggbZMuK
         dXOQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=5+KErOVOO3puPIHf0zTxo10UMRiowm4yep6DYJ72394=;
        b=WthxHK2KRyqOcsGoIa83mia5+svoLn+Ju9mnio7y2mdS65x06ysgXEK25CMA+EhHbw
         +7jsEJiJwXmM6NpK/utioj+hIh7K1eW4dLFxqykMlQI/1h0tdIjNG2JAWFWPV/I58b+d
         zZ3vzGUHyoGslOnwf5cDXdbgIF9waNjcAFvGTgelwfvF/Jn4ie4BW4kBH6MIIbwSebSn
         xYAhXWbYNwbb1knueJhVeLhRe9bU+93SJo8daCJ1XVcoST6waZKxeKyQrcKbV6NK3ktL
         Boo0mMVbAstoxZMjU2GDo3AD+OWWUg2ILwyHM6fZJElQT0gfggF/Azj4G2mdMn/6QKTH
         dR3A==
X-Gm-Message-State: AElRT7GNKs6Yv2F5Fk0OvMYj8qXsevFKomljgPE2U/SzsztZx5XmGMTh
	kXdIHSKoMfFSuNcxFPb57bqx0IQgemfDug+YeomkAw==
X-Google-Smtp-Source: AG47ELtZ/JOJmFVjLMbXIx0Dz5u4p8Ao0Ws7WlFn2nemiNdoNyy0EcYiW0UdiSC27KlPv6XWrgPPFanu3mCVSoh0dW8=
X-Received: by 10.200.3.224 with SMTP id z32mr44750251qtg.119.1520596465003;
 Fri, 09 Mar 2018 03:54:25 -0800 (PST)
MIME-Version: 1.0
Received: by 10.12.146.39 with HTTP; Fri, 9 Mar 2018 03:54:04 -0800 (PST)
From: Rafael Cossovan <navossoc@gmail.com>
Date: Fri, 9 Mar 2018 08:54:04 -0300
Message-ID: <CADmvPVp1C9RhSbW36rfDmJp1P6MUC+B7wErdzC=3cijdrG84BA@mail.gmail.com>
Subject: oi oi oi
To: teste2@revenda.email
Content-Type: multipart/alternative; boundary="f4030437a1dc24afcb0566f97453"
X-Rspamd-Queue-Id: 1A626B5B
X-Rspamd-Server: mail-nyc3.revenda.email
X-Spam-Status: No, score=0.40
X-Spamd-Result: default: False [0.40 / 20.00]
 RCVD_COUNT_ONE(0.00)[3]
 RCVD_NO_TLS_LAST(0.00)[]
 FROM_HAS_DN(0.00)[]
 MIME_GOOD(-0.10)[multipart/alternative,text/plain]
 RCPT_COUNT_ONE(0.00)[1]
 TO_MATCH_ENVRCPT_ALL(0.00)[]
 FROM_EQ_ENVFROM(0.00)[]
 ARC_NA(0.00)[]
 TO_DN_NONE(0.00)[]
 PREVIOUSLY_DELIVERED(0.00)[teste2@revenda.email]
 R_PARTS_DIFFER(0.50)[100.0%]

--f4030437a1dc24afcb0566f97453
Content-Type: text/plain; charset="UTF-8"

erro?

--f4030437a1dc24afcb0566f97453
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">erro?</div>

--f4030437a1dc24afcb0566f97453--```

**Comment by hardware** [comment]
```
Return-Path: <xxxxxxxxxxxxx@gmail.com>
Delivered-To: contact@meshup.net
Received: from mail.meshup.net
	by mail.meshup.net (Dovecot) with LMTP id 1EXdFtvDolpTIAAAlGKyKw
	for <contact@meshup.net>; Fri, 09 Mar 2018 17:26:51 +0000
Authentication-Results: mail.meshup.net; dmarc=pass policy=none header.from=gmail.com; dkim=pass header.d=gmail.com; spf=pass smtp.mailfrom=xxxxxxxxxxxxx@gmail.com
Received: from mail-oi0-f44.google.com (mail-oi0-f44.google.com [209.85.218.44])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail.meshup.net (Postfix) with ESMTPS id A4EEC261568
	for <contact@meshup.net>; Fri,  9 Mar 2018 17:26:50 +0000 (UTC)
Received: by mail-oi0-f44.google.com with SMTP id u73so7525029oie.3
        for <contact@meshup.net>; Fri, 09 Mar 2018 09:26:50 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=m4e+dzA7RopS1WGxh5RfZ95P9rmGxG5oO2o6jZNJnUw=;
        b=U00aWnPG6zPViPEfLZb46xul7z/dxJjwc7kTobCZ+XTnR2/6E1LTAEX+JjP4GAS2fA
         nWx4fnZkQtG7QTLX4ny5sf3Ygo5VNYVt1y0fbBcf1tOyYBw67bjxZMwRRt86COPtCIjB
         QixEqzsS+HIawX6hfBAyPVsxU4mmRqLm7eKml9O8c+JlmbezE2uuoIWrG+Y6bhFonZ97
         nic7dyTypJVUWMTARF16w0dA+PU/wY1lwQZvZfMcHSAA91GoPKL/72Rozm3UeNdOP/kd
         20iKO0MNUaJGwbapcGpLE1a8HKyjbM5xoZcsx3xWxPgj+4eKgMH/KiLHWJtOKhvHi+L7
         N/8A==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=m4e+dzA7RopS1WGxh5RfZ95P9rmGxG5oO2o6jZNJnUw=;
        b=i/582wqdtT0tT/YT3VPIJbEzelMikipRuJG32P3mO1H3WSZqliG56FF6UdYg31o+ib
         +UEMRFQrtnNPW/llnt71jBz1weLmI3uQcYFXsopyDPZRJ9R4sCnTPXR0Wju3VYIf4lG6
         T63jEM2PxQYSXYvJd1LleYmsPSjeM1LIMwazwoaO8ZC61KtS9uCtlgs8J81579YBwIUE
         n64g6rDfonvLf5EfUOc9WrO6ZqY699NMc65LhpiJ6yVXSnryI4oYtQT2Nh41vI+Qid39
         CjskjZ7dgdkyBIMln2MYB/PlDW0ZZJN/O+h7dihir5/IewPtcqvS+ZiMY6Le13fEMR4g
         F39Q==
X-Gm-Message-State: AElRT7FpPzWMrKNEAvtahcRxprG6hRyt5kGyLdknljrh8+1gBi3TX6bO
	AKXXj78E26VvSNv3gZzKTGmHmAFCMSz8Zzc3chRn1QwV
X-Google-Smtp-Source: AG47ELv5NKM7Hq+Y/FAMVvmHdKOram0YKd/T79JxKG76QEv4TxA4he1S+zqRwdLGa8Qzj67f7eFCFsIouqDcLggrAxI=
X-Received: by 10.202.166.15 with SMTP id p15mr18883395oie.149.1520616408459;
 Fri, 09 Mar 2018 09:26:48 -0800 (PST)
MIME-Version: 1.0
Received: by 10.157.20.234 with HTTP; Fri, 9 Mar 2018 09:26:48 -0800 (PST)
From: John Doe <xxxxxxxxxxxxx@gmail.com>
Date: Fri, 9 Mar 2018 18:26:48 +0100
Message-ID: <CA+af=_o3t+S52EbdMH6T24KZ6_DLa5QzOQ-uNeQ-3_c7zbtuYA@mail.gmail.com>
Subject: test
To: contact@meshup.net
Content-Type: multipart/alternative; boundary="001a1144f150ddadc10566fe18cb"
X-Rspamd-Queue-Id: A4EEC261568
X-Rspamd-Server: mail.meshup.net
X-Spam-Status: No, score=-0.75
X-Spamd-Result: default: False [-0.75 / 20.00]
 TO_DN_NONE(0.00)[]
 IP_SCORE(0.00)[ipnet: 209.85.128.0/17(-7.89), asn: 15169(-4.93), country: US(-0.92)]
 ARC_NA(0.00)[]
 R_SPF_ALLOW(-0.20)[+ip4:209.85.128.0/17]
 R_PARTS_DIFFER(0.50)[100.0%]
 ASN(0.00)[asn:15169, ipnet:209.85.128.0/17, country:US]
 MX_GOOD(-0.50)[cached: alt4.gmail-smtp-in.l.google.com]
 TAGGED_FROM(0.00)[]
 MIME_GOOD(-0.10)[multipart/alternative,text/plain]
 R_DKIM_ALLOW(-0.20)[gmail.com]
 FROM_HAS_DN(0.00)[]
 PREVIOUSLY_DELIVERED(0.00)[contact@meshup.net]
 TO_MATCH_ENVRCPT_ALL(0.00)[]
 RWL_MAILSPIKE_POSSIBLE(0.00)[44.218.85.209.rep.mailspike.net : 127.0.0.17]
 RCVD_NO_TLS_LAST(0.00)[]
 RCPT_COUNT_ONE(0.00)[1]
 FROM_EQ_ENVFROM(0.00)[]
 RCVD_COUNT_ONE(0.00)[3]
 DMARC_POLICY_ALLOW(-0.25)[gmail.com,none]
 RCVD_IN_DNSWL_NONE(0.00)[44.218.85.209.list.dnswl.org : 127.0.5.0]

--001a1144f150ddadc10566fe18cb
Content-Type: text/plain; charset="UTF-8"

test

--001a1144f150ddadc10566fe18cb
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">test<br></div>

--001a1144f150ddadc10566fe18cb--
```

**Comment by denji** [comment]
@hardware @navossoc @j-schumann Are you using Unbound/Swarm-mode or not?

**Comment by navossoc** [comment]
Yeah, I think we have found the problem.

```
mail-qt0-x230.google.com. 21599 IN AAAA 2607:f8b0:400d:c0d::230
mail-oi0-f44.google.com. 21599  IN      A       209.85.218.44
```

Since my hostname don't have an ipv4 address, "something" (probably docker) spoofed his ip address.

@denji 

I'm not using docker swarm and I'm using unbound as a local dns resolver.

**Comment by hardware** [comment]
> I'm not using docker swarm and I'm using unbound as a local dns resolver.

Same.

> Since my hostname don't have an ipv4 address, "something" (probably docker) spoofed his ip address.

And if you add an IPv4 address, does that correct the problem ?

**Comment by navossoc** [comment]
> And if you add an IPv4 address, does that correct the problem ?

Sorry, I expressed myself poorly up there.

Yes, my hostname does have a IPv4 and a IPv6 address, both reachable from internet.

What I was trying to say was:
The email server that gmail used to send me the email only has ipv6.
In your case, the server they used was one that only has ipv4.

**Comment by denji** [comment]
#### [Postfix stable release 3.3.0](http://www.postfix.org/announcements/postfix-3.3.0.html)

Interoperability: when Postfix IPv6 and IPv4 support are both enabled, the Postfix SMTP client will now relax MX preferences and attempt to schedule similar numbers of IPv4 and IPv6 addresses. This works around mail delivery problems when a destination announces lots of primary MX addresses on IPv6, but is reachable only over IPv4 (or vice versa). The new behavior is controlled with the `smtp_balance_mx_inet_protocols` parameter.

**Comment by hardware** [comment]
@navossoc ok so this is definitely an IPv6 issue with docker : https://github.com/hardware/mailserver/issues/43#issuecomment-330809473

**Comment by navossoc** [comment]
I had some progress with it...

![image](https://user-images.githubusercontent.com/2457338/37240055-40ba4fc4-2424-11e8-8fd5-799f79d40797.png)

For now (testing), I just dropped the `http_network` and recreated it with ipv6 enabled.

This was enough to assign a global ipv6 address to each container on that network.

Test 1: After that I tried to send another email and it **failed** miserable.

Test 2: I went to my DNS settings and changed my `AAAA` record to point to my `mailserver` container and **boom** it works properly.

So, it seems the problem is when docker forwards ipv6 packets from host to it's containers.
I'm not sure if this is a configuration issue with docker or it is a bug.

I'll investigate further at the weekend to see if I can get a better solution.

**Comment by j-schumann** [comment]
> @hardware @navossoc @j-schumann Are you using Unbound/Swarm-mode or not?

No, nothing like that, simple docker-compose on host reachable via IPv4/v6.

> I always get the correct IP address in rspamd WebUI field and not a local docker address. Maybe your problem is related to this issue : #43 - sometimes Postfix thinks 172.18.0.1 is the client_ip

It sure is, I opened that issue. The problem here is the bad support of IPv6 by Docker: I don't want to assign global IPv6 addresses to each container as @navossoc did because I want all traffic to go through the host to utilize one fail2ban instance for host + all containers, so I'm stuck with 172.18.0.1 showing up in the containers for all IPv6 requests as there is no immediate solution for this in https://github.com/moby/moby/issues/15086

My current question is: Why is rspamd even trying to sign **incoming** mails here, regardless if they are from a local IP or external? @vstakhov 
I would understand if he tried to sign mails being forwarded to another server, but this could happen in the sending process, not on receival?

**Comment by navossoc** [comment]
@j-schumann I gave up assigning a ipv6 for each container.
DigitalOcean provides only 16 ipv6 addresses 🤢 not a /64 block.

So, I created an `ipv6_network` and attached it only to the mailserver container. I also assigned a static ipv6 to it. Now I'm pointing my `AAAA` record to that container.
This will be my workaround until the ipv6 on docker gets better.

@hardware Postfix listen in both protocols, while dovecot only listen on ipv4.  
Do you want a PR for this or you will drop whole ipv6?

As for the original issue, I believe there is nothing to be done, except perhaps if rspamd can be configured otherwise where this would not happen.

Seems that `RMILTER` is obsolete. I need to check the docs later.

**Comment by hardware** [comment]
@navossoc  You can make a PR to drop IPv6 protocol for Postfix I think. To my knowledge, it is not useful that a program inside a container to listen in IPv6, docker manages IPv6 routing outside the container. You confirm that ?

**Comment by navossoc** [comment]
@hardware to be honest, I'm not a docker expert, so you may want a second opinion.
AFAIK docker is good enough with ipv4, but ipv6 support is kind 😐 yet.

If you application inside the container don't listen on ipv6, it can't be reached from the internet directly.
IMHO: To be safe is better to have both, since ipv6 is a trending and the support will get better eventually.

In my case, I'm planning to listen on both protocol and expose only the mailserver container to a ipv6 network.
So this way I can support users connecting with ipv4 and ipv6 to postfix/dovecot.

@j-schumann do you have any opinion on that?

**Comment by j-schumann** [comment]
@navossoc In my opinion every application running in a container that can be exposed via a port should support v4 & v6 for future compatibility. If it's only internal communication within the container it can be v4 only or via sockets.

**Comment by hardware** [comment]
> As for the original issue, I believe there is nothing to be done, except perhaps if rspamd can be configured otherwise where this would not happen.

The only relevant parameter that I see is to switch `sign_local` to `false` in rspamd configuration.

**Comment by navossoc** [comment]
@j-schumann I found this today:
https://github.com/robbertkl/docker-ipv6nat

Looks promising. I'll give a try later.
Maybe it solve our problems?

**Comment by j-schumann** [comment]
@navossoc looks interesting, one issue there said it can work with ufw, this is good. Don't know if this means it also works with fail2ban. Let me know how it goes!

**Comment by navossoc** [comment]
@j-schumann works fine and also seems to solve the problem.

I did the same thing as before, but this time I created a `ipv6nat_network` and assigned it to `mailserver`.
Then created the `docker-ipv6nat` container and reverted my `AAAA` record back to my main ipv6.

![image](https://user-images.githubusercontent.com/2457338/37463921-72460212-2835-11e8-837c-70078ad2dedf.png)

**Comment by j-schumann** [comment]
@navossoc I got it working with my docker-compose.yml, below is an extract, important is the listing of the custom network for each service, not only the mailserver or he can't communicate with MySQL etc.

This definitely solves the issue, mailserver and other containers now see the real IPv6 address.
But it still has the same problem as docker has by default: it ignores any other iptables rules from ufw or fail2ban, so i'll have to finally ditch ipv6nat, set ```DOCKER_OPTS="--iptables=false"``` and use custom rules.

docker-compose.yml, builds the mailserver with custom dockerfile in the "mailserver/" dir:
```
version: '2.1'
services:

  ipv6nat:
    image: robbertkl/ipv6nat
    restart: on-failure:5
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

 mailserver:
    build: mailserver/
    container_name: mailserver
    domainname: abc
    hostname: mail
    restart: on-failure:5
    cpu_shares: 256
    mem_limit: 500m
    networks:
      custom:
    security_opt:
      - apparmor:docker-default
    ports:
      - "25:25"
      - 143:143
      - 587:587
      - 993:993
      - 4190:4190
      - 11334:11334
    volumes:
      - /var/www/vhosts/abc/docker:/var/mail
      - /dev/log:/dev/log
    depends_on:
      - mariadb

  redismail:
    container_name: redismail
    image: redis
    command: redis-server --appendonly yes
    restart: on-failure:5
    network_mode: service:mailserver
    cpu_shares: 128
    mem_limit: 128m
    read_only: true
    security_opt:
      - apparmor:docker-default
    volumes:
      - /var/www/vhosts/abc/docker/redis:/data

networks:
  custom:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: fd00:dead:beef::/48
```

**Comment by hardware** [comment]
> @hardware this looks like a good fix to me. Let's wait @j-schumann reply with his results and I can help to draft a wiki page explaining how to setup ipv6. I just need someone later to review it.

No problem, your solution looks great.

**Comment by navossoc** [comment]
@hardware Yes, I can, probably wednesday I'll let you know about the results.

**Comment by navossoc** [comment]
@hardware I did some additional tests with the 1.7.x version, but I still need to use the ipv6nat to get the correct ipv6 address of the remote sender.

So in my opinion the best way to deal with this right now (until docker fixes it) is using the ipv6nat or assigning one ipv6 address to each container, besides that, everything else seems ok.

**Comment by sknight80** [comment]
@navossoc is that mean if I update my image to the latest version of "hardware/mailserver" I need to update the docker-compose file, too for ipv6?  Even though I don't use it?

**Comment by navossoc** [comment]
This ipv6 problem already exists in the previous version and continues in this new version as well.
(it's a docker issue to be more specific)

If you do not have any `AAAA` (ipv6) entry in your DNS, then you will not get any ipv6 connection and do not have to worry about it.

Just ignore this.

**Comment by hardware** [comment]
Someone can make a pull request to explain `ipv6nat` solution ?

**Comment by navossoc** [comment]
@hardware Sure, give me a few hours. I'll make it available tonight.

**Comment by navossoc** [comment]
I've created a draft of the pull request, it's enough to make it work.

Feel free to edit as you wish.
Let me know if you have any doubts.

[]'s

**Comment by hardware** [comment]
Solution : https://github.com/hardware/mailserver#ipv6-support (thanks @navossoc).
