### ISSUE TITLE
TLS is required, but was not offer by host

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#225]
#### Classification

* [X] Question
* [X] Deliverability issue

#### Reproducibility
_Please delete options that are not relevant._

* [x] Always

#### Docker information

Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 285
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-5-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.845GiB
Name: mail
ID: HDUV:3SOT:CFCZ:4UVN:G3MT:JTMK:LQXH:637M:FHT4:LL2F:ST7I:PVGU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:34a1474cc5ddf816352f7fe7f80a743c61d0f75d6ca3221205c6db5a1df894b4   8ae11245d35f        6 weeks ago         332MB

#### Description

Lorsque j’envoie mon mail vers le domaine chsf, exemple support.helpdesk@chsf.fr
J'ai une erreur sur l'envoi TLS is required, but was not offer by host
Est il possible de faire en sorte d'être moins restrictif au niveau des paramétrages du TLS et comment ?
Merci,

smtpd_helo_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unknown_recipient_domain, reject_non_fqdn_recipient, reject_unlisted_recipient, reject_rbl_client zen.spamhaus.org
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
smtpd_sender_restrictions = reject_non_fqdn_sender, reject_unknown_sender_domain, reject_sender_login_mismatch, reject_rhsbl_sender dbl.spamhaus.org

**Comment by hardware** [comment]
Ok, I see your problem. 

By default this docker image use an Opportunistic TLS encryption if no TLSA policy is found for the destination. But [chsf.fr](http://www.chsf.fr/) domain use a DNS **TLSA SMTP** record and have a valid DNSSEC zone :

```bash 
# dig +short MX chsf.fr

1 smtp01.chsf.fr.

# dig +short TLSA _25._tcp.smtp01.chsf.fr

3 1 1 DFDD38F1B38A70F075B1082366CF22CFCCCAD07ADEF51AF37B240922 268FD98A

# dig DS +trace +short chsf.fr | egrep '^DS'

DS 34458 7 2 2622FEBF86D8B06DB98611FBDCB564F7A96E95643F27B247433F9BAC 18786DA7 from server 194.0.9.1 in 13 ms.
```

Therefore, postfix applies a "Mandatory TLS encryption" automatically because TLSA records are in effect in a DNSSEC signed zone but [chsf.fr](http://www.chsf.fr/) mail server does not support TLS.

Contact [chsf.fr](http://www.chsf.fr/) IT administrator or use `smtp_tls_security_level=may` to use an opportunistic TLS encryption :

```ini
# /mnt/docker/mail/postfix/custom.conf

smtp_tls_security_level=may
```

http://www.postfix.org/postconf.5.html#smtp_tls_security_level

**Comment by tsedgwick1** [comment]
I used the option "may" for smtp_tls_security_level but It's the same as before.
I can't send any mail to chsf.fr domain and it's stuck in the mailq list.

2018-03-14T13:43:49.975571+01:00 mail postfix/smtp[8297]: 607B5CA01FA: to=<support.helpdesk@chsf.fr>, relay=smtp01.chsf.fr[90.83.106.187]:25, delay=0.75, delays=0.68/0.02/0.05/0, dsn=4.7.4, status=deferred (TLS is required, but was not offered by host smtp01.chsf.fr[90.83.106.187])

Maybe it's into the restrictions rules... I don't know
Do you see an other solution ?

**Comment by tsedgwick1** [comment]
Ok It worked! with "smtp_tls_security_level=may" when I restarted the container but I will contact the chsf.fr IT administrator fot that.
Thank you! This issue can be close.
