### ISSUE TITLE
Sieve Vacation + DKIM

### ISSUE THREAD

**Issue by navossoc** [hardware/mailserver#227]
#### Classification

* [X] Question
* [X] Deliverability issue

#### Reproducibility

* [X] Always

#### Docker information

default 1.1-stable images.

#### Description
When using the vacation feature, the outgoing mails are not dkim signed by the mailserver.

#### Steps to reproduce
1. Create a vacation filter.
2. Send a message to that user.
3. Look the reply message headers.

#### Expected results

All messages should be signed with DKIM, even if they are sent by dovecot/managesieve plugin.

#### Actual results

Message is not signed, this cause issues with DMARC...

#### Configuration (docker-compose.yml, traefik.toml...etc)

No extra configuration was done.

#### Related information

I found this related issue when I was looking for this problem.
https://github.com/Mailu/Mailu/issues/121

I don't have too much knowledge on postfix/dovecot/rspamd setup, so that was as far as I could get.

**Comment by denji** [comment]
https://github.com/hardware/mailserver/issues/54

**Comment by hardware** [comment]
This bug has been fixed with this commit : 227262bb58979d0462ffee9945b1d22e99be64de

**Comment by navossoc** [comment]
@hardware LGTM

I made a few tests and seems everything is working fine.

Have you tried with the alias? (I didn't, yet)

**Comment by hardware** [comment]
> Well, alias are not sending the vacation message

Fixed with 1c7b7fd.

**Comment by navossoc** [comment]
Really awesome, I'll check it tonight.

**Comment by navossoc** [comment]
Sorry for the late feedback, but yes, now it is working as intended.

Thanks.
