### ISSUE TITLE
Docker swarm / Kubernetes support 

### ISSUE THREAD

**Issue by measwel** [hardware/mailserver#231]
Does this image work in docker swarm mode?

**Comment by hardware** [comment]
Yes, some people use it with docker swarm or kubernetes. But no official support.

**Comment by tsedgwick1** [comment]
I'm also interested if someone have more informations on that.

**Comment by measwel** [comment]
For the time being I chose to implement my mail server with iredmail. As long as the server isn't under heavy load and does little more, it should work most of the time *GRIN*.

**Comment by hardware** [comment]
What do you want to know about docker swarm ? As [rancher support](https://github.com/hardware/mailserver/issues/83), I'm open merge any contribution to add documentation or make swarm support better. But I don't have enough time to maintain my self all variants (Vanilla, Rancher, Swarm, K8s...etc). So any maintainers for Swarm and K8s configurations are welcome.

> I'm also interested if someone have more informations on that.

ping @outbackdingo.

**Comment by tsedgwick1** [comment]
Personally, I want to use the Rancher solution. I think that in a production environment it is essential to have a backup server in case of error or system update with reboot of the main server but unfortunately I do not have enough knowledge in docker swarm to participate.

**Comment by outbackdingo** [comment]
@measwel why iredmail, its terrible, would have been better off with mailu ..... either way they all do basically the same thing, however support for things like kubernetes, swarm, rancher do somewhat lack here in mailserver ...  mailu actually runs on rancher and kubernetes. that being said there is nothing that stops or prevents someone from running mailserver in a stack environment other then someone properly putting together the right compose config for it. of all the stacks well ranchert is the easiest to deploy on as it uses standard docker-compose files, k8s and mesos however use different yaml syntax. I guess the best bet honestly would be to poll the community using mailserver and see who has actually successfully deployed mailserver on what stacks and then go from there.

**Comment by hardware** [comment]
> kubernetes, swarm, rancher do somewhat lack here in mailserver

hardware/mailserver works with Rancher : https://github.com/hardware/mailserver-rancher

> There is nothing that stops or prevents someone from running hardware/mailserver in a stack environment other then someone properly putting together the right compose config for it.

Ok, good to know :)

As previously said, any contributors are welcome to add some documentation for Swarm and K8s environments.

**Comment by bjrnio** [comment]
> There is nothing that stops or prevents someone from running hardware/mailserver in a stack environment other then someone properly putting together the right compose config for it.

I second this.

**Comment by nsmith5** [comment]
Currently working on deploying this on my personal Kubernetes cluster. I'll keep note of what I do and try to document the process for others afterwards. 

By the way, the fact that this container does mount the docker socket is very refreshing. Thanks for all the great work here. I really appreciate it.

**Comment by hardware** [comment]
@nsmith5 Your contribution is welcome.
