### ISSUE TITLE
s6-svc: fatal: something is wrong with syslogd/supervise directory

### ISSUE THREAD

**Issue by laimoncijus** [hardware/mailserver#233]
#### Classification

* [X] Question

#### Reproducibility

* [X] Always

#### Description
Can it be that mailserver logs are somehow broken for the latest 1.1-stable build?

#### Steps to reproduce
1. `docker pull hardware/mailserver:1.1-stable`
2. _create a container_
3. `docker start mailserver`
4. `docker logs -f mailserver`

#### Expected results

Seeing postfix logs about incoming emails, etc.

#### Actual results

Logs entries from starting the container:

> <..>
> [INFO] ManageSieve protocol is enabled
> [INFO] DKIM/ARC signing is enabled
> [INFO] Greylisting policy is enabled
> [INFO] Ratelimiting policy is enabled
> [INFO] POP3 protocol is disabled
> [INFO] Unbound DNS resolver is enabled
> [INFO] clamav-unofficial-sigs is disabled (user configuration not found)
> s6-svc: fatal: something is wrong with the /services/rsyslogd/supervise directory. errno reported: No such file or directory

After this point no logs are showing up at all...

**Comment by hardware** [comment]
Can you try with `1.1-stable-fallback` ?

I can't reproduce your problem on my end. s6 seems unable to create the `supervise` directory needed to launch and monitor rsyslogd's process, which explain why no logs are showing up.

**Comment by laimoncijus** [comment]
With `1.1-stable-fallback` it seems to be working properly, I can see logs from postfix and dovecot.

What is the difference between `1.1-stable` and `1.1-stable-fallback`?

**Comment by hardware** [comment]
> What is the difference between 1.1-stable and 1.1-stable-fallback ?

Both `1.1-stable` and `1.1-stable-fallback` use the same git branch ([v1.1-stable](https://github.com/hardware/mailserver/commits/v1.1-stable)). But `1.1-stable`  is built weekly and `1.1-stable-fallback` is built monthly. The fallback tag can be used when the main tag is broken (unlikely).

 * **2018-03-31T22:00:04 UTC** - Last stable fallback build : https://hub.docker.com/r/hardware/mailserver/builds/bbimyvlo2vjytp7ywvvacmm/

* **2018-04-08T10:05:03 UTC** - Last stable build : 
https://hub.docker.com/r/hardware/mailserver/builds/bkavbywp5fejnvmsjuun3vh/

* Between this two builds, no change have been made as you can see here : 
https://github.com/hardware/mailserver/commits/v1.1-stable

* Same for the parent docker image (stable tag last update : 18 days ago)  : 
https://hub.docker.com/r/hardware/debian-mail-overlay/tags/

Can you build the latest stable image manually and try again ?

```
git clone -b v1.1-stable --single-branch --depth 1 https://github.com/hardware/mailserver.git 
docker build --no-cache -t hardware/mailserver:1.1-stable-test mailserver/
```

```yml
services:
  mailserver:
    image: hardware/mailserver:1.1-stable-test
```

Containers are immutable but that does not exclude any time-specific build issue or someting like that.

**Comment by laimoncijus** [comment]
I have tried building the image myself (according to your provided instructions) and it is working properly as well... No idea why the official build is causing issues...

**Comment by hardware** [comment]
Yeah, it's strange. I have rebuilt the stable image on docker hub, can you retry please ?

**Comment by laimoncijus** [comment]
The latest stable build is also working as expected. I assume it was temporary issue, which is solved now.

Thanks for taking a look!
