### ISSUE TITLE
Lost connection with remote mail server

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#234]
#### Classification
* [x] Deliverability issue

#### Reproducibility
* [X] Sometimes

#### Description

1. Lorsqu'un mail est envoyé depuis l'une de nos plateforme avec l'adresse no-reply au domaine transal.bzh, il arrive parfois que le message n'est pas transmis au destinataire et reste en file d'attente.

Le message d'erreur qui est affiché dans les logs :

```
F1C9BCA020B    66234 Fri Apr  6 16:05:29  no-reply@histalim.com
(lost connection with mailtr.transal.bzh[90.102.106.125] while sending end of data -- message may be sent more than once) chimie@transal.bzh ybirien@transal.bzh
```

2. J'ai un message légèrement différent pour un autre domaine, je sais pas si c'est lié...

```
6DC83CA0145  2759594 Fri Apr  6 14:58:40  alefrancois@histalim.com
(lost connection with mail.efty.com[159.8.40.50] while receiving the initial server greeting) jean-yves.deslandes@horama.com`
```

En forçant l'envoi avec postqueue -f ça ne marche toujours pas.

Mon fichier main.cf : https://paste.mondedie.fr/?0dd01e999c6d8486#u/QEMstqJJ8PBq9jfh9GWcEKE5KnOEKn4ErjEPhZE5Y=

Auriez vous une solution a mon problème ?

Merci d'avance.

**Comment by hardware** [comment]
Same as : https://github.com/hardware/mailserver/issues/195, solution : https://github.com/hardware/mailserver/issues/195#issuecomment-346336521
