### ISSUE TITLE
Connect with Rainloop

### ISSUE THREAD

**Issue by ricardollerenad** [hardware/mailserver#235]
I cant connect to rainloop, it throw me the next error: "stream_socket_client() :php_network_getaddresses error" when i try to connect with postfix

**Comment by Hydrog3n** [comment]
Hey @ricardollerenad can't you paste your conf here ?

**Comment by hardware** [comment]
Please post a screenshot of your domain configuration in rainloop and your docker-compose.yml.

This should works with the default docker-compose.yml :
https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration#smtpimap-configuration-
