### ISSUE TITLE
Nodemailer : 454 4.7.0 TLS not available due to local problem

### ISSUE THREAD

**Issue by measwel** [hardware/mailserver#236]
I keep getting this error when connecting to postfix from nodemailer:
Error: Error upgrading connection with STARTTLS: 454 4.7.0 TLS not available due to local problem

However, there is no problem connecting and sending email with email client. Also diagnostic tools show no tls errors - all seems fine. The only thing I notice is that diagnostics report tls v 1.2 while the error mentiones 4.7.0 TLS. Is this a version number?

I would appreciate someone to help me with this issue.

**Comment by hardware** [comment]
>  Is this a version number ?

No, it's the postfix SMTP error `454 4.7.0 TLS not available due to local problem`.

Can you share your nodemailer configuration ? Example :

```javascript
let transporter = nodemailer.createTransport({
    host: 'mail.domain.tld',
    port: 587,
    secure: false, // upgrade later with STARTTLS
    auth: {
        user: 'username@domain.tld',
        pass: 'password'
    }
});
```

I also need your container logs when the mail is sent with nodemailer.

```
docker logs -f mailserver
```

What is your of Node.js version ? I suspect a problem occurring during TLS hanshake between the Node TLS library and the mail server OpenSSL library.

**Comment by measwel** [comment]
Hi hardware,

Your answer brought me closer to the solution. The transporter configuration seems wrong. I must go offline now, but will get back with an update later.

**Comment by hardware** [comment]
I can not help you without container logs and nodemailer configuration.

**Comment by measwel** [comment]
Its okay hardware. Thank you for you help. I solved the problem.

**Comment by dkim-95112** [comment]
How did u solve the problem ?

**Comment by measwel** [comment]
By making sure the transporter configuration is correct.
