### ISSUE TITLE
PANIC: unprotected error in call to Lua API

### ISSUE THREAD

**Issue by jodumont** [hardware/mailserver#250]
#### Classification
* [X] Question
* [x] Deliverability issue

#### Reproducibility
* [X] Always

#### Docker information
docker info
```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
Kernel Version: 4.9.65-1-hardened
Operating System: Alpine Linux v3.7
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.949GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false
```

docker images hardware/mailserver --digests --filter "dangling=false"
```
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:b930736623fc35668a6ccd7d4e736c5826446c2683841351672f53752579e6e1   7a6cc949cfd7        3 days ago          363MB
```
#### Description
I think I did something wrong but I can't figure what
the Rspamd password is define in .env even before the first run `docker-compose up -d`
I didn't edit the docker-compose.yml
- Let's encrypt generated all certificate even for spam.domain.tld
- but when I go on https://spam.domain.tld it's always a **Bad Gateway**
- All the rest works perfectly aka configured, up and gain access : traefik, postfixadmin, rainloop
- Traefik show 4backend and 4frontend up

#### Expected results
Being able to login into rspamd when I go to https://spam.domain.tld

#### Actual results
Bad Gateway

#### Debugging information

docker logs mailserver|grep spam
```
PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
2018-06-06T19:22:45.417052+00:00 mail root: s6-supervise : rspamd has restarted too many times (permanent failure)
```

#### Configuration (docker-compose.yml, traefik.toml...etc)

**traefik.toml**
```
defaultEntryPoints = ["https","http"]

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  users = ["admin:password"]

[acme]
email = "postmaster@domain.tld"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedbydefault = false
```

**Comment by hardware** [comment]
> PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
s6-supervise : rspamd has restarted too many times (permanent failure)

Rspamd seems unable to start. Do you use some kernel security module like grsecurity, SELinux or
AppArmor ?

**Comment by jodumont** [comment]
yes as the host is Alpine Linux v3.7 Kernel Version: 4.9.65-1-hardened
it come with grsecurity.

**Comment by hardware** [comment]
So that's why you have this issue. You can ask on the rspamd mailing list more information about that.

**Comment by jodumont** [comment]
sadly rspamd with mailcow works perfectly on the same server with the same config

**Comment by jodumont** [comment]
Don't worry and don't loose your time on this; I know running docker with GRCsecurity is an exception..
And anyway for me it's only the peak of the iceberg after, I'll start migrate it into a userspace than restrict by cgroup and ...

So if you want to follow me on this path be my guest
I'll be glad to collaborate on your mailserver

if not; I'll might come back to challenge you when mailcow will kick me out :P

**Comment by denji** [comment]
el7 `--optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'`

Alpine GCC hardened by default https://git.alpinelinux.org/cgit/aports/tree/main/gcc?h=3.7-stable
* 001_all_default-ssp-strong.patch
* 002_all_default-relro.patch
* 003_all_default-fortify-source.patch
