### ISSUE TITLE
Send mail with bash script using SMTP

### ISSUE THREAD

**Issue by Al3601** [hardware/mailserver#251]
#### Classification

* [X] Question

#### Description
Hi , 
I have a question (maybe dumb one), how i can send an email direcly from console ?
i can't figure how to send email with docker with my script 

`#!/bin/bash
MAX=80
EMAIL=alert@mydomain.tld
PART=sda1

USE=`df -h |grep $PART | awk '{ print $5 }' | cut -d'%' -f1`
if [ $USE -gt $MAX ]; then
  echo "Percent used: $USE" | mail -s "Espace disque insuffisant" $EMAIL
fi`

Thank you

**Comment by hardware** [comment]
You can use MSMTP or SSMTP.

https://github.com/hardware/mailserver/issues/162

**Comment by Al3601** [comment]
Thank you ! 

installed MSMTP and i work great!

here the config you need to get it work with mailserver ;

nano ~/.msmtprc

```
account default
host mail.domain.tld
port 587
from system@mail.domain.tld
tls on
tls_certcheck on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
auth on
user system@mail.domain.tld
password XXXXXXXXXX
account default: default
```
chmod 600 ~/.msmtprc

then send mail with;

printf "Subject:Hello\n,This is message" | msmtp -a default test@anydomain.tld

(printf better than echo, to avoid spam reject 500)
