### ISSUE TITLE
Fetchmail seems to be giving errors 

### ISSUE THREAD

**Issue by cypriotxx** [hardware/mailserver#252]
mailserver      | 2018-06-08T19:30:46.592175+00:00 mail fetchmail[672]:  not flushed
mailserver      | 2018-06-08T19:30:46.595508+00:00 mail postfix/smtpd[673]: 915FF130C0142: client=localhost[127.0.0.1]
mailserver      | 2018-06-08T19:30:46.636064+00:00 mail postfix/cleanup[677]: 915FF130C0142: message-id=<544723.24735.qm@web111618.mail.gq1.yahoo.com>
mailserver      | 2018-06-08T19:30:46.638689+00:00 mail postfix/cleanup[677]: 915FF130C0142: milter-reject: END-OF-MESSAGE from localhost[127.0.0.1]: 4.7.1 Ratelimit \"to\" exceeded; from=<willettaleary7117bjxk@yahoo.com> to=<mails@mails.net> proto=ESMTP helo=<mail.mails.net>
mailserver      | 2018-06-08T19:30:46.638885+00:00 mail fetchmail[672]: reading message mails@able.zapto.org@192.168.1.36:43 of 117321 (2907 header octets) (2067 body octets) (log message incomplete)
mailserver      | 2018-06-08T19:30:46.638892+00:00 mail fetchmail[672]: SMTP error: 451 4.7.1 Ratelimit \"to\" exceeded
mailserver      | 2018-06-08T19:30:47.639025+00:00 mail fetchmail[672]:  not flushed
mailserver      | 2018-06-08T19:30:48.640959+00:00 mail postfix/smtpd[673]: 9C788130C0142: client=localhost[127.0.0.1]
mailserver      | 2018-06-08T19:30:50.642987+00:00 mail postfix/cleanup[677]: 9C788130C0142: message-id=<20786.1264637635908.JavaMail.admin@172.20.60.23>
mailserver      | 2018-06-08T19:30:50.959700+00:00 mail postfix/cleanup[677]: 9C788130C0142: milter-reject: END-OF-MESSAGE from localhost[127.0.0.1]: 4.7.1 Ratelimit \"to\" exceeded; from=<tradealert@service.alibaba.com> to=<mails@mails.net> proto=ESMTP helo=<mail.mails.net>
mailserver      | 2018-06-08T19:30:51.959991+00:00 mail fetchmail[672]: reading message mails@able.zapto.org@192.168.1.36:44 of 117321 (1716 header octets) (69579 body octets) (log message incomplete)
mailserver      | 2018-06-08T19:30:51.959998+00:00 mail fetchmail[672]: SMTP error: 451 4.7.1 Ratelimit \"to\" exceeded
mailserver      | 2018-06-08T19:30:52.960170+00:00 mail fetchmail[672]:  not flushed

**Comment by denji** [comment]
https://github.com/hardware/mailserver/blob/master/rootfs/etc/rspamd/local.d/ratelimit.conf#L3

**Comment by cypriotxx** [comment]
thank you so much

**Comment by cypriotxx** [comment]
i have try to find this file but i failed , it is not under /dockers/volumes/mail/rspamd

under here only
rspamd_dynamic 
 rspamd.rrd  
rspamd.sock=  
stats.ucl  
symbols.cache

what do i do to teach this or change this settings to increase the numbers ,.

**Comment by hardware** [comment]
**1.** You can customize your ratelimit settings by creating an override ratelimit config file like this :

```yml
mailserver:
  volumes:
      - ${VOLUMES_ROOT_PATH}/rspamd/ratelimit.conf:/etc/rspamd/override.d/ratelimit.conf
```

Or you can also disable the ratelimiting policy :

```yml
mailserver:
  environment:
      - DISABLE_RATELIMITING=true
```

**2.**

```yml
mailserver:
  environment:
      - WHITELIST_SPAM_ADDRESSES=test@example.com,another@domain.tld
```

**Comment by cypriotxx** [comment]
thank you so much ,

i know with getmail latest version we can say ALL MAIL and it would download all folders but seems with fetchmail thats not happening .. can i enter more than one in the remote folder box , i tried inbox,sent but didnt work maybe i should be writing that in different format ?

**Comment by DrMurx** [comment]
@hardware The `v1.0-legacy` branch used to have an internal smtpd on localhost:10025 which did bypass any spam filter (in fact, it was used for amavis to re-feed the scanned messages). Can't we just create an smtpd on 10025 again without any milter configuration so it doesn't pass rspamd?
