### ISSUE TITLE
RspamD settings not changing 

### ISSUE THREAD

**Issue by cypriotxx** [hardware/mailserver#253]
on the configuration menu , SPAM is stuck on 22 and not changing at all , coming back as 22 .. is there something else i should be doing ?

**Comment by 1n5aN1aC** [comment]
This sounds almost EXACTLY like the issue I had around half a year ago:

https://github.com/hardware/mailserver/issues/179

Read through especially my last comment there, but in my case, I'm guessing there was an `actions {` definition that was added wrongly from the web interface, and breaking it.  After re-generating that file, my problems were fixed.

**Comment by cypriotxx** [comment]
i have removed the file 
# cat rspamd_dynamic
[
    {
        "metric": "default",
        "actions": [
            {
                "name": "reject",
                "value": 44.0
            }
        ],
        "symbols": [

        ]
    }
which this was in it ,
and run the command again to restart the docker
docker-compose up -d

i am guessing thats the right way of doing it 
which didnt change anything for me

**Comment by hardware** [comment]
Same as #179

Please open an issue on rspamd project repo. This is not an issue with this docker image. You should avoid to change settings via Rspamd WebUI.
