### ISSUE TITLE
traefik        dashboard not showing 

### ISSUE THREAD

**Issue by cypriotxx** [hardware/mailserver#254]
rainloop ok
rspamd ok
postfix admin ok

Traefik dashboard showing not found
http://nimb.ws/RQIXKC

any suggestions pls

# docker-compose ps
    Name                  Command               State                                                                        Ports           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mailserver     run.sh                           Up      0.0.0.0:11334->11334/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:25->25/tcp, 0.0.0.0:4190->4190/tcp, 465/tcp, 0.0.0.0:587->587/tcp, 0.0.0.0:993->993/tcp
mariadb        docker-entrypoint.sh mysqld      Up      3306/tcp                                                                             
postfixadmin   tini -- run.sh                   Up      0.0.0.0:8888->8888/tcp                                                               
rainloop       run.sh                           Up      0.0.0.0:8889->8888/tcp                                                               
redis          docker-entrypoint.sh redis ...   Up      6379/tcp                                                                             
traefik        /entrypoint.sh traefik           Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by cypriotxx** [comment]
docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.07.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 3addd840653146c90a254301d6c3a663c7fd6429)
runc version: N/A (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
init version: 949e6fa
Kernel Version: 4.2.8
Operating System: QTS 4.3.4 (20180528)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: NASFFF243
ID: E7IT:WFTW:SRST:PDJK:UX2H:Y3BI:YMM5:TTJ5:VORB:RFO3:GK6W:3WAM
Docker Root Dir: /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 97
 Goroutines: 92
 System Time: 2018-06-10T14:44:13.665342819+01:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
[/share/CACHEDEV1_DATA/dockers] # docker images hardware/mailserver --digests --filter "dangling=false"
REPOSITORY            TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
hardware/mailserver   1.1-stable          sha256:b930736623fc35668a6ccd7d4e736c5826446c2683841351672f53752579e6e1   7a6cc949cfd7        7 days ago          363MB
hardware/mailserver   1.0-legacy          sha256:3237c1442ff5d1011a889782c89540c87f96e985a782a8f4fa4ff2f01852ee9e   c22f3fa27eef        4 months ago        234MB

**Comment by hardware** [comment]
Think before open an issue.
