### ISSUE TITLE
Problem with accessing rainloop

### ISSUE THREAD

**Issue by Cyber1000** [hardware/mailserver#258]
* [X] Question
* [X] Always

#### Description
Setup made from https://github.com/hardware/mailserver -> 1 - Prepare your environment
- No changes to docker-compose
- No changes to traefik.toml
- .env has MAILSERVER_DOMAIN, Passwords set, VOLUMES_ROOT_PATH is set to a different location than default

If I go to webmail.mydomain.tld I get a "Bad gateway", instead of rainloop site.

#### Steps to reproduce
1. Setup (see description)
2. docker-compose up -d
3. browse to https://webmail.mydomain.tld or https://webmail.mydomain.tld/?admin

#### Expected results
rainloop-admin-site

#### Actual results
"Bad gateway" message

#### Debugging information
That's my question more or less. Any idea how to investigate this further?
Traeffic-Dashboard and Postfixadmin are accessible without problem ...

Thanks,
Cyber1000

**Comment by hardware** [comment]
"Bad gateway" means that your rainloop container is unavailable. Add `LOG_TO_STDOUT` env variable :

```yml
rainloop:
    image: hardware/rainloop
    container_name: rainloop
    environment:
      - LOG_TO_STDOUT=true
```

Post the result of this command : `docker logs rainloop`

Try to access to Rainloop without Traefik :

```yml
rainloop:
    image: hardware/rainloop
    ports:
      - "8888:8888"
```

http://webmail.mydomain.tld:8888/ and http://webmail.mydomain.tld:8888/?admin

Switch Traefik to debug mode and post your logs...etc

> Any idea how to investigate this further ?

Without some logs and configuration file I can't help you.

**Comment by Cyber1000** [comment]
> docker logs rainloop
`nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2018/07/07 18:51:29 [emerg] 58#58: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)`
Repeats every few minutes
> docker exec rainloop ps aux
`PID   USER     TIME   COMMAND
    1 991        0:00 /bin/s6-svscan /services
   12 991        0:01 s6-supervise nginx
   13 991        0:00 s6-supervise php
   14 991        0:00 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.conf)
 1043 root       0:00 ps aux
`
> docker exec rainloop nc -vz 127.0.0.1:8888
Doesn't output anything
> http://webmail.mydomain.tld:8888/ 
With direct access to rainloop no result too, seems like rainloop container is running, but doesn't  do anything

**Comment by Cyber1000** [comment]
Deleting with "docker image rm hardware/rainloop" and recreating with "docker-compose up -d" didn't change anything.

Wanted to eliminate the possibility, that my image of rainloop has a problem or is too old (though only 1 -2 weeks old)

**Comment by navossoc** [comment]
Can you access http://mail.mydomain.tld?
If so, check the frontend and backends are properly linked.

> No changes to traefik.toml
Did you change the {{ EMAIL }} and {{ DOMAIN }} placeholders?

Also, is it http://spam.mydomain.tld working or it says bad gateway too?

[]'s

**Comment by hardware** [comment]
@Cyber1000 

This should fix your issue :

```yml
rainloop:
  environment:
    - UID=nginx
    - GID=nginx
```

**Comment by Cyber1000** [comment]
Looks far better with these settings, at least I get rainloop running. 
Running some tests today, but I'm confident, that I can close this issue.

Would be nice to have these settings in some kind of troubleshooting-section in wiki.

Thanks a lot, have a nice sunday.

**Comment by hardware** [comment]
You're right, I mentioned it [here](https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration#troubleshooting).

**Comment by Cyber1000** [comment]
Yes works as intented, I'm getting mail and I can read it, thanks again.
