### ISSUE TITLE
What do I need to backup from /mnt/docker to be save?

### ISSUE THREAD

**Issue by Cyber1000** [hardware/mailserver#259]
My question is what do I need to backup to be save, if system crashes or I need to go to another server.
- mail-Folder: Is there anything beside mail/postfix/spool/ and mail/dkim that is relevant? I don't think I need to restore clamav for example.
- postfix-mysql-db:  Is important in my opinion
- rainloop: Does rainloop itself contain anything or is all mail still in postfix?
- redis: Don't think that I need this backup
- traefik: perhaps the toml-file, but nothing that can't be recreated by hand.

I hope you get the point, I want to know what's the minimal set I need to backup.

Thanks!

**Comment by hardware** [comment]
Backup `/mnt/docker` entirely, "minimal set" is not viable way when you setup a backup system. Backup everything in /mnt/docker to keep a consistent state and futur proof solution. And use mysqldump for MariaDB databases dump.

**Comment by Cyber1000** [comment]
Ok I think that's the best way to go, I'm convinced.
Thanks again.
