### ISSUE TITLE
traefik EMAIL variable

### ISSUE THREAD

**Issue by atomtigerzoo** [hardware/mailserver#261]
#### Classification

* [X] Question
* [X] Documentation

#### Reproducibility

* [X] Not applicable

#### Description
I tried creating letsencrypt certificates with traefik according to the documentation and get errors with `Error creating new account :: not a valid e-mail address` from traefiks acme client.
I saw that there is a variable called [EMAIL in traefik.toml](https://github.com/hardware/mailserver/blob/5ec1de087fdefc6dc0ef86c45e4786705e587ddc/traefik.sample.toml#L21) but can't find it inside docker-compose.yml or .env.

Where is EMAIL set?

**Comment by hardware** [comment]
> Where is EMAIL set?

You must set your e-mail address in `traefik.toml`

`.env` is used to define environment variables to be used for variable substitution in your docker compose file, not for traefik.toml.

**Comment by atomtigerzoo** [comment]
So to clarify, both values [EMAIL](https://github.com/hardware/mailserver/blob/5ec1de087fdefc6dc0ef86c45e4786705e587ddc/traefik.sample.toml#L21) and [DOMAIN](https://github.com/hardware/mailserver/blob/5ec1de087fdefc6dc0ef86c45e4786705e587ddc/traefik.sample.toml#L31) have to be set manually in traefik.toml?

**Comment by navossoc** [comment]
@atomtigerzoo Yes

**Comment by atomtigerzoo** [comment]
Thank you - I will try and add this info to the documentation the next days if you like.
