### ISSUE TITLE
Allowing relay does not work as expected

### ISSUE THREAD

**Issue by atomtigerzoo** [hardware/mailserver#262]
#### Classification

* [X] Minor bug

#### Reproducibility

* [X] Always

#### Description

I want to allow IPs and ranges for relaying mails through the server.

#### Steps to reproduce
When I set the following `docker-compose.yml`:

    - RELAY_NETWORKS=xxx.xxx.xxx.xxx [2a01:4f8:xxxx:xxxx::]/64

Then `docker-compose down` and `docker-compose up -d`. The IP and the IPv6 range is now set in postfix config:

    mynetworks    = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 xxx.xxx.xxx.xxx [2a01:4f8:xxxx:xxxx::]/64

But when I try to send mails from the server with the given IP the logs yield:

    2018-07-11T17:25:25.485557+00:00 mail postfix/submission/smtpd[737]: NOQUEUE: reject: RCPT from unknown[2a01:4f8:xxxx:xxxx::13]: 554 5.7.1 <unknown[2a01:4f8:xxxx:xxxx::13]>: Client host rejected: Access denied; from=<> to=<someone@example.com> proto=ESMTP helo=<servername.example.com>

After trying multiple times I also found that I somehow need to set a custom value for postfix. So I did:

    smtpd_sender_restrictions = reject_non_fqdn_sender,reject_unknown_sender_domain,permit_mynetworks,reject_sender_login_mismatch,reject_rhsbl_sender dbl.spamhaus.org

Still not working.

I tried with port 587 and 465 because I want it to submit encrypted. Port 25 not used.

#### Expected results

Adding IPs or ranges to the config value should allow relaying.

#### Actual results

Relay access blocked.

**Comment by hardware** [comment]
The default configuration should works, you should check your client settings, because this is not a relaying issue. Your client seems not sasl authenticated.

**Comment by atomtigerzoo** [comment]
After a night of sleep and some thinking I got it down to two problems:
- reverse dns entry of the domain for ipv6 was not set 😞
- I did miss the enforcement of auth on port 587 (`smtpd_tls_auth_only = yes` in postfix's main.cf) which is the reason of above error (On my old mail server I did not enforce this hence my misconfigured exim could connect without a cert 🤪)

Issue fixed. All questions cleared for the moment ;) Thank you for your help!
