### ISSUE TITLE
Cannot send email, but i can receive them

### ISSUE THREAD

**Issue by Whisper40** [hardware/mailserver#274]
#### Classification
 [X ] Serious bug

#### Reproducibility
 [X] Always

#### Docker information
#####DOCKER INFO#######
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.9GiB
Name: vps567780
ID: Z2G5:XDKK:HYCZ:U64Z:XRUI:EF4F:FYYR:2W4I:FFGY:UH5H:SNO7:OHCH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

###OTHER###
hardware/mailserver   1.1-stable          sha256:c20a29aba7d28c6b31d23205277a0c7b8975de6d8642151974b34f6e43d16f44   b2859e0aaf00        30 hours ago        378MB

#### Description ENG ####
I'm new on Docker, but I managed to install docker with your image, there are no particular mistakes during the process, however, two resident problems:
1) The first is Traefix, it is simply not accessible here: https://mail.domain.tld/ 

2) And the second, it is impossible for me to send an e-mail, as much from Outlook as from PostFix, MailTester confirms the non reception of the e-mail and consequently I cannot test my note.

The reception of mail is it on the other hand functional !
Anyway thanks for this image that does its job.
I hope you have any idea where the bug came from.

####DESCRIPTION FR ####
Je suis nouveau sur Docker, mais j'ai réussi à installer docker avec ton image, il n'y à pas d'erreurs particulières durant le processus, cependant, deux problèmes résides:
1 ) Le premier est Traefix, il est tout simplement innaccessible ici :  https://mail.domain.tld/ 

2 ) Et le second, il m'est impossible d'envoyer un mail , autant depuis Outlook que depuis PostFix, MailTester confirme la non réception du mail et par conséquent je ne peut pas tester ma note.

La réception de mail est elle par contre fonctionnel !
En tout cas merci pour cette image qui fait son job ;) J'espère que tu à une idée d'ou viens le bug ;)

#### Steps to reproduce
1. Just Install
2. It's not working

#### Debugging information

2018-07-23T16:20:35.171141+00:00 mail dovecot: lmtp(629): Disconnect from local: Successful quit
2018-07-23T16:20:35.171503+00:00 mail postfix/qmgr[591]: 7D56E82BEA: removed
2018-07-23T16:23:55.311828+00:00 mail postfix/anvil[605]: statistics: max connection rate 4/60s for (submission:52.125.137.1) at Jul 23 16:19:00
2018-07-23T16:23:55.311853+00:00 mail postfix/anvil[605]: statistics: max connection count 1 for (submission:172.19.0.1) at Jul 23 16:18:06
2018-07-23T16:23:55.311870+00:00 mail postfix/anvil[605]: statistics: max cache size 3 at Jul 23 16:18:59
2018-07-23T16:37:17.669603+00:00 mail postfix/smtpd[630]: connect from unknown[172.19.0.2]
2018-07-23T16:37:17.703324+00:00 mail postfix/smtpd[630]: NOQUEUE: reject: RCPT from unknown[172.19.0.2]: 554 5.7.1 <web-m2mg8@mail-tester.com>: Relay access denied; from=<postfixadmin@sdedikool.me> to=<web-m2mg8@mail-tester.com> proto=ESMTP helo=<mail.sdedikool.me>              #############ICI################
2018-07-23T16:37:17.703990+00:00 mail postfix/smtpd[630]: warning: non-SMTP command from unknown[172.19.0.2]: To: web-m2mg8@mail-tester.com
2018-07-23T16:37:17.704388+00:00 mail postfix/smtpd[630]: disconnect from unknown[172.19.0.2] ehlo=1 mail=1 rcpt=0/1 data=0/1 unknown=0/1 commands=2/5

**Comment by hardware** [comment]
I need the full output of :

```
docker logs mailserver
```

**Comment by Whisper40** [comment]
[logs.txt](https://github.com/hardware/mailserver/files/2220610/logs.txt)
Logs here thanks

**Comment by Whisper40** [comment]
Hey, little update, i have reinstall all the system , so now traefix is working, i think the  problem was the cache.. yes really.. 

But the problem for sending email is the same as past..
I upload logs2 of this new installation.
[logs2.txt](https://github.com/hardware/mailserver/files/2224570/logs2.txt)

**Comment by hardware** [comment]
Il y a rien dans les logs qui me permet de savoir d'où vient le problème, en tout cas ça vient obligatoirement d'un problème de configuration à ton niveau, je dirais du côté du postfixadmin ou de docker.

L'erreur `Relay access denied` veut dire serveur mail refuse relayer les mails et il peut y avoir de multiples raisons. Quelqu'un a eu ce soucis dernièrement, ça venait de sa base de données. Il a décrit la solution ici : https://github.com/hardware/mailserver/issues/246#issuecomment-395158801

En espérant que ça puisse t'aider.
