### ISSUE TITLE
Fetchmail fails to deliver mails from a local sender

### ISSUE THREAD

**Issue by DrMurx** [hardware/mailserver#276]
#### Classification

* [x] Deliverability issue

#### Reproducibility

* [X] Always

#### Description

Fetchmail can't deliver fetched mails to postfix if those emails have `From:` address which belongs to a local mail account.

In this log, `sender@myserver` sends an email to `recipient@otherserver` which is recipient's official address; recipient has also a local mailbox on `myserver` and a fetchmail job pulls his emails from `otherserver`:

```
postfix/smtpd[5540]: NOQUEUE: reject: RCPT from localhost[127.0.0.1]: 553 5.7.1 <sender@myserver.xxx>: Sender address rejected: not logged in; from=<sender@myserver.xxx> to=<recipient@myserver.xxx> proto=ESMTP helo=<mx.myserver.xxx>
fetchmail[5616]: reading message recipient@pop3.otherserver.xxx:2 of 4 (14129 octets) (log message incomplete)
fetchmail[5616]: SMTP error: 553 5.7.1 <sender@myserver.xxx>: Sender address rejected: not logged in
```

This happens because of this setting:

`smtpd_sender_restrictions=reject_sender_login_mismatch`

#### Proposal

Sender restrictions should be dropped for fetchmail delivery. It would be best add another internal smtpd entry to `main.cf` with less restrictions, eg. on port `10025`.

To make this work, postfixadmin's fetchmail settings need `smtp localhost/10025` added to the `extra_options` field.

**Comment by hardware** [comment]
Thanks for the heads up, I will look into this issue.

**Comment by hardware** [comment]
> Sender restrictions should be dropped for fetchmail delivery. It would be best add another internal smtpd entry to main.cf with less restrictions, eg. on port 10025.

I think we can use zeyple's internal smtpd entry :

https://github.com/hardware/mailserver/blob/11f0ef63574ba06b685021137072a6e314486d21/rootfs/etc/postfix/master.cf#L61-L69

> To make this work, postfixadmin's fetchmail settings need smtp localhost/10025 added to the extra_options field.

```ini
# /postfixadmin/config.local.php

$CONF['fetchmail_extra_options'] = 'smtp localhost/10026';
```

But I have not found any mention of this in the documentation, are you sure about this syntax  ?

```
smtp host/port
```

http://www.fetchmail.info/fetchmail-man.html
[https://github.com/postfixadmin/postfixadmin/config.inc.php#L454-L461](https://github.com/postfixadmin/postfixadmin/blob/ba14535489c6169aea925ef0eeb7f72eb7ad3a2f/config.inc.php#L454-L461)
[https://github.com/postfixadmin/postfixadmin/model/FetchmailHandler.php#L40](https://github.com/postfixadmin/postfixadmin/blob/cdf3c9acb969126101f357307e233ad4945305b2/model/FetchmailHandler.php#L40)

**Comment by DrMurx** [comment]
> I think we can use zeyple's internal smtpd entry

I currently do that, and I haven't had any issues so far. However I'm a strong advocate of the unix philosophy "Do one thing and do it well". Future changes on zeyple's internal port might again break fetchmail delivery because it's then used for multiple purposes.

> are you sure about this syntax

Yip. It's even documented on http://www.fetchmail.info/fetchmail-man.html with the `-S|--smtphost` option:

> Each hostname may have a port number following the host name.  The port number is separated from the host name by a slash; the default port is "smtp".

**Comment by hardware** [comment]
I had seen the `smtphost` in the [legal user options](http://www.fetchmail.info/fetchmail-man.html#34) but `smtp` works too.

```
-S <hosts> \| --smtphost <hosts>
--
  | (Keyword: smtp[host]) 
```

> Future changes on zeyple's internal port might again break fetchmail delivery because it's then used for multiple purposes.

Fair point. Sounds good to me.

**Comment by hardware** [comment]
@DrMurx Looks good to you ?

**Comment by hardware** [comment]
Because you can't indent an here docs code block in bash and i hate to have multiple ident style in the same level, so everything in the else block is un-indented, like lines 667-686 in the same script ^^
