### ISSUE TITLE
Question: sending mails from host

### ISSUE THREAD

**Issue by Cyber1000** [hardware/mailserver#278]
Hi,

May be a strange question, but I'll try it anyway:
- before this docker image, I had postfix directly on my host and every mail (mailx or linux internal mail like hdd failures and cron-errors) got delivered to a mail-address.
- Now postfix is within docker and mailx or system internal mails on host are not forwarded (I know that this is obvious)
- Is there a way to accomplish this easily to get mails (at least the system internal) forwarded to docker-container? postfix on host wouldn't work, since it uses the same ports as within docker and I also want to avoid a large difficult setup on host-side.
- Perhaps someone had a similar problem

Thanks for any ideas!
Cyber1000

**Comment by 1n5aN1aC** [comment]
I personally have created a mail account for cron (root) to send emails.  (within the dockers)

Then I use [msmtp](https://marlam.de/msmtp/) to handle the delivery for root emails.

So technically it's SMTP'ing into the docker with a real account to send emails.  a bit different than how cron/root emails normally is set up, but it's working great for me!

**Comment by denji** [comment]
#162

**Comment by Cyber1000** [comment]
Ah seems that's the thing I was searching for. Thanks a lot, I' ll test within the next few days, report here and then close this issue.

Thanks again for your fast answers!

**Comment by Cyber1000** [comment]
works as expected and was very easy to setup. I use msmtp, my setup:
having 2 domains: 
- a "private" internal, not known outside, only used for system-messages, I wanted to deliver here
- a real public domain, where docker listens to, I use for "real" mail
- Both domains must have an entry in this docker postfix

Installed msmtp and msmtp-mta and created /etc/msmtprc:
> account default
> host [docker mailserver] # MX-Record-name, for example mail.domain.com
> auto_from on
> maildomain [private domain] # from address get's created for example as root@[private domain] 
> aliases /etc/aliases #useful to relay messages to another address
> syslog LOG_MAIL

/etc/aliases simple relays everything to a single private domain:
> default: root@[private domain]

You may have a more complex setup here.

private domain can have a own mailbox on docker postfix or relay to another address. I have relayed everything from private domain (with *) to a single address on my public domain. So every system message goes there.

Thanks again, was a very fast and effective solution!
