### ISSUE TITLE
MUA privacy audit service

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#281]
* https://www.emailprivacytester.com
  - [~`github/email-privacy-tester`~](https://github.com/mikecardwell/email-privacy-tester)
  - https://gitlab.com/mikecardwell/ept3

**Comment by hardware** [comment]
0 test pass with Thunderbird, Rainloop and K-9 Mail :muscle: 

![screenshot_20180810_220353](https://user-images.githubusercontent.com/327354/43978930-49f99d22-9ce9-11e8-9db4-7587343b3f6e.png)
