### ISSUE TITLE
CPU doesn't have SSSE3 instructions set required for hyperscan, disable it

### ISSUE THREAD

**Issue by Amine27** [hardware/mailserver#282]
#### Classification
_Please delete options that are not relevant._

* [X] Serious bug
* [X] Vulnerability

#### Reproducibility
_Please delete options that are not relevant._

* [X] Always

#### Description
Using the latest mailserver image, I can't access RSPAMD webui anymore (wrong password). Verifying the logs, I see:
`mailserver      | sed: -e expression #1, char 87: unterminated 's' command`
and:
```
mailserver      | controller; rspamd_controller_password_sane: your normal password is not encrypted, we str
ongly recommend to replace it with the encrypted one 
mailserver      | controller; rspamd_controller_password_sane: your enable password is not encrypted, we str
ongly recommend to replace it with the encrypted one
```
So, the password is not encrypted correctly. I tried to generate that password from inside the container:
```
docker exec -it mailserver /bin/bash
rspamadm pw --quiet --encrypt --type pbkdf2 --password "mypass"
```
The output is:
```
CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
$1$ge4ctt1u6xfaczn4xk3jp44darkc7mob$pb1foh7jgeiceunyhizijxewt853jx6x866jyd89r94h5yewjiiy

```
The first line which causes sed error. Therefore:
```
cat /etc/rspamd/local.d/worker-controller.inc
password = "<PASSWORD>";
enable_password = "<PASSWORD>";
```

The actual password is `<PASSWORD>` !
The problem of "CPU doesn't have SSSE3..." is reported [here](https://github.com/vstakhov/rspamd/issues/2327), but the proposed solution doesn't work for me.

Hope you can fix this ASAP.
Thank you.

**Comment by hardware** [comment]
I enabled hyperscan 1 month ago with [this commit](https://github.com/hardware/debian-mail-overlay/commit/7b6d6e9165c38fb2122f77018ee54bf045abc8ec#diff-3254677a7917c6c01f55212f86c57fbfR103).

> The problem of "CPU doesn't have SSSE3..." is reported here, but the proposed solution doesn't work for me.

This solution should work. How did you add `disable_hyperscan = true;` in `local.d/options.inc` ?

**Comment by navossoc** [comment]
Which CPU is that? SSE3 has more than 10 years.

**Comment by hardware** [comment]
@Amine27 Could you tell me if this command remove the warning ?

```bash
rspamadm pw --quiet --encrypt --type pbkdf2 --password "..." 2>/dev/null
```

First solution if the redirection works :

```bash
PASSWORD=$(rspamadm pw --quiet --encrypt --type pbkdf2 --password "${RSPAMD_PASSWORD}" 2>/dev/null)

if ! grep --quiet 'ssse3' /proc/cpuinfo; then
  echo "disable_hyperscan = true;" >> /etc/rspamd/local.d/options.inc
  echo "[INFO] Missing SSSE3 CPU instructions, hyperscan is disabled"
fi

sed -i "s|<PASSWORD>|${PASSWORD}|g" /etc/rspamd/local.d/worker-controller.inc
```

Second solution if the redirection can not work because the warning is print in stdout :

```bash
#!/bin/bash

PASSWORD=$(rspamadm pw --quiet --encrypt --type pbkdf2 --password "${RSPAMD_PASSWORD}")

if ! grep --quiet 'ssse3' /proc/cpuinfo; then
  PASSWORD=$($PASSWORD | sed -n 2p)
  echo "disable_hyperscan = true;" >> /etc/rspamd/local.d/options.inc
  echo "[INFO] Missing SSSE3 CPU instructions, hyperscan is disabled"
fi

sed -i "s|<PASSWORD>|${PASSWORD}|g" /etc/rspamd/local.d/worker-controller.inc
```

**Comment by denji** [comment]
Perhaps the use of `PRCE2` (JIT) instead of `PRCE` be more useful on systems where SSSE3 is not available hardware/debian-mail-overlay#3.

**Comment by Amine27** [comment]
Thank you @hardware for the proposed solutions.
The first one doesn't work because it prints always the two lines in stdout. The second one is working.

Anyway, I ended up by adding SSSE3 CPU feature to my KVM machine hosting the mailserver. And now no error message.

Thank you everyone :)

**Comment by hardware** [comment]
> Perhaps using PRCE2 (JIT) instead of PRCE will be more useful on systems where SSSE3 is not available 

But it would take 2 base images, one with hyperscan and another with PRCE2, it's not worth it.
