### ISSUE TITLE
Please document what's needed for backups

### ISSUE THREAD

**Issue by kenyee** [hardware/mailserver#287]
#### Classification
* [X] Documentation

#### Reproducibility

* [X] Not applicable

#### Description

Would be nice to have documentation on what directories have to be backed up besides everything under the /mnt/docker mount?  I don't think some of the SQL index files need to be?

Also, one other thing worth documenting is you should do a docker-compose logs mariadb when you first start up the container up so you can write down the randomly generated root password.  I didn't do that and had to reinstall because I wanted to change my DB User password and didn't realize it had to be changed in the DB....took a while to figure out that dovecot couldn't talk to mariadb because postfixadmin had no such  problems....

**Comment by hardware** [comment]
Backup /mnt/docker entirely, a "minimal set" is not viable way when you setup a backup system. Backup everything in /mnt/docker to keep a consistent state and futur proof solution for all your containers. And use mysqldump to make MariaDB databases dump.

> Also, one other thing worth documenting is you should do a docker-compose logs mariadb when you first start up the container up so you can write down the randomly generated root password.

Yes, you're right, I forgot to document that. Do you want to make a pull request ?

**Comment by navossoc** [comment]
If you using PostgreSQL you can use this to backup all your databases:

```docker exec -u postgres -w /tmp postgres pg_dumpall | gzip > ~/dump.sql.gz```

This will save `dump.sql.gz` on your host home folder.

[]'s

**Comment by kenyee** [comment]
Sounds good...I can do a first cut at a backup doc and you can tell me what I missed ;-)
It's sort of a question of minimal because stuff like the DB indexes don't need to be in your backup...and if there are any logs that end up in /mnt/docker, they shouldn't be backed up either.  You don't want to bloat your backups IMHO.  Postgresql DB dirs are also huge because they don't always get compacted.

I can do a PR to document the startup capture of the root password of mariadb as well...does that also have to be done for postgresql?
