### ISSUE TITLE
[Question] Autodelete for Trashed emails

### ISSUE THREAD

**Issue by sknight80** [hardware/mailserver#288]
#### Classification
* [X] Question

#### Reproducibility
* [X] Always

#### Description
Hi, I noticed that when I put an email to the trash folder after a couple of weeks the deleted email is actually deleted from the trash folder (in the server, too).  Is this a feature?  If so, how can I configure the max delete time (like delete an email if older than x days and if it is in the trash folder)

#### Steps to reproduce
1.  Move a month or 3-month-old email to the Trash folder from your Inbox
2. Wait for about a 5 days
3. Open your Trash folder

#### Expected results
The deleted email should be there.

#### Actual results
The old email is gone, deleted.

#### Debugging information
N/A, I did not saw any "delete" keyword in the log

#### Configuration (docker-compose.yml, traefik.toml...etc)
Same as what we have in the repo.

**Comment by hardware** [comment]
> Hi, I noticed that when I put an email to the trash folder after a couple of weeks the deleted email is actually deleted from the trash folder (in the server, too). Is this a feature?

Nope, this docker image **never auto expunge trash** or other mailboxes.

This can be done with [doveadm-expunge](https://wiki.dovecot.org/Tools/Doveadm/Expunge) but I do not use it. Your mua probably do this for you automagically.

**Comment by sknight80** [comment]
@hardware thank you. I will look at my email client.  I hope that is the case and not something else.
