### ISSUE TITLE
Impossible to send to yahoo email address

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#290]
#### Classification
_Please delete options that are not relevant._

* [X] Deliverability issue

#### Reproducibility

* [X] Always

#### Description

We can't send any email to yahoo. With GMAIL or Outlook there are no issue but we suspect Yahoo to block our mail. Do you have a solution for that ?

#### Actual results

host mx-aol.mail.gm0.yahoodns.net[98.136.101.116] said: 421
    Connection went away (in reply to MAIL FROM command)

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/issues/206
