### ISSUE TITLE
Sender address rejected: not owned by user

### ISSUE THREAD

**Issue by pepya2** [hardware/mailserver#292]
Hello, Everything works fine.. I am receiving emails, sending using Rainloop webmail works fine.. i have another docker container having php app, unfortunately sending mail from that container fails.. inspecting via docker container i found that `smtpd_relay_restrictions` applies.

I am sending mail via container that has domain added in - ADD_DOMAINS in docker-compose as seen below..
![t3](https://user-images.githubusercontent.com/25289859/44652176-ef325380-a9f3-11e8-958c-6d62914b1f73.png)

My postfix main.cf is as normal hardware/mailserver postfix..
sample..
![t4](https://user-images.githubusercontent.com/25289859/44652378-6d8ef580-a9f4-11e8-983e-7d97d8f4337e.png)

i used swaks to troubleshoot and see the error.. 
![t1](https://user-images.githubusercontent.com/25289859/44652460-98794980-a9f4-11e8-877c-59ec53aecb8b.png)

tried to another docker container i got the same..
![t2](https://user-images.githubusercontent.com/25289859/44652484-a6c76580-a9f4-11e8-8392-ac6e7d02fc30.png)

i removed `reject_non_fqdn_recipient`  in `smtpd_relay_restrictions` now i am getting 
```
<~* 553 5.7.1 <root@d4a806ed796c>: Sender address rejected: not owned by user support@domain.com
 ~> QUIT
<~  221 2.0.0 Bye
```

i think hardware/mailserver has everything setup.. may i get a help on how i can overcome these restriction.
Thank you so much.

**Comment by gkapkowski** [comment]
@pepya2 How did you solve this problem?
