### ISSUE TITLE
docker pull fails: manifest not found

### ISSUE THREAD

**Issue by cracker0dks** [hardware/mailserver#293]
I can't pull anymore. Problem:
```
docker pull hardware/mailserver
Using default tag: latest
Error response from daemon: manifest for hardware/mailserver:latest not found
```
Other images from docker hub working fine.
Thanks for help

**Comment by navossoc** [comment]
Hi, it's `1.1-latest`.

You can check the other tags here:
https://hub.docker.com/r/hardware/mailserver/tags/

**Comment by cracker0dks** [comment]
mmm I remember their was a :latest at some point.
thanks!

**Comment by hardware** [comment]
Don't use 1.1 version before to do this : https://github.com/hardware/mailserver/wiki/Migrating-from-1.0-stable-to-1.1-stable
