### ISSUE TITLE
Rainloop Plugin "postfixadmin-change-password" config Details Question

### ISSUE THREAD

**Issue by Yackip** [hardware/mailserver#294]
[X] Question

#### Reproducibility

[X] Always

#### Docker information
```
docker images hardware/mailserver --digests --filter "dangling=false"
hardware/mailserver   1.1-stable          xxx        4 weeks ago         378MB
```

#### Description
I wanted to make users able to change their password in Rainloop. but i don't exactly know what information i have to feed the postfixadmin plugin for Rainloop. 
I'm not shure about the encryption used and about the Table name/column names/
I figured out the user name and the DB password from the config files.

Thank's for the awesome Work !

Here is a screenshot:

[https://imgur.com/download/TNURHvW](url)

**Comment by navossoc** [comment]
@Yackip Are you using MariaDB?

If so, check this:
https://github.com/hardware/rainloop/issues/3#issuecomment-320059899

[]'s

**Comment by Yackip** [comment]
@navossoc How do i find that out? I used https://hub.docker.com/r/hardware/mailserver/ to set it up.
I see a mysql folder in /mnt⁩/⁨docker⁩/ but in the tutorial MariaDB is mentioned a couple of times

**Comment by navossoc** [comment]
@Yackip Yeah, the default is `mysql` (mariadb).

[]'s

**Comment by Yackip** [comment]
@navossoc Jep i used the "Environment variables" I got it up and running. Thank's a lot !
