### ISSUE TITLE
'ssse3' /proc/cpuinfo

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#295]
[This code](https://github.com/hardware/mailserver/blob/v1.1-stable/rootfs/usr/local/bin/run.sh#L650) always leads to breakage. In addition, the `PASSWORD` variable is not initialized.
Always `exit 1` inside qemu/KVM (`[ERROR] rspamadm pw : bad output`).
```sh
PASSWORD=$(rspamadm pw --quiet --encrypt --type pbkdf2 --password "${RSPAMD_PASSWORD}")

if ! grep --quiet 'ssse3' /proc/cpuinfo; then
  PASSWORD=$($PASSWORD | sed -n 2p) # <<<<<<<<
  echo "disable_hyperscan = true;" >> /etc/rspamd/local.d/options.inc
  echo "[INFO] Missing SSSE3 CPU instructions, hyperscan is disabled"
fi

if [ -z "$PASSWORD" ]; then
  echo "[ERROR] rspamadm pw : bad output"
  exit 1
fi
```

> [INFO] Unbound DNS resolver is disabled
> /usr/local/bin/run.sh: line 651: CPU: command not found
> [INFO] Missing SSSE3 CPU instructions, hyperscan is disabled
> [ERROR] rspamadm pw : bad output
> `exit 1`

In my case, only hack works
```sh
# Setting the controller password
PASSWORD=$(rspamadm pw --quiet --encrypt --type pbkdf2 --password "${RSPAMD_PASSWORD}" | grep -v SSSE3)
if ! grep --quiet 'ssse3' /proc/cpuinfo; then
  if ! grep --quiet 'disable_hyperscan' /etc/rspamd/local.d/options.inc; then
    echo "disable_hyperscan = true;" >> /etc/rspamd/local.d/options.inc
  fi
  echo "[INFO] Missing SSSE3 CPU instructions, hyperscan is disabled"
fi

if [ -z "$PASSWORD" ]; then
  echo "[ERROR] rspamadm pw : bad output"
  exit 1
fi
```

> [INFO] Unbound DNS resolver is disabled
> [INFO] Missing SSSE3 CPU instructions, hyperscan is disabled
> [INFO] clamav-unofficial-sigs is disabled (user configuration not found)
> ...

**Comment by denji** [comment]
@hardware stable version broken.

**Comment by hardware** [comment]
@denji LGFY with latest ? If yes, I will merge the changes on stable.

**Comment by denji** [comment]
I use PCRE2 without PCRE 1 and with the removed Hyperscan module.
I think it is necessary to add still check that hyperscan is present, `sed-n 2p` may still not work correctly if there is no Hyperscan.

**Comment by denji** [comment]
```sh
# Setting the controller password
PASSWORD=$(rspamadm pw --quiet --encrypt --type pbkdf2 --password "${RSPAMD_PASSWORD}" | grep -v SSSE3)
if ! grep --quiet 'ssse3' /proc/cpuinfo; then
  if ! grep --quiet 'disable_hyperscan' /etc/rspamd/local.d/options.inc; then
    echo "disable_hyperscan = true;" >> /etc/rspamd/local.d/options.inc
  fi
  echo "[INFO] Missing SSSE3 CPU instructions, hyperscan is disabled"
fi
```
