### ISSUE TITLE
Override postfix master configuration

### ISSUE THREAD

**Issue by bkraul** [hardware/mailserver#297]
Due to having residential internet service, I use a hassle-free SMTP service to receive mail, called ghetosmtp. I have set up my domain to route all mail sent to my domain through that server. The server in turn, communicates with my inhouse mail server to deliver the mail.

This works on a mail server in a standalone VPS machine I have. However, the mailserver docker install rejects the email as follows:

```
NOQUEUE: reject: RCPT from in1.ghettosmtp.com[104.237.130.186]: 554 5.7.1 <in1.ghettosmtp.com[104.237.130.186]>: Client host rejected: Access denied; from=<******@*****> to=<****@******> proto=ESMTP helo=<in1.ghettosmtp.com>
```
I have added the IP ```104.237.130.186``` to my list of RELAY_NETWORKS. However, this seems to have no effect, even after making sure the IP appears in /etc/postfix/main.cf.

I have been reading that this can be fixed by commenting out the line:
```
-o smtpd_client_restrictions=permit_sasl_authenticated,reject
```
in ```/etc/postfix/master.cf```. However, there seems to be no override functionality for items in ```master.cf```, only for ```main.cf```

Anyone have any idea how overcome this issue?

**Comment by bkraul** [comment]
UPDATE: So, what I ended up doing in the meantime was to override the ```master.cf``` file in my volumes section of the compose, and commenting out the ```smptd_client_restrictions``` lines as outlined above, and this seems to work. I am just wondering if there is a cleaner method to accomplish this.

**Comment by hardware** [comment]
Same as https://github.com/hardware/mailserver/issues/262

The default configuration should works, you should check your client settings, because this is not a relaying issue. Your client seems not sasl authenticated.

**Comment by bkraul** [comment]
@hardware No, it was not a relaying issue for me, but a client issue, as outlined above. Ultimately I secured a little better by re-adding the IP of my ghettosmtp server to my networks, and modifying the line in ```master.cf``` to:

``` -o smtpd_client_restrictions=permit_sasl_authenticated,permit_mynetworks,reject```

That way it is no longer open-ended. The thing with ghettosmtp is that it does not need authentication all it is doing is redirecting mail to my server from the outside on a different port, due to my ISP blocking port 25, so I know to accept it.

Since my issue is mostly resolved, and my oiriginal question had to do with trying to find out if there is a way to override settings in ```master.cf``` and there being none, I will go ahead and close my issue. Thanks for the feedback.

**Comment by hardware** [comment]
> The thing with ghettosmtp is that it does not need authentication all it is doing is redirecting mail to my server from the outside on a different port, due to my **ISP blocking port 25**

I understand now why you must use the submission port. 

> Since my issue is mostly resolved, and my oiriginal question had to do with trying to find out if there is a way to override settings in master.cf and there being none

You can use a custom `master.cf` with docker volumes.

```yml
volumes:
  - /path/to/your/custom-master.cf:/etc/postfix/master.cf
```

This method should not breaks anytime soon, but it could happen if I make conflits changes during container preparation (run.sh), you must keep this in mind.

**Comment by bkraul** [comment]
Yes, that is what I ended up doing, which is why I asked if there was a way to override ```master.cf``` settings in the same way ```main.cf``` can be overriden with ```custom.conf```

**Comment by hardware** [comment]
> I asked if there was a way to override master.cf settings in the same way main.cf can be overriden with custom.conf

Currently it is not possible, but you can implement that with `postconf -P` :

> With -P, edit the  master.cf  configuration  file,  and  add  or
              update  one  or  more  service  parameter  settings  (-o parame-
              ter=value settings) with new  values  as  specified  with  "ser-
              vice/type/parameter=value" on the postconf(1) command line.

http://www.postfix.org/postconf.1.html

Example :

```
postconf -P "submission/inet/permit_sasl_authenticated,permit_mynetworks,reject"
```

You can make all pull request if you want. Your script can parse a `custom-master.conf` with this format :

```
# /mnt/docker/mail/postfix/custom-master.conf

M|submission inet n       -       -       -       -       smtpd
P|submission/inet/smtpd_tls_security_level=may
P|submission/inet/smtpd_tls_ciphers=medium
P|submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,permit_mynetworks,reject
```

Each lines starting with **M** (service) go through `postconf -M` and each lines with **P** (parameter) go through `postconf -P`.  The value being obtained by splitting the line with the character `|`.

It's just an example, but it should work.

**Comment by hardware** [comment]
@bkraul do you plan to implement this feature and make a pull request ?

**Comment by bkraul** [comment]
@hardware while I am realitively familiar with postconf and bash scripting, I am still learning in terms of working with docker image configuration and scripting, so I don't think I'd be quite able to provide a good PR for this.

**Comment by hardware** [comment]
@bkraul you can now override postfix master configuration with `custom.conf` file like this :

```ini
# /mnt/docker/mail/postfix/custom.conf

P|submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,permit_mynetworks,reject
```

Others prefixes are available, more information here :

https://github.com/hardware/mailserver#override-postfix-configuration

For the moment, this feature is only available in `1.1-latest`  (more testing needed). Tell me if it suits your needs.

**Comment by bkraul** [comment]
@hardware You da man! Thank you for taking the time to do this.

**Comment by bkraul** [comment]
Reporting back. Updated container, set up the override lines in custom.conf as directed:
```
P|submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,permit_mynetworks,reject
P|smtps/inet/smtpd_client_restrictions=permit_sasl_authenticated,permit_mynetworks,reject
```

Lines show with proper values in container's ```/etc/postfix/master.cf``` without need for file override. Working like a charm! Thanks again
