### ISSUE TITLE
SSL_accept error from mydomain.com

### ISSUE THREAD

**Issue by loic-lopez** [hardware/mailserver#298]
#### Classification

* [] Question
* [ ] Deliverability issue
* [X ] Crash/Hang/Data loss
* [ ] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [ ] Feature/Enhancement
* [ ] Documentation

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

#### Docker information
```
hardware/mailserver   1.1-stable
```

#### Description
Hello,

I am trying to connect this mail server with atlassian software like Crowd, when i send a mail from this service an error occurs on the mail server.

The atlassian services are not in the same server.

#### Actual results
SSL_accept error

#### Debugging information
```
connect from serverip.com
SSL_accept error from mydomain.com : -1
warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974
lost connection after CONNECT from mydomain.com
```

Thanks for reply.

**Comment by denji** [comment]
It looks like you are trying to connect SSLv2/3 through a port which only allows TLS, try port 25 or port, supports STARTLS.

Service | Software | Protocol | Port
-- | -- | -- | --
SMTP | Postfix | TCP | 25
SMTPS | Postfix | TCP | 465
Submission | Postfix | TCP | 587

**Comment by loic-lopez** [comment]
Thanks for reply,

I have tried with the port 25 and it give me : 
```
NOQUEUE: reject: RCPT from mydomain.com
```

How i can allow an IP or and subdomain like `crowd.mydomain.com`

Thanks again.

**Comment by loic-lopez** [comment]
I think the load of postfix custom.conf has a bug because:
```
[INFO] Traefik SSL certificates not used
[INFO] Let's encrypt live directory found
[INFO] Using /etc/letsencrypt/live/mail.exosuite.fr folder
[INFO] Found DKIM key pair for domain exosuite.fr - skip creation
[INFO] Custom Postfix configuration file loaded
[INFO] MariaDB/PostgreSQL hostname not found in /etc/hosts
[INFO] Container IP found, adding a new record in /etc/hosts
[INFO] Redis hostname not found in /etc/hosts
[INFO] Container IP found, adding a new record in /etc/hosts
[INFO] Debug mode is disabled
[INFO] ClamAV is enabled
[INFO] Fetchmail forwarding is disabled
[INFO] Automatic GPG encryption is disabled
[INFO] ManageSieve protocol is enabled
[INFO] DKIM/ARC signing is enabled
[INFO] Greylisting policy is enabled
[INFO] Ratelimiting policy is disabled
[INFO] POP3 protocol is disabled
[INFO] Unbound DNS resolver is enabled
```

`[INFO] Custom Postfix configuration file loaded` but `smtpd_sender_restrictions`was not overridden

**Comment by hardware** [comment]
`mydomain.com` need to be declared in postfixadmin and your atlassian software must be authenticated before sending an e-mail `Sender address rejected: not logged in`. RELAY_NETWORKS isn't needed in your case. You can use a no-reply address.

![1471795422](https://user-images.githubusercontent.com/327354/45108710-aa1dc800-b13d-11e8-8761-553c752894f4.png)

**Comment by hardware** [comment]
> I think the load of postfix custom.conf has a bug because

No rule was loaded according to the logs so your file is empty or it is badly formatted.

**Comment by loic-lopez** [comment]
@hardware Yes it lacked a newline at the end of the custom.conf file.

Thanks for reply.
