### ISSUE TITLE
Add postfix blacklisting via sender_access

### ISSUE THREAD

**Issue by atomtigerzoo** [hardware/mailserver#299]
#### Classification
* [X] Feature/Enhancement

#### Reproducibility
* [X] Not applicable

#### Description
I would like to block some senders in postfix by adding them to `sender_access` for easy and fast blacklisting of i.e. unreasonable senders of newsletters.

I would try and add this to the project, but I'm by no way a docker or shell expert, so this would take days :/

Is this something the project could need? I think yes 😃

**Comment by hardware** [comment]
> Is this something the project could need ?

All contribution are welcome, I do not need this feature but it can still be useful for others.

**Comment by hardware** [comment]
@atomtigerzoo https://github.com/hardware/mailserver#postfix-blacklist

**Comment by atomtigerzoo** [comment]
Cool 👨‍🚀 Thank you very much for the enhancement!!

**Comment by atomtigerzoo** [comment]
Sorry to open this again, but somehow it is not working here, the file seems not be copied.

    mailserver      | 2018-09-24T15:47:42.490901+00:00 mail postfix/smtpd[778]: error: open database /etc/postfix/sender_access.db: No such file or directory

Here is what I did:

    sudo docker-compose down
    sudo docker-compose pull
    sudo nano mail/postfix/sender_access
    [entered 5 domains, saved]
    sudo docker-compose up

Watched the logs and received the above. I checked to see if the mailserver docker image is new, and it is:

    hardware/mailserver     1.1-stable          b12411bf5132        30 hours ago        379MB

Is there anything that I've been missing? :/

**Comment by hardware** [comment]
This feature is only available with 1.1-latest for the moment.

**Comment by navossoc** [comment]
@atomtigerzoo have you tried to run:

```postmap /etc/postfix/sender_access```

(please adjust the path, I'm not sure where this file is located on the container)

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/blob/0b483b8e4b62be6315d798cbc448574f35c6df41/rootfs/usr/local/bin/run.sh#L534-L537

**Comment by navossoc** [comment]
Not sure if I did something wrong, but I was testing this feature recently and there were almost 100 messages in my message queue related to blacklisted domains.

Are they going to stay there forever or I'm missing something?

[]'s
