### ISSUE TITLE
Update container -  Temporary lookup failure

### ISSUE THREAD

**Issue by cracker0dks** [hardware/mailserver#30]
Hey after I have updated my container I get this error:

`Temporary lookup failure` at the client.

When I want to send a mail (can not reseve also). But I can view all my mails as before...

In the console I get the message:

`warning: connect to mysql server mariadb: Unknown MySQL server host 'mariadb'`

but if I connect to the container and ping the db there is no problem... 

My startparameters:
`docker run --name=mail --link mariadb:mariadb --restart=always -p 25:25 -p 143:143 -p 465:465 -p 587:587 -p 993:993 -p 4190:4190 -e DBHOST=mariadb -e DBUSER=mailserver -e DBNAME=mailserver -e DBPASS=mypassword -e ADD_DOMAINS=mail.domain.tld -v /home/mailserver:/var/mail -v /home/mailserver/opendkim:/etc/opendkim/keys -h mail.domain.tld -d hardware/mailserver`
did not changed it since first start

Any suggestions ? Thanks :)

**Comment by hardware** [comment]
Same issues : #14 #27

**Comment by hardware** [comment]
Can you please retry with **docker run** AND **docker-compose v1** AND **v2** ?

**Comment by cracker0dks** [comment]
oh thanks alot! I have no docker compose but I binded the host file from outside the container read only:

`/home/mailserver/hosts:/var/spool/postfix/etc/hosts:ro`

so I can restart and update the container.

Its a little workaround but Solved :)

**Comment by hardware** [comment]
Fix in c2c8a22

Can you confirm ?

**Comment by cracker0dks** [comment]
Very nice patch! Now its working without any hardcoded config again :tada:
