### ISSUE TITLE
providing auto-configuration for mail clients

### ISSUE THREAD

**Issue by albjeremias** [hardware/mailserver#302]
#### Classification

* [X] Feature/Enhancement

#### Description
It would be cool if mailserver could provide auto-configuration files for the different mail clients... checkout this interesting articles:

http://web.archive.org/web/20120828065248/http://moens.ch/2012/05/31/providing-email-client-autoconfiguration-information/ stolen from
https://serverfault.com/questions/172326/how-to-configure-email-autoconfiguration-for-a-domain

**Comment by hardware** [comment]
This feature is useful for public mailserver with a lot of "casuals" users with multiples e-mail client. This docker image is not targeting this type of use. Moreover, most email clients do not share the same method, which makes the task difficult. 

And auto-configuration service completely depends on your reverse proxy to distribute autodiscover/autoconfiguration file.
