### ISSUE TITLE
AbuseIO & FBL Messages (Feedback Loop)

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#304]
* https://abuse.io/abuseio/features/
* https://github.com/AbuseIO/AbuseIO
* https://github.com/AbuseIO/parser-fbl/blob/master/config/Fbl.php

# ISP Feedback Loops

A Feedback Loop (FBL) is a system by which an Internet Service Provider provides the sender a copy of the message that one of their subscribers has reported as spam — usually by hitting a “report spam” button in that ISP’s mail interface.

ISPs offer feedback loops to qualified senders, so the senders can identify subscribers who no longer want to receive similar mail and/or any problems originating from their networks, such as virus-infected spam-producing machines.

This page summarizes the information about FBL signup pages, whitelist pages, and postmaster pages of most popular ISPs around the world.

| ISP | **FBL Signup** | **Whitelist Signup** | **Postmaster Page** |
----- | -------------- | -------------------- | -------------------
AOL                         | [AOL FBL signup](https://postmaster.info.aol.com/fbl-request)                                                            | [AOL Whitelist signup](http://postmaster.info.aol.com/Postmaster.Whitelist.php)             | [AOL postmaster](http://postmaster.info.aol.com/)                 
AT&T                        | does not provide                                                                                                         | does not provide                                                                            | [AT&T postmaster](http://www.att.com/esupport/postmaster/)        
Bellsouth                   | does not provide                                                                                                         | does not provide                                                                            | [Bellsouth postmaster](http://www.att.com/esupport/postmaster/)   
Comcast                     | [Comcast FBL signup](http://feedback.comcast.net/)                                                                       | does not provide                                                                            | [Comcast postmaster](http://postmaster.comcast.net/)              
centrum.cz                  | [Centrum FBL signup by email](http://napoveda.centrum.cz/index.php?/Knowledgebase/Article/View/153/12/feedback-loop-fbl) | does not provide                                                                            | does not provide                                                  
Cox                         | [Cox FBL signup](http://fbl.cox.net/)                                                                                    | does not provide                                                                            | [Cox postmaster](http://postmaster.cox.net/)                      
Earthlink                   | [Earthlink FBL signup](mailto:fblrequest@abuse.earthlink.net)                                                            | does not provide                                                                            | does not provide                                                  
Excite (Bluetie)            | [Excite FBL signup](http://feedback.bluetie.com/)                                                                        | does not provide                                                                            | [Excite postmaster](http://postmaster.bluetie.com/)               
FastMail                    | [FastMail FBL signup](http://fbl.fastmail.com/)                                                                          | does not provide                                                                            | does not provide                                                  
Gmail                       | [Gmail FBL signup (ESP only)](https://docs.google.com/forms/d/1WBnrmKw8KUV1-2e2D-3Syp8cx0m3pDFKkav3pg7mjLU/viewform)     | does not provide                                                                            | [Gmail postmaster](https://support.google.com/mail/answer/6227174)
Hotmail                     | [Hotmail FBL signup](https://postmaster.live.com/snds/JMRP.aspx?wa=wsignin1.0)                                           | does not provide                                                                            | [Hotmail postmaster](https://postmaster.live.com/pm/services.aspx)
Mail.ru                     | [Mail.ru FBL signup](http://fbl.mail.ru/)                                                                                | does not provide                                                                            | [Mail.ru postmaster](http://postmaster.mail.ru/)                  
Outblaze                    | [Outblaze FBL signup](mailto:postmaster@outblaze.com)                                                                    | does not provide                                                                            | does not provide                                                  
Rackspace                   | [Rackspace FBL signup](http://fbl.apps.rackspace.com/)                                                                   | does not provide                                                                            | [Rackspace postmaster](https://emailsrvr.com/index.php)           
Synacor                     | [Synacor FBL signup](http://fbl.synacor.com/)                                                                            | does not provide                                                                            | does not provide                                                  
Terra.com.br                | —                                                                                                                        | does not provide                                                                            | does not provide                                                  
Tucows                      | [Tucows FBL signup](http://fbl.hostedemail.com/)                                                                         | does not provide                                                                            | does not provide                                                  
UnitedOnline (NetZero/Juno) | does not provide                                                                                                         | [UnitedOnline Whitelist signup](http://postmaster.untd.com/whitelisted.html)                | [UnitedOnline postmaster](http://postmaster.untd.com/index.html)  
USA.net                     | [USA.net FBL signup](http://fbl.usa.net/)                                                                                | does not provide                                                                            | [USA.net postmaster](http://postmaster.usa.net/)                  
Verizon                     | does not provide                                                                                                         | [Verizon Whitelist signup](http://www2.verizon.net/micro/whitelist/request_form.asp?id=isp) | does not provide                                                  
XS4ALL                      | [XS4ALL FBL signup](http://feedbackloop.xs4all.nl/)                                                                      | does not provide                                                                            | does not provide                                                  
Yahoo!                      | [Yahoo! FBL signup](http://feedbackloop.yahoo.net/)                                                                      | [Yahoo! Whitelist signup](http://help.yahoo.com/l/us/yahoo/mail/postmaster/bulkv2.html)     | [Yahoo! postmaster](http://postmaster.yahoo.com/)                 
Yandex                      | [Yandex FBL signup](http://yandexfbl.senderscore.net/)                                                                   | does not provide                                                                            | [Yandex postmaster](https://postoffice.yandex.ru/)                
ZOHO                        | [ZOHO FBL signup](http://www.zoho.com/fbl/index.html)                                                                    | does not provide                                                                            | does not provide

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/wiki/ISP-Feedback-Loops
