### ISSUE TITLE
Spam rejected

### ISSUE THREAD

**Issue by cypriotxx** [hardware/mailserver#305]
* [X] Question
Hi there, 
what i noticed that some emails rejected are not always spam and end up left on the cloud server ,..
is there anyway we can accept all mails and spams just would end up in our junk as it should be instead of left on cloud server ? thanks

docker info
docker images hardware/mailserver --digests --filter "dangling=false"
hardware/mailserver   1.1-stable          sha256:b930736623fc35668a6ccd7d4e736c5826446c2683841351672f53752579e6e1   7a6cc949cfd7        3 months a

**Comment by hardware** [comment]
Increase rejection value in `rspamd/local.d/actions.conf`. Example : `reject = 99;`

If an email reaches the default rejection score (20), you can be sure he has nothing to do on your server, even in junk mailbox. There is no false positive at this level.

**Comment by navossoc** [comment]
@cypriotxx Yes, that is it.

You can also change this on the rspamd web interface.

![image](https://user-images.githubusercontent.com/2457338/45883912-cc902200-bd88-11e8-8e55-57be50ee1d6e.png)

**Comment by cypriotxx** [comment]
some of the logs showing this also 
Sender address rejected: Domain not found

would this be same settings or ?

**Comment by navossoc** [comment]
Have you registered your own domains on postfixadmin?

Please attach the log.

[]'s

**Comment by cypriotxx** [comment]
actually we set this server at the office to use it like this
https://github.com/gw0/docker-dovecot-getmail

Couldnt use this one as there is no spam protection included so yours here is the best <3 

in office we didnt register our own real domain just registered as officemails.net in postfixadmin and added our 4email address in fetchmail settings to download our emails . 
and add our 4 different domain as identities in Roundcube , all fine now till here

now Roundcube giving error when trying to send FROM our domains because there is no sender dependent relay sasl etc settings are done yet, not sure how to go about this ... 
all mind blowing :D  any advice will be appreciated

**Comment by 1n5aN1aC** [comment]
> 
> @cypriotxx Yes, that is it.
> 
> You can also change this on the rspamd web interface.
> 

I would like to add that when I changed the limits using this interface, I somehow got into a weird state where the web-interface settings were being ignored completely.  Not only that, but the dev of rspamd more or less said to not use that to change the limits, at least not when you have 4 actions defined.

See this issue for more information: https://github.com/hardware/mailserver/issues/179

**Comment by hardware** [comment]
> Sender address rejected: Domain not found

> **reject_unknown_sender_domain**
Reject the request when Postfix is not final destination for the sender address, and the MAIL FROM domain has 1) no DNS MX and no DNS A record, or 2) a malformed MX record such as a record with a zero-length MX hostname.

You have a DNS problem. Check MX record for that domain.

**Comment by hardware** [comment]
@cypriotxx this feature is currently not implemented https://github.com/hardware/mailserver/issues/237
