### ISSUE TITLE
Improvement for docker-compose.sample.yml

### ISSUE THREAD

**Issue by sebastienDevibim** [hardware/mailserver#31]
In the docker-compose.sample.yml at the level of the Mariadb container, there are environment and volumes property which are set.
However if the volumes property is set then the environment variables are ignored.
I think it might be a good thing to specify it in the README for example.

**Comment by hardware** [comment]
Why not :)

I added this clarification : https://github.com/hardware/mailserver/commit/0675a3e5883cf247f0ad42aaa8391975e3a18f38

**Comment by sebastienDevibim** [comment]
Thank's :) !
