### ISSUE TITLE
Auto Renew Certificates from LetsEntrypt

### ISSUE THREAD

**Issue by catinred2** [hardware/mailserver#324]
#### Classification
* [X] Question
* [X] Documentation

#### Reproducibility
* [X] Not applicable

#### Description
I've built up the whole containers and it works well. As we know, the ssl certificate from letsentrypt  would expired in 3 months.  And I follow the instruction to install incron and add a script to restart mailserver container as soon as the acme.json file gets modified.
for auto renewal, is there anything more I should do ?

Thanks.

**Comment by denji** [comment]
No, because certificates need to be restarted only in the MailServer container. Traefik update it once we receive it.

**Comment by catinred2** [comment]
Many thanks.

**Comment by 1n5aN1aC** [comment]
@catinred2 could you provide any information on how you have the restart when modified set up?
