### ISSUE TITLE
Run Letsencrypt with nginx and the mail server [script]

### ISSUE THREAD

**Issue by mario26** [hardware/mailserver#327]
Hello !

I do not know if this is a good practice, but i use Nginx as a Web server and i had some trouble running with Letsencrypt on the mail server.

I want to explain to you in this issue how to get around my problems

For starters, here is the context, Nginx is executed in a container, i need this one to run hard sites on the server. Without any knowledge of Traefik, being a web server too young, i do not want to use it for now.

Letsencrypt is to install on the server, not finding my happiness in the tutorials of Internet to execute it in docker, i execute this one directly on the server.

So, i create a symbolic link to the Letsencrypt directory:

`ln -s /etc/letsencrypt/ /mnt/my-docker/config/`

I add the volume to mount for nginx and the mail server in the docker-compose.yml:

`- ${VOLUMES_ROOT_PATH}/config/letsencrypt/:/etc/letsencrypt`

I generate my certificate:

`certbot certonly --standalone --agree-tos -m contact@example.org -d example.org -d www.example.org -d mail.example.org -d spam.example.org`

Then i replace the signed auto certificates:

```
rm /mnt/my-docker/data/mail/ssl/selfsigned/cert.pem
rm /mnt/my-docker/data/mail/ssl/selfsigned/privkey.pem
cat /etc/letsencrypt/live/exemple.com/fullchain.pem >> /mnt/my-docker/data/mail/ssl/selfsigned/cert.pem
cat /etc/letsencrypt/live/exemple.com/privkey.pem >> /mnt/my-docker/data/mail/ssl/selfsigned/privkey.pem
```
I automate that with a bash script:

```
#!/bin/bash

echo -e '\033[0;33mContainer NGINX stop...'
docker-compose stop nginx && \
echo -e '\033[1;31mContainer NGINX stoped !'
docker-compose ps nginx && \

echo -e '\033[0;33mLetsencrypt certificates will be renewed...'
certbot renew >> /mnt/my-docker/scripts/logs/renew.txt && \
echo -e '\033[0;32mCertificates are verified/renewed, view: \033[4;32m/mnt/my-docker/scripts/logs/renew.txt'

echo -e '\033[0;33mContainer NGINX start...'
docker-compose start nginx && \
echo -e '\033[1;32mContainer NGINX starting !'
docker-compose ps nginx && \

echo -e '\033[0;33mContainer MAILSERVER stop...'
docker-compose stop mailserver && \
echo -e '\033[1;31mContainer MAILSERVER stoped !'
docker-compose ps mailserver && \

echo -e '\033[0;33mMAILSERVER certificates will be renewed...'
rm /mnt/my-docker/data/mail/ssl/selfsigned/cert.pem && \
rm /mnt/my-docker/data/mail/ssl/selfsigned/privkey.pem && \
cat /etc/letsencrypt/live/devosi.org/fullchain.pem >> /mnt/my-docker/data/mail/ssl/selfsigned/cert.pem && \
cat /etc/letsencrypt/live/devosi.org/privkey.pem >> /mnt/my-docker/data/mail/ssl/selfsigned/privkey.pem && \
echo -e '\033[0;32mMAILSERVER certificates are up-to-date!'

echo -e '\033[0;33mContainer MAILSERVER start...'
docker-compose start mailserver && \
echo -e '\033[1;32mContainer MAILSERVER starting !'
docker-compose ps mailserver && \

echo -e '\033[0;32mWell! All SSL certificates are up to date !'
```
Run the script:

`bash -c /mnt/my-docker/scripts/letsencrypt/renew.sh`

Here, i wanted to share my experience in exchange for some return.

Thank you for this beautiful Image!

I have 10/10 on => https://www.mail-tester.com

**Comment by denji** [comment]
`certbot` can start without downtime for nginx.
You must add location to handle `.well-known` and customize the operation manual `cerbot`.

Update the certificate via `nginx`, just run `docker-compose exec nginx nginx -s reload`. This will make a soft restart of nginx children without disconnection and downtime, relevant for the stable operation of `HTTP/2.0`.

**Comment by hardware** [comment]
You can use acme.sh to renew Let's Encrypt certificates, it's a great tool and very simple to use.

```bash
acme.sh \
  --issue \
  -w /mnt/docker/nginx/www/acme \
  -k 4096 \
  -d domain.tld \
  -d mail.domain.tld \
  -d webmail.domain.tld \
  -d spam.domain.tld \
  -d postfixadmin.domain.tld

acme.sh --install-cert -d domain.tld \
--ca-file        ${VOLUMES_ROOT_PATH}/ssl/live/mail.domain.tld/chain.pem  \
--cert-file      ${VOLUMES_ROOT_PATH}/ssl/live/mail.domain.tld/cert.pem  \
--key-file       ${VOLUMES_ROOT_PATH}/ssl/live/mail.domain.tld/privkey.pem  \
--fullchain-file ${VOLUMES_ROOT_PATH}/ssl/live/mail.domain.tld/fullchain.pem \
--reloadcmd      "docker restart mailserver"
```

acme.sh create a cron task to check if your certificates need to be renewed or not : 

```
30 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"
```

Put this in all your vhosts to renew without down time : 

```nginx
location ~ /\.well-known/acme-challenge {
  root /nginx/www/acme;
  allow all;
}

location / {
   ...
}
```

**Comment by denji** [comment]
@hardware *domain.tld/test/.well-known/acme-challenge

1. `location /.well-known/acme-challenge`
2. `location ^~ /.well-known/acme-challenge`

**Comment by mario26** [comment]
Thank you for your feedback!

@hardware: Thanks for your advice, do not know acme.sh, i'll see how it works and in practice, i will adapt to my Docker.

Regarding the "acme-challenge", I created in my VHOST Nginx includes:

```
server {
	listen 80;
...
	include /var/www/snippets/letsencrypt.conf;
...
}

My letsencrypt.conf
```
location ^~ /.well-known/acme-challenge/ {
  allow all;
  auth_basic "off";
  root /var/www/snippets/letsencrypt;
  default_type "text/plain";
  try_files $uri =404;
}
```
Everything to work, thank you for your responses!

**Comment by denji** [comment]
Here's another addition, besides the cron we can use systemd/Timers https://github.com/Neilpang/acme.sh/wiki/Using-systemd-units-instead-of-cron.
