### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by luminouw** [hardware/mailserver#33]
Hi,

I'm currently organizing a new infrastructure around an OpenLDAP container for my users, and I'd like to manage them from a centralized place.

I was going for a manual Postfix / Dovecot install revolving around my directory and then stumbled upon your packaged docker solution.

Do you know if this is all pluggable to an LDAP instance ? Thank you : )

**Comment by hardware** [comment]
It's possible, but I never used LDAP authentification. LDAP support isn't in the roadmap but i am open to integration suggestions, feel free to create a pull request to add this feature.

Some links :

http://www.postfix.org/LDAP_README.html
http://wiki2.dovecot.org/HowTo/DovecotOpenLdap
http://wiki.dovecot.org/AuthDatabase/LDAP
https://github.com/tomav/docker-mailserver/pull/251
http://www.iredmail.org/docs/active.directory.html
https://bitbucket.org/zhb/iredmail/src/3115ab14d3ec7c743d8d8c3cd8d7a0f9644b902c/iRedMail/samples/postfix/ldap
https://bitbucket.org/zhb/iredmail/src/3115ab14d3ec7c743d8d8c3cd8d7a0f9644b902c/iRedMail/samples/dovecot/dovecot-ldap.conf

**Comment by denji** [comment]
We have LDAP support. I will try however it will not be easy, as you will need valid schema information and query before adding ldap support (bootstrap).

**Comment by hardware** [comment]
No contributor for adding LDAP support so i close this issue. I'm not familiar with OpenLDAP protocol and I am not able to maintain an LDAP implementation in hardware/mailserver because I don't have a suitable environment for testing.
