### ISSUE TITLE
rspamd 

### ISSUE THREAD

**Issue by cypriotxx** [hardware/mailserver#334]
* [X] Question

hi there, all working lovely thank you all for this gorgeous piece of work

just one question  
i know where to add whitelist email addresses in YML file 
but 
how can i whitelist a domain name instead of email address ?

thank you so much

**Comment by BloodyAltair** [comment]
**+1** to this question
I have mounted custom whitelist mapping:
```
# /var/mail/rspamd/whitelist.conf

rules {
  "WHITELIST_CUSTOM_DOMAIN" = {
    strict = true;
    domains = "${DBDIR}/whitelist.inc.local";
    description = "Mail comes from the whitelisted domain";
    score = -200.0
  }
}
```
Added `shodan.io` to map through WebUI. But i still have 2.70 score

[Screenshot](https://cdn.pbrd.co/images/HOEJYxE.png)

**Comment by hardware** [comment]
Your example seems good. Please post your question on rspamd community support, sometimes rspamd's scoring system is hard to understand in some case.
