### ISSUE TITLE
Upgrade to RSPAM 1.8.3

### ISSUE THREAD

**Issue by dguttierrez** [hardware/mailserver#339]
Issue:

* [X] Question

Description:

Upgrade to RSPAM 1.8.1 or 1.8.3 - is this available only in latest branch?

**Comment by navossoc** [comment]
You can check it by looking at the `Components` section:

[stable](https://hub.docker.com/r/hardware/mailserver/builds/bermupufptwa7nvmnpha9en/): 1.8.1
[latest](https://hub.docker.com/r/hardware/mailserver/builds/bkwm6x8nuhzyzzubjj4iacw/): 1.8.3

**Comment by dguttierrez** [comment]
Tnx for that. I have docker-compose file with:
 mailserver:
    image: hardware/mailserver:${MAILSERVER_DOCKER_TAG}

and then .env file with this:
MAILSERVER_DOCKER_TAG=1.1-stable

if I execute docker-compose down and then up -d there is no upgrade of RSPAM, how can I upgrade RSAPM from version 1.7.9?

**Comment by hardware** [comment]
Use `MAILSERVER_DOCKER_TAG=1.1-latest`.

https://github.com/hardware/mailserver/blob/fb740e5c26008eef3730d559d75d1c8cf6216446/sample.env#L26-L35

**Comment by navossoc** [comment]
You should pull the image again:

``
docker-compose pull
docker-compose images
```

[]'s

**Comment by hardware** [comment]
Rspamd 1.8.3 will be available on stable branch (`1.1-stable` docker tag) after few weeks.
