### ISSUE TITLE
Allow to have multiple domains on opendkim

### ISSUE THREAD

**Issue by sebastienDevibim** [hardware/mailserver#34]
Could you implement a way to have multiple entry in the KeyTable, SigningTable and TrustedHosts ?
Maybe doing a shared folder and if the files exist then don't reset them.
It can be useful for multiple domains DKIM signing.
Actually on each restart these files are reset to the original values.

**Comment by hardware** [comment]
You can use **ADD_DOMAINS** environment variable for this purpose.

**Comment by sebastienDevibim** [comment]
Thanks, I didn't notice that 1
