### ISSUE TITLE
fail2ban for mailserver

### ISSUE THREAD

**Issue by heliflieger** [hardware/mailserver#341]
#### Classification

* [X] Question

#### Reproducibility

* [X] Always

#### Description
Can you insert the fail2ban to the mailserver?
I think it would be nice to block the fault logins/hacking from other destinations.

**Comment by hardware** [comment]
fail2ban is outside the scope of this project, I need to keep it easy to maintain. Personally, I prefer Ossec to protect my mailserver. I use it for years outside of my container, in host level.

Ossec : https://github.com/ossec/ossec-hids
Ossec fork (Wazuh) : https://github.com/wazuh/wazuh

**Comment by denji** [comment]
I would not like to see fail2ban as a base supply if any other fail2ban alternative is possible.

**Comment by navossoc** [comment]
@hardware Is there any general guidelines that you can share? Like the rules?

I would like to test it...

[]'s

**Comment by heliflieger** [comment]
I have done it now outside the docker container on the docker-host.

The changed rules and filters are attched.

[docker-action.conf.txt](https://github.com/hardware/mailserver/files/2682629/docker-action.conf.txt)
[dovecot-docker.conf.txt](https://github.com/hardware/mailserver/files/2682630/dovecot-docker.conf.txt)
[jails.conf-rules.txt](https://github.com/hardware/mailserver/files/2682631/jails.conf-rules.txt)
[postfix-docker.conf.txt](https://github.com/hardware/mailserver/files/2682632/postfix-docker.conf.txt)
[postfix-sasl-docker.conf.txt](https://github.com/hardware/mailserver/files/2682633/postfix-sasl-docker.conf.txt)

Remark: After start/restart the docker container, you should restart the fail2ban. This is needed, because the docker can get a new container storage and then the logfiles are located on another position.

**Comment by navossoc** [comment]
> Remark: After start/restart the docker container, you should restart the fail2ban. This is needed, because the docker can get a new container storage and then the logfiles are located on another position.

Probably is easy to bind mount the logs from the container to the host and make it use a fixed path.

I'll take a closer look later, I let you know if I found something useful ;)
Anyhow, thanks.

[]'s
