### ISSUE TITLE
Question postfix virtuals

### ISSUE THREAD

**Issue by rs-development** [hardware/mailserver#344]
#### Classification
* [X] Question

#### Reproducibility
* [X] Not applicable

#### Description
Is there an option to use the standard postfix files for virtual forwarding or can this only be done via the web interface of postfixadmin?
I have a lot of addresses with i like to manage via a script connecting to the ldap server.

**Comment by denji** [comment]
Similar questions #33, #218.

**Comment by rs-development** [comment]
Thanks for answering the LDAP Question.
Is it possible to use the standard files, without a database set?

**Comment by hardware** [comment]
It should be possible with small adjustments but that's not the purpose of this docker image, I only maintain the postfixadmin database version. If you need only configuration files, no SQL database, you should definitely see this project : https://github.com/tomav/docker-mailserver

**Comment by rs-development** [comment]
Thanks for the comment, this is the alternative mailserver i was looking at. 

I really liked the RSpamd web interface from your image! And also the Dokumenation is very detailed, which is great for beginners. :+1:
