### ISSUE TITLE
Configuring Rspamd for custom subject rewriting via the web ui

### ISSUE THREAD

**Issue by gotjoshua** [hardware/mailserver#357]
#### Classification

* [X] Question

I am trying to follow the instructions at the bottom of the [Rspamd Metrics Docs](https://rspamd.com/doc/configuration/metrics.html).

And I added the following configuration to:
/var/mail/rspamd/rspamd_dynamic (via the rspamd web ui):

```[
    {
        "metric": "default",
        "subject": "[* SPAM>9 *] %s",
        "actions": [
            {
                "name": "rewrite subject",
                "value": 9.0,
                "subject": "[* SPAM>9 *] %s"
            },
```

The subject rewrite is happening, but not using the custom format.

Any advice?

**Comment by hardware** [comment]
Please, ask any question about rspamd here : https://rspamd.com/support.html
