### ISSUE TITLE
Missing if statement in run.sh

### ISSUE THREAD

**Issue by artifex404** [hardware/mailserver#361]
#### Classification
* [X] Minor bug

#### Description
Seems there is a missing if statement in the shell script:
https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/run.sh#L423

**Comment by denji** [comment]
![block](https://user-images.githubusercontent.com/3759759/53576053-89c64780-3b7b-11e9-883d-a7f38ae463b0.png)

**Comment by artifex404** [comment]
My bad, sorry :)
