### ISSUE TITLE
Legacy email protocols to bypass MFA & breach accounts

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#368]
* https://www.proofpoint.com/us/threat-insight/post/threat-actors-leverage-credential-dumps-phishing-and-legacy-email-protocols
* [hardware/mailserver#80](https://github.com/hardware/mailserver/issues/80)

**Comment by sknight80** [comment]
As I understood we are good here. Aren't we?

**Comment by denji** [comment]
It's a reflection on how we can improve protection against compromise. Even if you use webmail with pop/imap. turned off, you still have the option of attacking via smtp.

**Comment by sknight80** [comment]
@denji I am curious why did you close this ticket?
