### ISSUE TITLE
Use TLD as hostname?

### ISSUE THREAD

**Issue by ForsakenHarmony** [hardware/mailserver#369]
#### Classification
* [X] Question

#### Reproducibility
* [X] Always

#### Description
I'm wondering if there's some way to use the tld as the hostname, as my reverse dns is set up to point at it, so `domain.tld` instad of `mail.domain.tld`

**Comment by sknight80** [comment]
Hi @ForsakenHarmony ,

My guess is not possible because of the PTR lookup as it mentioned here: https://github.com/hardware/mailserver/blob/master/docker-compose.sample.yml#L40

**Comment by ForsakenHarmony** [comment]
Managed to make it work by using

```
    domainname: com
    hostname: example
```
