### ISSUE TITLE
Need maintainers

### ISSUE THREAD

**Issue by hardware** [hardware/mailserver#371]
Hi everyone,

As you may have noticed, the project has not moved forward since january. I'm running out of time right now to maintain these docker images and review pull requests. I started this mailserver in 2016, it was only a small personal project at the time 😄 But it has evolved substantially, attracting more and more people, thanks to great contributors.

Now, I make this call to all regular contributors and all people who has a good knowledge of this project and internet mail standards. If you are interested, you can add a message in this issue. To show your support to potential future maintainers, add a thumbs up emoji 👍 on their messages.

If you want more information on how this project works (workflows, new features, testing, builds,  continuous integration process...etc) you can post your questions here.

Thanks in advance to all the volunteers.

**Comment by ksylvan** [comment]
I'm extremely busy as well but send me details and I'll see what it would take.

**Comment by sknight80** [comment]
I would like to help in this project. Unfortunately, I have only a little knowledge in mailserver, but I guess this knowledge can pickup during the time.

**Comment by xvello** [comment]
Hi!

I've been using this solution for a year now, after running my own non-containerized stack for years. I currently run it on a Nomad / Consul / Traefik mono-node.

You can have a look at [my contributions on the Datadog agent](https://github.com/DataDog/datadog-agent/graphs/contributors) (my previous team), which has a very similar image (debian base, s6 supervision, lots of external dependencies to monitor).

I can mostly help with packaging, CI, security tracking and testing. Ping me if you're interested!

**Comment by michael-k** [comment]
I don't feel experienced enough for the main project, but I'd love to help maintaining https://github.com/hardware/nsd-dnssec and https://github.com/hardware/postfixadmin

**Comment by neuffer** [comment]
> I don't feel experienced enough for the main project, but I'd love to help maintaining https://github.com/hardware/nsd-dnssec and https://github.com/hardware/postfixadmin

Closer integration/tracking with the source repository of [Postfixadmin](https://github.com/postfixadmin/postfixadmin) would be great. :-)

**Comment by hardware** [comment]
@michael-k You're the main contributor on nsd-dnssec repo since almost 3 years, so I do not see any problem to give you access on both ;) I'll let you know.

@ksylvan @sknight80 @xvello Thank you ! Maybe I can take some hours to make a "How to maintain mailserver project".  The most important thing and what requires a bit of experience is writing integration tests to avoid any regression with a new feature.

**Comment by michael-k** [comment]
@hardware Thanks for the access.  Can you activate travis for both repos?  Preferably https://travis-ci.com/account/repositories, if not possible https://travis-ci.org/account/repositories

I can change the settings at https://travis-ci.org/hardware/nsd-dnssec/settings, but I don't have sufficient rights to activate the builds. :/

**Comment by hardware** [comment]
@michael-k Done.

**Comment by johansmitsnl** [comment]
I have done quite some work at https://github.com/tomav/docker-mailserver and recently switched over to this project. Don't have much time available but I am a daily user of the product and have mail experience.

Using the LDAP PR at the moment so I could assist there.

**Comment by sknight80** [comment]
@hardware if you around, I am trying to review a couple of PRs and answering some questions here there. I hope that is okay

**Comment by hardware** [comment]
@johansmitsnl & @sknight80  I sent you both an invitation. I reactivated docker hub build (the github token had expired since 1 month..).

> I am trying to review a couple of PRs and answering some questions here there. I hope that is okay

No problem. I think most of these PR can be safely merged. LDAP one is a pretty massive one but seems to work for those who use it 👍

**Comment by johansmitsnl** [comment]
@hardware Thanks for the invitation.

I use the LDAP branch on 2 locations (office and personal) without any issues.

Can you explain more about the releasing, there is a master branch some branches (stable).
Is master considered edge, and when x time passes merged into stable?

Please inform us what the strategy is so we can continue it.

**Comment by sknight80** [comment]
@hardware thank you for the invitation.

@johansmitsnl yeah, I like your idea and direction.  I am onboard with it.

**Comment by dguttierrez** [comment]
Hello

I have forked mailserver, rainloop, debian-mail-overlay, nsd, postfixadmin, afterlogic ... and compile it on my personal Gitlab and test it on my docker host. Now I have upgraded RSPAM to latest version, and make another branch for debian-mail-overlay, which now includes:

Skalibs 2.8.1.0 : https://skarnet.org/software/skalibs/
Execline 2.5.1.0 : https://skarnet.org/software/execline/
s6 2.8.0.1 : https://skarnet.org/software/s6/
Rspamd 1.9.4 : https://rspamd.com/
Gucci 1.2.2 : https://github.com/noqcks/gucci/

and Debain Buster Slim and create docker images. This is for now in my private GITLab, how can I contribute all Dockerfiles, ... to you, I you are interested. Sorry for questions, I'm not so familiar with Gitlab, but just want to help, to keep this fantastic project alive.

**Comment by hardware** [comment]
@dguttierrez Hi

I upgraded the base image yesterday with the latest Rspamd version and skarnet's suit. Now I'm working on Debian Buster as well (since this morning).

https://github.com/hardware/debian-mail-overlay/commit/b554cb797163bf9357a9576cfa472171fe329771

If you want to contribute, feel free to pull your gitlab work on Github and then make a pull request on this repo. You can do the same for project repositories (rainloop, nsd, postfixadmin, afterlogic).
