### ISSUE TITLE
 How do I set up the email forward to gmail or frontapp

### ISSUE THREAD

**Issue by ivajo26** [hardware/mailserver#379]
How do I set up the email remail to gmail or frontapp

**Comment by sknight80** [comment]
Hi,

You can do it in `postfixadmin`.  You can set email forward for all incoming emails for a mailbox or a domain as well.

**Comment by ivajo26** [comment]
> Hi,
> 
> You can do it in `postfixadmin`. You can set email forward for all incoming emails for a mailbox or a domain as well.

Yes, its works.
