### ISSUE TITLE
postfix: adding custom config problem

### ISSUE THREAD

**Issue by j-schumann** [hardware/mailserver#38]
The startup script allows to use /var/mail/postfix/custom.conf to overwrite the default settings w/ the help of postconf.
When only overriding existing options this works. But when I try to add an option previously undefined in the main.cf like "smtpd_data_restrictions" or "smtpd_delay_reject" it is NOT appended as a new file but instead appended to the last line. Further new options then will be added as new lines.
Result looks like:

> non_smtpd_milters     = $smtpd_milterssmtpd_delay_reject = yes
> smtpd_data_restrictions = reject_unauth_pipelining

So this should be fixed by keeping a trailing linebreak in the /etc/postfix/main.cf

**Comment by hardware** [comment]
Smallest commit ever ! :smiley:
