### ISSUE TITLE
How to add email account from terminal?

### ISSUE THREAD

**Issue by unomind** [hardware/mailserver#386]
How to add email account from terminal?

Thanks

**Comment by navossoc** [comment]
I don't know if it works or not but seems that postfixadmin has a cli interface.

> commandline client postfixadmin-cli for those who don't want to click around in a web interface ;-)

I'm inserting the accounts directly on the SQL.

**Comment by sknight80** [comment]
I think if you are using the CLI command, they may send a welcome email, so the mailbox will be created by postfix + dovecot

**Comment by unomind** [comment]
> I'm inserting the accounts directly on the SQL.
Which table?

Thanks

**Comment by navossoc** [comment]
@nomind `mailbox` and `alias`

```SQL
INSERT INTO mailbox (username, password, maildir, quota, active, domain, local_part) VALUES ...
```

```SQL
INSERT INTO alias (address, goto, domain, active) VALUES ...
```

**Comment by unomind** [comment]
Cool, thank you

**Comment by sknight80** [comment]
I might be late in the party, but this documentation might help: https://sourceforge.net/p/postfixadmin/wiki/Postfixadmin-cli/

I am not sure if we included the `cli` package in the postfixadmin image/container.
