### ISSUE TITLE
CalDAV add-on?

### ISSUE THREAD

**Issue by ragboy** [hardware/mailserver#387]
#### Classification
_Please delete options that are not relevant._

* [ ] Question
* [ ] Deliverability issue
* [ ] Crash/Hang/Data loss
* [ ] Serious bug
* [ ] Minor bug
* [ ] Vulnerability
* [X] Feature/Enhancement
* [ ] Documentation

#### Description
Any plans or do you know of any add-on for a CalDAV server to incorporate? I have been using this for a couple years now, and its been great.

**Comment by iMouath** [comment]
[radicale](https://radicale.org/) is pretty good. I've it running in the same vps but not inside a docker container.
configured *traefik* `[file]` [provider](https://docs.traefik.io/providers/file/) to proxy it under SSL

```traefik.toml
...

[file]
domain = "domain.tld"
watch = true
exposedbydefault = false

[backends]
  [backends.radicale]
    [backends.radicale.servers.radicale]
    url = "http://0.0.0.0:5232/"

[frontends]
  [frontends.radicale]
  backend = "radicale"
    [frontends.radicale.routes.radicale]
    rule = "Host:dav.domain.tld"
```
