### ISSUE TITLE
Problems on dovecot configuration files customization

### ISSUE THREAD

**Issue by incal** [hardware/mailserver#388]
Hi,
I try this solution for override dovecot custom conf 

```yml
volumes:
  - /path/to/10-mail.conf:/etc/dovecot/conf.d/10-mail.conf
```

```ini
mail_plugins = $mail_plugins quota
mail_location = maildir:/var/mail/vhosts/%d/%n/{{ VMAIL_SUBDIR }}
maildir_stat_dirs=yes

namespace inbox {
  prefix = INBOX.
  separator = .
  inbox = yes
}

mail_uid = {{ VMAILUID }}
mail_gid = {{ VMAILGID }}
mail_privileged_group = vmail
```

> To extend dovecot configuration, I can add `!include_try custom.conf` in `dovecot.conf` but this will not work in your case because you want to make changes and not extend the configuration.

> or check if anything else changed in the file in the new image and adapt my own copy of the file.

> `10-mail.conf` should not be changed noticeably without a new version of this docker image. So it's pretty safe to override it.

_Originally posted by @hardware in https://github.com/hardware/mailserver/issues/186#issuecomment-341880864_

but I have this error:
`doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-mail.conf line 12: Invalid number {{ VMAILUID }}: Not a valid number`

with and without the dot:
`doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-mail.conf line 12: Invalid number {{ .VMAILUID }}: Not a valid number`

in composer file VMAILUID and VMAILGID vars take the value from env vars:

`    - VMAILUID= ${USER_UID} #vmail user id [optional 1024]
      - VMAILGID= ${USER_GID} #vmail group id [optional defailt 1024]
`

in .env:
`USER_UID=1000
USER_GID=1000
`

what is wrong?
thanks in advance

**Comment by sknight80** [comment]
Hi @incal ,

In your `.env` file the `USER_UID=1000` and `USER_GID=1000` are the same line or in separate lines? Like:
```
USER_UID=1000
USER_GID=1000
```

**Comment by incal** [comment]
Hi,  thanks for reply
they are in separate lines

> USER_UID=1000
> USER_GID=1000

**Comment by sknight80** [comment]
Ok. Are you running your setup via `docker-compose` or using Ansible (https://github.com/hardware/mailserver#ansible-playbooks)?

**Comment by incal** [comment]
my setup is via docker-compose

**Comment by sknight80** [comment]
Ok, have you tried this?
```
...
mailserver:
    ...
    environment:
      ...
      - VMAILUID=${USER_UID}
      - VMAILGID=${USER_GID}
```

Based on the `run.sh` this should work.

**Comment by incal** [comment]
yes, it is:

>     environment:
>       - TZ=${TIMEZONE}
>       - VMAILUID= ${USER_UID} #vmail user id [optional 1024]
>       - VMAILGID= ${USER_GID} #vmail group id [optional defailt 1024]

**Comment by hardware** [comment]
Your method is a bad practice. Gucci can't replace your {{ ... }} variable in your case.

Use the official way documented in the readme : https://github.com/hardware/mailserver#custom-configuration-for-dovecot using `/mnt/docker/mail/dovecot/conf.d`.

**Comment by navossoc** [comment]
@incal There are spaces after the equal sign...
`VMAILUID= ${USER_UID}`

**Comment by hardware** [comment]
> @incal There are spaces after the equal sign...
> `VMAILUID= ${USER_UID}`

That is not the issue. Issue is Gucci can't replace variables in a custom mounted file. This is a bad pratice.

`Invalid number {{ VMAILUID }}: Not a valid number`

**Comment by incal** [comment]
> > @incal There are spaces after the equal sign...
> > `VMAILUID= ${USER_UID}`
> 
> That is not the issue. Issue is Gucci can't replace variables in a custom mounted file. This is a bad pratice.
> 
> `Invalid number {{ VMAILUID }}: Not a valid number`

what then is the correct procedure to override the dovecot settings?

**Comment by hardware** [comment]
https://github.com/hardware/mailserver#custom-configuration-for-dovecot

**Comment by incal** [comment]
I apologize but I would like to understand better: in practice I do not have to insert environment variables but directly the values in the conf files?

**Comment by navossoc** [comment]
@incal yes, you will have to hard code it...

**Comment by hardware** [comment]
> I apologize but I would like to understand better: in practice I do not have to insert environment variables but directly the values in the conf files?

Both, insert an env variable and hard code it your custom files. Because VMAILUID/VMAILGID are used in other files.
