### ISSUE TITLE
rspamd StochasticGradient error

### ISSUE THREAD

**Issue by incal** [hardware/mailserver#390]
Hi,
I have this errors in mail log file about rspamd problems

```
# StochasticGradient: training
# StochasticGradient: you have reached the maximum number of iterations
# training error = 0.00083207718058818
# StochasticGradient: training
# StochasticGradient: you have reached the maximum number of iterations
# training error = 0.064932535430326
```

any suggestions?

**Comment by hardware** [comment]
https://github.com/rspamd/rspamd/issues/2329

**Comment by incal** [comment]
this is closed but I don't understand the solution

**Comment by hardware** [comment]
I closed this issue because it's not a mailserver project problem. You can ask for more information about machine-learning behavior on the rspamd mailing list : https://rspamd.com/support.html
