### ISSUE TITLE
Upgrade to Debian 10 Buster

### ISSUE THREAD

**Issue by hardware** [hardware/mailserver#393]
## :exclamation:  Current sticking points

* [ ]  Zeyple : [pygpgme](https://pypi.org/project/pygpgme/) is no longer supported by upstream for years and has a successor (python-gpg), python-gpgme package is no longer available with Buster. Zeyple needs to be updated. 
  * [X] **Zeyple has been temporarily disabled in mailserver `1.1-latest`**. Open issue : https://github.com/infertux/zeyple/issues/52
  * [ ] Temporary solution : Install `python-gpgme` [deb package](https://debian.pkgs.org/9/debian-main-amd64/python-gpgme_0.3-1.2_amd64.deb.html) from [debian.pkgs.org](https://debian.pkgs.org).

## :information_source: Changes

* [X] Dovecot https://wiki2.dovecot.org/Upgrading/2.3
  * [X] ssl_protocols has been replaced by ssl_min_protocol.
  * [X] Since 2.3.3+ DH parameter usage is optional and can be omitted. Amend ciphers to disallow non-ECC based DH algorithms, new `ssl_cipher_list = EECDH+AES:EDH+AES+aRSA:!DH`
  * [X] ssl_dh_parameters_length removed. 
  * [X] ssl-parameters.dat file is now obsolete and has been removed.
  * [X] Database password can now contain a '#' character.
---
* [X] Postfix [Postfix 3.4](http://www.postfix.org/announcements/postfix-3.4.0.html), [Postfix 3.3](http://www.postfix.org/announcements/postfix-3.3.0.html), [Postfix 3.2](http://www.postfix.org/announcements/postfix-3.2.0.html)
  * [X] Since Postfix 3.3, the master daemon can be started in the foreground ! Finally :tada: :cake: 
---
* [X] clamav-unofficial-sigs
  * [X] Yara rules are broken with clamav ≥ 0.100. Yara rules are now disabled in default configuration. Open issue : [link](https://bugzilla.clamav.net/show_bug.cgi?id=12077)

## :warning: Warnings

* [X] ```postfix/postfix-script: warning: symlink leaves directory: /etc/postfix/./makedefs.out```. Open issue : [link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926331) (This warning is harmless)

## :beetle:  Bugs

* No bug found yet, only zeyple unit tests fail.

## Softwares version

Software | Stretch | Buster |
| ------------- | ------------- | ------------- |
| Postfix | 3.1.12 | 3.4.5 |
| Dovecot | 2.2.27 | 2.3.4 |
| Fetchmail | 6.3.26  | 6.4.0 |
| ClamAV | 0.100.3  | 0.101.2  |
| Unbound | 1.6.0  | 1.9.0  |
| Rsyslog | 8.24.0 | 8.1901.0  |

###  Upgrade state : Complete

**Comment by hardware** [comment]
For all volunteers, you can begin to test this new version unless if you are currently using Zeyple. Your feedback will be appreciated.

**Comment by neuffer** [comment]
Shouldn't we update Python from Python 2 to Python 3 as well? I think Debian 10 support would be a great place to do it. Are there any parts that still depend on Python 2?

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by hardware** [comment]
@neuffer done.

**Comment by neuffer** [comment]
Thanks!

**Comment by dguttierrez** [comment]
Everything is ok after upgrade on my two servers. What if we add zeyple.py into rootfs, can we then use it?

**Comment by hardware** [comment]
@dguttierrez nope because zeyple.py use [pygpgme](https://pypi.org/project/pygpgme/) and the maintainers of Debian Project dropped the old `python-gpgme`  with pygpgme module [inside](https://packages.debian.org/stretch/amd64/python-gpgme/filelist).

You can install [pygpgme](https://pypi.org/project/pygpgme/) with pip directly, it should works, but this package was last released in 2012 and I don't want to use an unmaintained GPG module for security reason.

**Comment by ksylvan** [comment]
I'm seeing this on startup.

```
mailserver      | 2019-08-12T23:54:19.721747+00:00 mail dovecot: master: Fatal: service(dict) User doesn't exist: vmail (See service dict { unix_listener /var/run/dovecot/dict { user } } setting)
mailserver      | 2019-08-12T23:54:19.739876+00:00 mail root: s6-supervise : spawning unbound process
mailserver      | [1565654059] unbound[1184:0] warning: did not exit gracefully last time (1157)
mailserver      | 2019-08-12T23:54:19.755257+00:00 mail root: s6-supervise : spawning dovecot process
mailserver      | 2019-08-12T23:54:19.764876+00:00 mail root: s6-supervise : spawning rspamd process
mailserver      | 2019-08-12T23:54:19.782181+00:00 mail root: s6-supervise : spawning freshclam process
mailserver      | ./run: line 13: /var/run/clamav/freshclam.pid: No such file or directory
mailserver      | 2019-08-12 23:54:19 #1198(main) <fb8165>; main; detect_priv: user specified does not exists (Success), aborting
mailserver      | 2019-08-12T23:54:19.808271+00:00 mail root: s6-supervise : virus database downloaded, spawning clamd process
mailserver      | ./run: line 4: /var/run/clamav/clamd.pid: No such file or directory
```

**Comment by ksylvan** [comment]
Temporarily downgraded to `mail-server:1.1-stable` for the above problem. Will look into it. Would appreciate any ideas, @hardware

**Comment by ksylvan** [comment]
In `mailserver` container, from the prior images, I see:

```
$ docker-compose exec mailserver  bash
root@mail:/# grep vmail /etc/passwd
vmail:x:1024:1024::/var/mail:
```

but in mailserver:1.1-latest, there is no `vmail` user.

**Comment by hardware** [comment]
Upload your entire logs please.

**Comment by ksylvan** [comment]
[mailserver.log](https://github.com/hardware/mailserver/files/3502533/mailserver.log)

**Comment by ksylvan** [comment]
> Upload your entire logs please.

[mailserver.log](https://github.com/hardware/mailserver/files/3502533/mailserver.log)

@hardware

**Comment by hardware** [comment]
Ok, got it. So the issue is : you've actived Zeyple and the mail server should have stopped right after this warning : 

```
[WARNING] Zeyple support has been temporarily disabled in the master branch following the Debian 10 update. Please, use the stable docker tag (1.1-stable) until the issue fixed. More information here : https://github.com/hardware/mailserver/issues/393
```

But my exit procedure doesn't works as expected, I forgot about the changes made by @Matchlighter. 

Disable Zeyple or stay with `1.1-stable`.

**Comment by ksylvan** [comment]
I actually don't need Zeyple. I can disable it. Thank you.

**Comment by sknight80** [comment]
Can I use this version? I can install one of my mail servers.

**Comment by hardware** [comment]
So far so good, you can use it.

**Comment by hardware** [comment]
Zeyple' author wants to rewrite his program starting from scratch with Golang : https://github.com/infertux/zeyple/issues/52#issuecomment-431650033

As a temporary solution for Buster, I can install `python-gpgme` [deb package](https://debian.pkgs.org/9/debian-main-amd64/python-gpgme_0.3-1.2_amd64.deb.html) from [debian.pkgs.org](https://debian.pkgs.org). This is not ideal but why not.
