### ISSUE TITLE
add configure to disable amavis & clamav

### ISSUE THREAD

**Issue by changloong** [hardware/mailserver#4]
With amavis & clamav on small VPS the server will be slow, if we can disable it by configure or ENV var will make hardware/mailserver more useable for small VPS.

**Comment by hardware** [comment]
@changloong You can now set two environment variables to disable SpamAssassin and ClamAV :

* **DISABLE_CLAMAV** = Disable virus scanning (optional, default: false)
* **DISABLE_SPAMASSASSIN** = Disable SPAM checking (optional, default: false)

If DISABLE_CLAMAV and DISABLE_SPAMASSASSIN are both set to true, Amavis is also completely disabled.

**Comment by changloong** [comment]
Great, I will test it ASAP.
