### ISSUE TITLE
[Outlook/Yahoo] Email ends up in spam folders 

### ISSUE THREAD

**Issue by Vingtoft** [hardware/mailserver#40]
I have followed all instructions to the point, and my mail-tester.com score is 10/10. 
Everything should work as expected, but the emails the server is sending out ends up in spam-folders (tested in yahoo and hotmail, works with gmail).

Please see [this question os StackOverflow](http://stackoverflow.com/questions/39698417/prevent-email-ending-in-spam-folders)

Any ideas of improvements?

**Comment by hardware** [comment]
Some few tips : 

- Read this : http://mail.live.com/mail/troubleshooting.aspx and this https://help.yahoo.com/kb/postmaster/complaint-feedback-loop-program-sln3438.html
- Contact the Microsoft feedback-loop (their robot responds quickly) : https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wfname=capsub&productkey=edfsmsbl3
- Join SNDS program : https://postmaster.live.com/snds/
- Add your mail server to a whitelist like : https://www.dnswl.org/

I have the same problem, the microsoft's smartscreen filter is too strict, it's based on IP ranges i think.

**Comment by hardware** [comment]
I leave this issue open if someone has any suggestions/ideas to improve email deliverability with Outlook / Hotmail / Yahoo.

**Comment by Vingtoft** [comment]
I tried to add my mail to iPhone iOS 10 and got rejected. Reason: Certificated not trusted (im still scoring 10/10 on mail-tester.com). Perhaps this is the reason why mail end up in spam folders.
BTW im using my own ssl certificates, as described in the instructions, but it looks like the certificate is self-signed. 

Any thoughts?

![img_0009](https://cloud.githubusercontent.com/assets/1752080/18995224/88835766-872b-11e6-8a51-e6f1a1d23804.PNG)

**Comment by vizv** [comment]
Hey @Vingtoft, you could try DV certificates issued by Let's Encrypt, mine works this way.

Refer to https://github.com/hardware/mailserver#lets-encrypt and http://letsencrypt.readthedocs.io/en/latest/using.html#running-with-docker
