### ISSUE TITLE
Prevent redis DB size runaway

### ISSUE THREAD

**Issue by 1n5aN1aC** [hardware/mailserver#400]
#### Classification
_Please delete options that are not relevant._

* [x] Deliverability issue
* [X] Serious Hang

#### Description
Upon setting up backup on my mailserver, I noticed the redis folder was using well over 3GB of size.  Upon research, I found the following:

- The redis DB file is append-only so grows with every change, with no limit.  Mine was 3.5GB+
- This causes redis to replay the entire log upon startup.  Whenever my redis container was restarted, mailserver would not be usable for ~5 minutes.  Looking back on it, I realize this is because redis was still replaying it's log.
- Upon manually running [BGREWRITEAOF](https://redis.io/commands/bgrewriteaof), my database reduced in size to <50MB.

I learned how redis works by reading this [page on persistance](https://redis.io/topics/persistence), and discovered the 'correct' way is to specify the `auto-aof-rewrite-percentage` config option.  This way redis will automatically trim it if the size increases more than the specified percentage.

I am not sure what solution should be applied, or if my db being huge is a fluke, but I kept a copy of the huge version which I still have.  

#### My personal solution was the following:

1. Manually shrink it.  (`docker exec -it redis sh` & `redis-cli` & `BGREWRITEAOF`)
2. add the following to my docker-compose: (under redis)
```
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
```
3. Create that config file with the following, at a minimum: ([source](https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf))
```
appendonly yes
auto-aof-rewrite-percentage 50
auto-aof-rewrite-min-size 64mb
```
4. Restart redis

This has solved my problem short-term, and hopefully does long-term as well.

#### Docker information
```
Docker version 19.03.1, build 74b1e89
hardware/mailserver   1.1-latest          sha256:e5371a3a7a2d52e42e751dd6feb5d1787e7a455ae417069126602c0f91ea9fa9   c290d9020bb5        9 days ago          346MB
hardware/mailserver   <none>              sha256:6e9224503f222aebba379544f65902bdb5299a1b5d6e67f6954f8de61df43130   dc542ca44e7d        2 weeks ago         375MB
hardware/mailserver   <none>              sha256:9dae67a39f30642942e9f40109665511f78db896f1b0e1e48ec4637878949396   e2e08ae5a00d        2 months ago        396MB
hardware/mailserver   <none>              sha256:3130ce108d1f29244493685fc7695346f3af727613d3dbc8e7c9d655100c6ac6   e4b84104d93f        2 months ago        380MB
hardware/mailserver   <none>              sha256:8afec9a7a45f0215171a0ce7391b3fe7bea8334d77b5f606caa25d9060ce4669   e5611e4c6c00        4 months ago        380MB
hardware/mailserver   <none>              sha256:419f6ffb3f84dda6a056eecd134db92813b293a89d7da2dbd135e1a65386010e   4dc7b16a7234        6 months ago        380MB
hardware/mailserver   1.1-stable          sha256:1b2b3a1c5b3c99b3794b096800e8889274e5120479654cc1bf96e8f60019c3d4   295dd7bf1525        22 months ago       338MB
hardware/mailserver   latest              sha256:5ff8559ba758cd23f44121e64c152edded8a3370f46bff23d946b4209bdb375b   834cbdab45d6        2 years ago         235MB
```

**Comment by hardware** [comment]
> Since Redis 2.4 the AOF rewrite is automatically triggered by Redis, however the BGREWRITEAOF command can be used to trigger a rewrite at any time.

> If you're using the AOF with Redis 2.2 you'll need to run BGREWRITEAOF from time to time. Redis 2.4 is able to trigger log rewriting automatically

The documentation says that it is not necessary because `BGREWRITEAOF` is triggered automatically to avoid that precisely. I missed something ?

**Comment by 1n5aN1aC** [comment]
My understanding from the documentation is that it is only 'called automatically' because the directives I mentioned are in the default config file.  My understanding was that the default config file is not being used.  (as no config file is being used)

That being said, it's possible it grew so massively from something wrong on my server years ago.  Today my db is 67MB.  So obviously it's not growing at any serious rate right now.

**Comment by navossoc** [comment]
@1n5aN1aC I have a cron task for that...

```0 3 * * * docker exec redis redis-cli BGREWRITEAOF```

**Comment by 475392689485** [comment]
I noticed the same. Mine was around 500MB and running `redis-cli BGREWRITEAOF` made it 50MB.

**Comment by hardware** [comment]
> My understanding from the documentation is that it is only 'called automatically' because the directives I mentioned are in the default config file.

That makes sense. I let you make a pull request if you want.

**Comment by prometheanfire** [comment]
Is there a reason this isn't left to the user when setting up the redis container?  Maybe specifying that `foo=bar` should be in the redis config is enough?

**Comment by n33pm** [comment]
> > My understanding from the documentation is that it is only 'called automatically' because the directives I mentioned are in the default config file.
> 
> That makes sense. I let you make a pull request if you want.

This makes only sense, if you change the config file.
Redis without any config:
```bash
127.0.0.1:6379> CONFIG GET auto-aof-rewrite-percentage
1) "auto-aof-rewrite-percentage"
2) "100"
127.0.0.1:6379> CONFIG GET auto-aof-rewrite-min-size
1) "auto-aof-rewrite-min-size"
2) "67108864"
```
Tested with the `docker-compose.sample.yml`
