### ISSUE TITLE
Typo in LDAP virtual alias map (true vs yes)

### ISSUE THREAD

**Issue by henry-nicolas** [hardware/mailserver#402]
Hello,

Using this container with LDAP and tag 1.1-latest, I noticed the following configuration issue:
postfix/smtps/smtpd[330]: fatal: /etc/postfix/ldap/virtual-alias-maps.cf: bad boolean configuration: tls_require_cert = true

This happens when LDAP_TLS_FORCE is set to true. The value in the generate config should be "yes" and not "true".

Best regards,

**Comment by hardware** [comment]
@PeerD @johansmitsnl

**Comment by hardware** [comment]
Fixed in 5aca41ea0da24057934fefe85e32d542f026cfe7. Thank you for the report.
