### ISSUE TITLE
I can't login in postfixadmin

### ISSUE THREAD

**Issue by JulienFauconnier** [hardware/mailserver#41]
After step 4 of "Postfixadmin initial configuration" I'm not able to login...

**Comment by JulienFauconnier** [comment]
Ok no, in fact the form to create Admin account have an issu, he didn't check the rule of "3 character minimum".

So if i decide to type "ab789456123" as password, it's working, but i can't login

**Comment by hardware** [comment]
Retry to run the setup.php and follow all the steps including setup hash adding with docker exec. It works for me.

**Comment by JulienFauconnier** [comment]
It's exactly what I have done.
Like I said, it's just that typing a password with only two characters is possible when we choose the admin password.
It's seems that the setup password is checked, but not admin password.

**Comment by hardware** [comment]
So truncate postfix database and restart the setup.

**Comment by JulienFauconnier** [comment]
Ok, no problem :)

But now i'm facing an other issue XD
: host mx2.hotmail.com[65.55.37.120] said: 550
    SC-001 (COL004-MC4F39) Unfortunately, messages from 94.23.207.205 weren't
    sent. Please contact your Internet service provider since part of their
    network is on our block list. You can also refer your provider to
    http://mail.live.com/mail/troubleshooting.aspx#errors. (in reply to MAIL
    FROM command)

**Comment by hardware** [comment]
Contact Microsoft feedback-loop to unlock your server : https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wfname=capsub&productkey=edfsmsbl3

**Comment by hardware** [comment]
I close this issue because initial problem is solved.
