### ISSUE TITLE
How to create a "blackhole" account / an account where mails are automatically discarded?

### ISSUE THREAD

**Issue by ThibaultVlacich** [hardware/mailserver#410]
#### Classification
* [X] Question

#### Reproducibility
* [X] Not applicable

#### Description
I'm trying to create a "blackhole" email, like a no-reply address, where email are automatically discarded.

I came across [this StackOverflow topic](https://unix.stackexchange.com/questions/338084/correct-way-to-create-a-blackhole-account-in-postfix), which says that the best way is to add to Postfix transport map this:
```
blackhole@subdomain.myhostname.com   discard:silently
```

Any idea how to do this with this Docker image, or something similar? I need to do this because I have to login to the mailserver with an existing account to send emails from my application, because if I login with let's say contact@mydomain and tries to send an email as no-reply@mydomain, the server rejects me.

**Comment by 1n5aN1aC** [comment]
Maybe not the most elegant solution, but it is definitely possible to just setup a normal account, login as the user, and create a filter (sieve) rule to delete all incoming emails.

I would suggest something along the lines of:
"if sender contains {insert regex here} then discard"
or perhaps"if size > 1 then discard"
etc.
October 19, 2019 5:17 AM, "Thibault Vlacich" <notifications@github.com (mailto:notifications@github.com?to=%22Thibault%20Vlacich%22%20<notifications@github.com>)> wrote:
Classification
	*  Question
Reproducibility
	*  Not applicable
Docker information
	docker info docker images hardware/mailserver --digests --filter "dangling=false" 

Description
	I'm trying to create a "blackhole" email, like a no-reply address, where email are automatically discarded.

	I came across this StackOverflow topic (https://unix.stackexchange.com/questions/338084/correct-way-to-create-a-blackhole-account-in-postfix), which says that the best way is to add to Postfix transport map this:

	blackhole@subdomain.myhostname.com (mailto:blackhole@subdomain.myhostname.com) discard:silently 

	Any idea how to do this with this Docker image, or something similar? I need to do this because I have to login to the mailserver with an existing account to send emails from my application, because if I login with let's say contact@mydomain and tries to send an email as no-reply@mydomain, the server rejects me.
