### ISSUE TITLE
docker compose functionality

### ISSUE THREAD

**Issue by n1md4** [hardware/mailserver#413]
#### Classification

* [X] Question

#### Reproducibility

* [X] Not applicable

#### Docker information

Not necessary

#### Description
Briefly describe the problem you are having in a few lines.

I have created a docker-compose file in order to deploy the mailserver on a Swarm stack with NFS storage.

The container mail fails with the following error:

[ERROR] The domain name must be set !

The .env file is not used as I declared all the variables into the compose file.  How may I get around this?

**Comment by sknight80** [comment]
Is the `.env` file is next to the `docker-compose.yml` file? When. You run the `docker-compose up` command are you running it from the folder where you have the .`env` file?

**Comment by sknight80** [comment]
@n1md4 do you have your `docker-compose.yml` snippet so I can help you in this if you still have this problem.

**Comment by n1md4** [comment]
I believe this was resolved by using the appropriate domainname lines in the compose files.  Thank you for the assist, and apologies for not responding sooner.
