### ISSUE TITLE
Latest update not compatible with Ubuntu 14.04

### ISSUE THREAD

**Issue by Vingtoft** [hardware/mailserver#42]
This bug is discussed [here](https://github.com/Wonderfall/dockerfiles/issues/37#issuecomment-249576104). I had the same problem described in the linked thread, and I can confirm that the only solution (that i know about) is to update to Ubuntu 16.04.

**Comment by hardware** [comment]
This issue concern only wonderfall/nginx docker image, not hardware/mailserver image.
