### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Yfksw65** [hardware/mailserver#45]
Yop,

Petit souci ce soir suite a l'upgrade du mailserver, je n'arrive plus a accéder a Rainloop/PostfixAdmin

J'ai bien entendu modifié le proxy_pass sur le port 8888 comme indiqué mais cela ne corrige pas le pb.

Lorsque je fais un docker logs nginx je n'ai absolument rien (noir/vide)

Je vois bien les connexions dans l'access.log 

Aurais-tu une idée ?

**Comment by hardware** [comment]
tu as pensé à redémarrer nginx ?

```
docker-compose restart nginx

# ou

docker exec -ti nginx sh

nginx -s reload
```

**Comment by Yfksw65** [comment]
Oui bien sur, même la machine ^^'

Sans succès

**Comment by Yfksw65** [comment]
Finalement ca fonctionne sans mettre le :8888

**Comment by hardware** [comment]
ça veut dire que tes images ne sont pas à jour :

```
docker pull hardware/postfixadmin
docker pull hardware/rainloop
```

**Comment by Yfksw65** [comment]
Effectivement c'est mieux.. je pensais que docker-compose up -d me permettait de garder a jour mes containers.

Finalement il faut que je pull chaque images lorsque je veux le faire ?

**Comment by hardware** [comment]
Oui la commande pull permet de récupérer la dernière build de l'image auprès du registry de docker.
