### ISSUE TITLE
[Improvement] Quota support from the Postfix

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#48]
[Postfix VDA](http://vda.sourceforge.net/) — Limiting the size of virtual mailbox for Postfix.
- [postfix-vda-3.1.1](https://sourceforge.net/p/vda/mailman/message/35235581/)
### Features
- Brings per mailbox/maildir quota support to Postfix VDA
- Support for Courier style maildir format, including maildirsize file
- Limit either only INBOX or whole maildir
- Customizable bounce message, used if mails are bounced (it's also an option)
- Customisable suffix for Maildir support, sometimes needed for Courier IMAP
- Enhanced patch delivery abilities using vfilter

``` ini
##############################
## QUOTA SUPPORT PARAMETERS ##
##############################

virtual_create_maildirsize     = yes
virtual_mailbox_extended       = yes
virtual_mailbox_limit_maps     = mysql:/etc/postfix/mysql/mysql-virtual-mailbox-limit-maps.cf
virtual_mailbox_limit_override = yes
virtual_maildir_limit_message  = "The user you are trying to reach is over quota."
virtual_overquota_bounce       = yes
```
###### mysql-virtual-mailbox-limit-maps.cf

``` ini
# …
query = SELECT quota FROM mailbox WHERE username = '%s' AND active = '1'
```

**Comment by hardware** [comment]
Quota support is fully implemented now :tada:

Thunderbird :
![quota1](https://cloud.githubusercontent.com/assets/327354/20642281/9629995e-b40b-11e6-85e3-42c3980aae66.png)

Rainloop :
![quota2](https://cloud.githubusercontent.com/assets/327354/20642285/a2933c5e-b40b-11e6-85e5-199513636280.png)

Postfixadmin domain quotas :
![quota3](https://cloud.githubusercontent.com/assets/327354/20642287/a99d8252-b40b-11e6-9d1b-a1c1b666707f.png)

Postfixadmin mailboxes quotas :
![quota4](https://cloud.githubusercontent.com/assets/327354/20642292/be498048-b40b-11e6-8b68-d0cfb1a08ad6.png)

I will merge all modifications into master shortly.
