### ISSUE TITLE
[Implementation] fetchmail to receive mail

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#52]
https://sourceforge.net/p/postfixadmin/code/HEAD/tree/trunk/ADDITIONS/fetchmail.pl

**Comment by hardware** [comment]
Fetchmail is really useful ? What is the point of this solution ?

**Comment by denji** [comment]
@hardware To receive mail from external IMAP/POP3 into local mailbox.

> https://postfixadmin.domain.tld/edit.php?table=fetchmail

**Comment by hardware** [comment]
I added fetchmail forwarding support. Now you can set `ENABLE_FETCHMAIL` variable to `true` and configure your retrieval settings in postfixadmin.
