### ISSUE TITLE
Auto-responder email vacation & vacation_notification

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#54]
https://sourceforge.net/p/postfixadmin/code/HEAD/tree/trunk/VIRTUAL_VACATION/

**Comment by hardware** [comment]
This feature is already available with rainloop and Pigeonhole Sieve plugin. You can set a vacation auto-responder like this :

![vacation](https://cloud.githubusercontent.com/assets/327354/20644171/4b947078-b42c-11e6-9367-d4a973beee55.png)

Sieve rule :

```
require ["vacation"];

vacation :days 1 :addresses ["user@domain.tld"] :subject "Out of office" "My vacation message...";
stop;
```

Mailserver log : 

```
dovecot: lmtp(522, user@domain.tld): xxxxxxxxxxxxxxxxxxx: sieve: msgid=<xxxxxxxxxxxx@mail.another-domain.tld>: sent vacation response to <some.user@another-domain.tld>
```

Headers :

```
X-Sieve: Pigeonhole Sieve 0.4.2
Subject: Out of office
In-Reply-To: ...
References: ...
Auto-Submitted: auto-replied (vacation)
```

**Comment by digitalkram** [comment]
hi there
is the Pigeonhole sieve plugin still available and if yes hwo to install it (it is not in rainloop>plugins>available plugins)

thank you!

Cheers

**Comment by hardware** [comment]
@digitalkram you must enable Sieve support in rainloop admin panel.

![](https://i.imgur.com/ow76ykD.png)

Pigeonhole plugin is already enabled in Dovecot configuration.

**Comment by digitalkram** [comment]
Great, thank you!
