### ISSUE TITLE
nginx proxy for a directory

### ISSUE THREAD

**Issue by patgg** [hardware/mailserver#55]
Hello,
something failed when i try to configure the proxy for postfixadmin and rainloop.
i can just see postfixadmin. i can't connect to rainloop.
i tryied to modify the nginx proxy for that postfixadmin be in a specific directory /pf/ ( Webroot (default is /): /pf/ ), it idicates that : WARNING: You might have to add a proxy header to get your custom webroot working.
Is there a little tuto to do that ? i tryied it : https://www.nginx.com/resources/admin-guide/reverse-proxy/#headers but it fails.
thx

**Comment by hardware** [comment]
This issue only concern wonderfall/nginx docker image, not hardware/mailserver image.
