### ISSUE TITLE
Access and Auditing Milter for Postfix

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#56]
# ClueGetter - Access and Auditing Milter

[ClueGetter](https://github.com/Freeaqingme/ClueGetter) provides a means to have an integrated way to determine if a message
should be accepted by Postfix. All email (metadata) and verdicts are stored in a
database allowing for auditing.

Each message has a verdict of one of the following values:
- Permit: Accept message.
- Tempfail: Deny delivery, but expect the delivering MTA to deliver it at a later time.
- Reject: Reject the message, indicating it will not be accepted a next time either.

Features:
- [Quotas](https://github.com/Freeaqingme/ClueGetter/wiki/Quotas) - Limit the number of emails
  (per ip, sasl user, recipient, sender) over an arbitrary amount of time. 
- SpamAssassin - Determine whether an email is SPAM through [SpamAssassin](http://spamassassin.apache.org/).
  Can be used alongside the Rspamd module.
- Rspamd - Determine whether an email is SPAM through [Rspamd](http://www.rspamd.com).
  Can be used alongside the SpamAssassin module.
- ClamAV/Clamd - Scan the message for viruses, malware, etc.
- Greylisting - Ask a server to try again in a bit if it wasn't seen before and the mail looks spammy.
- [Bounce Handling](https://github.com/Freeaqingme/ClueGetter/wiki/Bounce-Handling) - Keep track of what emails were rejected by remote MTAs and for what reasons.
- Abusers - Present a list of users in the web interface who had an unusual amount of email rejected.
  Usually these users have been hacked, or are otherwise malicious.
- MailQueue - Display an aggregate of all mail queues that reside in your ClueGetter cluster.
  Filter based on instance, recipient(/domain), sender(/domain) and delete or requeue selections
  of items in the queue.
- Contacts - Import address books (e.g. from RoundCube) so these addresses and/or domains can be used to (partially) blacklist messages from those addresses or domains.
- SRS - Sender Rewriting Scheme
- DKIM - Sign messages using DKIM
- Volume Reputation - Detect anomalies in volume, and penalize sudden increases in volume.

| Message Details | Searching for a message | Mail Queue |
| --- | --- | --- |
| [![Message Details](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/thumbs/200.MessageDetails.png)](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/MessageDetails.png) | [![Search for a message](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/thumbs/200.Search.png)](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/Search.png) | [![Mail Queue ](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/thumbs/200.MailQueue.png)](https://raw.githubusercontent.com/Freeaqingme/ClueGetter/develop/screenshots/MailQueue.png) |

**Comment by Yfksw65** [comment]
Je valide l'ajout de ClueGetter a ta solution, très pratique.

**Comment by hardware** [comment]
The debian package is not compatible with systemd.
