### ISSUE TITLE
Allow to modify php.ini variables in rainloop

### ISSUE THREAD

**Issue by sebastienDevibim** [hardware/mailserver#58]
These two variables are set by default and cannot be set manually (without exec in the docker and that's not a good solution...)
upload_max_filesize
post_max_size

Is it possible to add something to allow to modify it ?
It's really useful to set the maximum size of an attachment.

**Comment by hardware** [comment]
You can modify sizes here : https://github.com/hardware/rainloop/blob/master/php-fpm.conf#L13-L14

**Comment by sebastienDevibim** [comment]
Sorry but I don't find how to do that if I've installed everything via a `docker-compose up -d`.
Is there a special option in the `docker-compose.yml` ?

**Comment by hardware** [comment]
Set your values, build your own image with `docker build -t rainloop .`  and run your container with `docker-compose up -d` I don't want to change my docker image for this kind of detail, it's not the purpose of docker.
