### ISSUE TITLE
Increase opendkim key length

### ISSUE THREAD

**Issue by Wonderfall** [hardware/mailserver#6]
Actuellement, la taille de la clé est de 1024 bits.
https://github.com/hardware/mailserver/blob/master/rootfs/usr/local/bin/opendkim#L15

Est-ce qu'il y a une raison qui empêcherait, ou déconseillerait techniquement l'utilisation d'une clé de taille supérieure ? Comme 2048 bits ? Parce qu'aujourd'hui en 2016 les clés RSA de cette taille sont fortement déconseillée d'utilisation. Si c'est juste une question d'enregistrement DNS chez certains services comme celui d'OVH, il y a par exemple le moyen de découper la clé en plusieurs enregistrements TXT. Pour le reste, aucun problème.

Merci de m'éclairer.
Au pire, pourquoi pas laisser le choix ? On en a déjà parlé, ce serait une bonne idée. Il suffit juste de rajouter une variable pour qu'on puisse générer une clé dont on peut préciser la taille avec `docker exec -ti mailserver opendkim 2048`.

**Comment by hardware** [comment]
À la base c'était pour une question de compatibilité mais autant laisser le choix, c'est sûr.

**Comment by Wonderfall** [comment]
C'est bon, merci ! Après il n'est pas spécialement recommandé d'aller au-delà de 4096 vu que la grande majorité des services utilisent du 2048 max.
