### ISSUE TITLE
How to configure with nginx-proxy image

### ISSUE THREAD

**Issue by vabatta** [hardware/mailserver#60]
Hi,

I use docker to serve several websites on my host through the `nginx-proxy` image. 
I would like to know if it's possible to serve the `mailserver` through that image instead of `boring-nginx`.
I would have something like:
`website1.com` and `mail.website1.com` to serve emails for this domain `@website1.com`
`website2.com` and `mail.website2.com` to serve emails for this domain `@website2.com`
where `mail.domain.com` is the webgui for postfix admin.
My `db` is actually a `mysql` container.

Machine installed with `Debian 8`.

**Comment by hardware** [comment]
Look at nginx-proxy readme : https://github.com/jwilder/nginx-proxy
and docker-gen readme  https://github.com/jwilder/docker-gen

But you should use wonderfall/boring-nginx.
