### ISSUE TITLE
550 5.1.1 <xxx@xxx.xxx> Recipient not found.

### ISSUE THREAD

**Issue by konstantinj** [hardware/mailserver#7]
Hi,

I'm getting "Recipient not found" for all addresses with different domains than the email server itself. Shouldn't that also work for multiple domains?
Also I can't see this error in any logfile. Could you redirect the logs from all services to stdout/stderr?

**Comment by hardware** [comment]
To see the log file, add another docker volume :

```
-v /var/log/mail:/var/log/mail
```

> Shouldn't that also work for multiple domains ?

Not yet, but it's in the roadmap.

**Comment by konstantinj** [comment]
Ah ok that would work. I think it would be great if you could see logs from all services via docker logs. [Foreman](https://github.com/ddollar/foreman) can do that nicely, or [Forego](https://github.com/ddollar/forego). Is that also possible with supervisord? I guess the problem is postfix since it only logs to syslog. Anyway, I still haven't found the error message in a log file. The mail.err does not exist although it is in the rsyslog.conf. Weired.

**Comment by hardware** [comment]
If you haven't any mail.err log file, it means that no error was generated by the mail stack (postfix/dovecot...etc). See `mail.warn` file for warnings. I have not yet tested the multi-domains support, but in reality I think it should work actually.

According to the postfix documentation, current settings are good for me :

http://www.postfix.org/ADDRESS_CLASS_README.html#virtual_mailbox_class
http://www.postfix.org/postconf.5.html#virtual_mailbox_domains

> Is that also possible with supervisord ?

Yes, I'll change supervisord settings to redirect logs to **stdout/stderr**.

**Comment by konstantinj** [comment]
All services are now logging to syslog so I've disabled logging in supervisor for everything and only enabled syslog to log to stdout. Also I have configured syslog to only log mail.* to stdout and not log everything else to reduce io. Also the kernel log feature from syslog raised errors so I've disabled it.

I've also added scripts to add multiple domains to opendkim etc. Still busy fixing some errors.

**Comment by konstantinj** [comment]
Hi, I've made some more changes to make me happy. Multiple domains btw have worked before but there are also keys for it. Take a look https://github.com/konstantinj/mailserver. Haven't changed the README so far.

**Comment by hardware** [comment]
Great job, can you create a new pull request ?

**Comment by konstantinj** [comment]
add #9
