### ISSUE TITLE
Let's encrypt for pop/imap/smtp

### ISSUE THREAD

**Issue by spoutnikfr** [hardware/mailserver#71]
Merci pour ce gros gros boulot.

J'essaye de comprendre comment générer un certificat valide avec let's encrypt (et non un auto-généré) pour les connexions POP/IMAP/SMTP. Outlook est lourd de ce côté là.
Je n'ai pas l'impression que la config de base le permette, peut-on le faire d'une façon ou d'une autre?

**Comment by kaiyou** [comment]
Il faut du Web quasi obligatoire pour générer un certificat Letsencrypt. La doc sur le ``README.md`` est très bien faite pour générer le certificat, puis simplement l'utiliser aussi bien pour le frontal Web que pour les autres services, tant que tout est accédé avec le même nom.

Attention à bien recharger le certificat une fois regénéré toutes les quelques semaines, c'est la seule partie contraignante pour l'instant. Y'a du boulot un peu pour automatiser le tout, mais c'est faisable ; j'y travaille sur un projet à côté, ça devrait être assez portable ici si ça peut servir.

**Comment by spoutnikfr** [comment]
Je débute avec docker et les containers, pas forcément évident.
J'ai du mal lire un truc dans le readme, je vais aller relire ça merci.

**Comment by kaiyou** [comment]
Si Docker rebute pour l'instant, tu peux aussi installer letsencrypt sur l'hôte, stopper temporairement la stack mail et utiliser ``certbot`` depuis l'hôte, quelque chose comme : 

```
certbot certonly --standalone --standalone-supported-challenges http-01 -d tondomaine.tld
```

La principale containte tant que tu n'automatises pas : les certificats sont valides trois mois, il faut penser à les renouveler régulièrement. Des mails automatiques le rappellent de la part de Letsencrypt.
