### ISSUE TITLE
Reverse proxy problems

### ISSUE THREAD

**Issue by tshaw** [hardware/mailserver#72]
I configured yml as seen below. (I removed rainloop as it requires payment I expect to use open source roundcube after I get this working.)

I configured letsencrypt using standalone certs to store in /etc/letsencrypt which is world readable.

I then went to configure the webserver using sudo docker exec -ti nginx ngxproxy

Name: postfixadmin
Domain: postfixadmin.mydomain.tld
Webroot (default is /): 
Container: postfixadmin
Port (default is 80): 8888 (NOTE I believe that this should be 8000 to match with the website's yml)
HTTPS [y/n]: y
Certificate path: /certs/live/postfixadmin.mydomain.tld/fullchain.pem

The Certificate path was never accepted. I kept getting "Certificate path: " without any error message.

Any help is truly appreciated,

Tom
yml:
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    # restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
        # /sites-enabled : vhosts files (*.conf)
      - /mnt/docker/nginx/sites-enabled:/opt/mailserver/nginx/sites-enabled
        # /conf.d : additional configuration files
      - /mnt/docker/nginx/conf:/opt/mailserver/nginx/conf.d
         # /var/log/nginx : nginx logs
     - /mnt/docker/nginx/log:/var/log/nginx
        # /certs : SSL/TLS certificates
      - /mnt/docker/nginx/certs:/etc/letsencrypt
        # /passwds : authentication files
        # /www : put your websites there

    depends_on:
      - postfixadmin
    # - rainloop

**Comment by rylincoln** [comment]
Go here and jump down to the "Let's Encrypt certificate authority"  section - you gotta set that up to create the certs otherwise you can use the snakeoil one they talk about ... but you shouldn't really do that.

https://hub.docker.com/r/hardware/mailserver/

**Comment by tshaw** [comment]
Thanks but I had the certs which is what confused me

in .yml

  nginx:
    image: wonderfall/boring-nginx
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
        # /sites-enabled : vhosts files (*.conf)
      - /mnt/docker/nginx/sites-enabled:/opt/mailserver/nginx/sites-enabled
        # /conf.d : additional configuration files
      - /mnt/docker/nginx/conf:/opt/mailserver/nginx/conf.d
         # /var/log/nginx : nginx logs
     - /mnt/docker/nginx/log:/var/log/nginx
        # /certs : SSL/TLS certificates
      - /mnt/docker/nginx/certs:/etc/letsencrypt
        # /passwds : authentication files
        # /www : put your websites there

    depends_on:
      - postfixadmin

And in configuring web server I did

# Configure webserver
sudo docker exec -ti nginx ngxproxy
Name: postfixadmin
Domain: postfixadmin.oitc.com
Webroot (default is /): /
Container: postfixadmin
Port (default is 80): 8888
HTTPS [y/n]: y
Certificate path: /etc/nginx/certs/live/postfixadmin.oitc.com/fullchain.pem
Certificate key path: /etc/nginx/certs/live/postfixadmin.oitc.com/privkey.pem
Secure headers [y/n]: y
Enable HSTS header ? [y/n]: n # Use with caution
Max body size in MB (integer/null): null

**Comment by chrissound** [comment]
@tshaw Are those files present? `/etc/nginx/certs/live/postfixadmin.oitc.com/fullchain.pem` for example? 

If you exec into the docker container. Because I can't see how that directory would be mounted (looking at your docker-compose.yml).

**Comment by hardware** [comment]
The certificate path is relative to the nginx container mountpoint, example :

```
Certificate path: /certs/live/mail.domain.tld/fullchain.pem
Certificate key path: /certs/live/mail.domain.tld/privkey.pem
```

```
nginx:
  image: wonderfall/boring-nginx
  volumes:
    - /mnt/docker/nginx/certs:/certs
```

External path : **/mnt/docker/nginx/certs/live/mail.domain.tld/fullchain.pem**
Internal path :  **/certs/live/mail.domain.tld/fullchain.pem**

You must use the internal path which is relative to the container.

**Comment by strarsis** [comment]
@tshaw: There are free editions of rainloop: https://www.rainloop.net/purchase/
I also plan to use this and like to know the reason for why you removed it from your installation.
