### ISSUE TITLE
What is the postfix setup password?

### ISSUE THREAD

**Issue by chrissound** [hardware/mailserver#74]
I'm running through the postfix configuration, and in the setup wizard there is a 'setup password' field - what is this - where can I retrieve it from?

**Comment by Hydrog3n** [comment]
Hi, it's the master password hashed explain here : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration

Make a screen if is not answer your question :)

**Comment by chrissound** [comment]
I was reading through that wiki page at the time.

`2 - Define setup password` - how do I do this?

Unless this form is responsible for **setting** the setup password?
If I click on "lost password" I get sent to a **change setup password**?

Seems a bit confusing.
![2017-01-11-10 03 09](https://cloud.githubusercontent.com/assets/1499652/21844078/2fb39686-d7e5-11e6-8440-910bb512ac0d.png)

**Comment by chrissound** [comment]
Ah nevermind, I must have forgotten I set the password on the first screen.
