### ISSUE TITLE
sa-learn : argument list too long

### ISSUE THREAD

**Issue by tsedgwick1** [hardware/mailserver#76]
Tous les jours j'ai une tâche planifié qui ne passe pas et du coup ça m’envoie un mail, en objet j'ai : 
Cron <root@mail> /usr/bin/sa-learn --ham /var/mail/vhosts/*/*/mail/cur/* | logger -t sa-learn-ham

Puis dans le corps du mail : 
/bin/sh: 1: /usr/bin/sa-learn: Argument list too long

je sais pas si je suis le seul mais je comprend pas trop pourquoi..
![capture2](https://cloud.githubusercontent.com/assets/17798571/22209277/32e3c88a-e186-11e6-9b35-f26000d06706.JPG)

**Comment by Hydrog3n** [comment]
@tsedgwick1 Je viens de regarder sa-learn c'est spamassassin. Il t'envois ça car il y a une erreur sur la commande. Tu as mit a jour ton image ? 

https://spamassassin.apache.org/full/3.1.x/doc/sa-learn.html

**Comment by tsedgwick1** [comment]
@Hydrog3n Yes toutes mes images sont a jour, j'ai fais la maj hier soir et comme d'hab à 3h30 j'ai reçu le même mail.. :/ Pour l'instant il y a pas d'impact sur la production et les spams sont bien rejeté donc ça va, j'ai juste pas envie d'avoir de mauvaises surprises ^^

**Comment by hardware** [comment]
C'est à cause d'une limitation du kernel : http://stackoverflow.com/a/18647755

Tu dois avoir une arborescence trop importante au niveau de /var/mail/vhost pour que le kernel bloque lors du listing des fichiers. Une solution serait d'utiliser le plugin antispam de Dovecot : http://wiki2.dovecot.org/Plugins/Antispam

En attendant que ce soit mis en place du niveau de l'image, tu peux créer une règle Sieve afin d'ignorer ce genre de mail.

**Comment by tsedgwick1** [comment]
@hardware D'accord merci pour ta réponse, je vais faire ça en attendant la mise a jour de l'image :)

**Comment by hardware** [comment]
[Fixed in version 1.1](https://github.com/hardware/mailserver/issues/110#issuecomment-309279757)
