### ISSUE TITLE
Logs management

### ISSUE THREAD

**Issue by paoll** [hardware/mailserver#77]
Hi,

First of all, thanks for your work, it's pleasure to set up an email server that quick ! 

I Would like to manage logs (for pflogsumm), and I didn't find an easy way to do it : 

- redirect /var/log outside the container : bad idea, break almost everything
- rsylog mail.log to a volume outside the container : don't break anything, but not working as well

Is there is any way to access to mail logs in order to work on them ? Another idea could be to include pflogsumm on the container ?

Many Thanks !

PA

**Comment by hardware** [comment]
Your second solution should work, edit rsyslog config file to redirect logs in /var/log/mail and mount this folder to a volume with docker compose.
