### ISSUE TITLE
Backup mx 

### ISSUE THREAD

**Issue by mhf-ir** [hardware/mailserver#78]
how can we have backup mx in seperate host but no additional configuration?
Other docker or mail suite dosnt care about backup mx. what about `hardware/mailserver` ?

**Comment by hardware** [comment]
Backup mx support isn't in the roadmap but i am open to implementation suggestions, feel free to create a pull request to add this feature.

**Comment by petrleocompel** [comment]
I think you can just deploy on other server secondary hardware/mailserver and to postfixadmin add domain as MX backup. And thats all. Or am I wrong?

**Comment by petrleocompel** [comment]
Okay. I was wrong. It's just little bit difficult but not much. 
Inspired by https://wiki.gentoo.org/wiki/Complete_Virtual_Mail_Server/Postfix_additions
Just need to add files for mapping relay_doamins and relay_recipient_maps and link them from main.cf.

**Comment by hardware** [comment]
And you need a database master/slave synchronisation with two servers in two differents datacenters on 2 differents autonomous system.

**Comment by petrleocompel** [comment]
Yup. Or be like a :monkey:  and do it twice when you have 10 emails.

**Comment by hardware** [comment]
True ^^ or you can use your registrar's mailserver as backup MX. This is the simplest solution.

**Comment by petrleocompel** [comment]
Yeah, but then I could ask. Do I need my own mailserver ?  - So, thats not a solution.

**Comment by hardware** [comment]
> Do I need my own mailserver ?

Yes, but if the primary host doesn't respond, it's better to have your registrar backup MX than nothing. Currently this docker image does not offer this feature because i don't need it but if you need it, I can add backup mx feture.

**Comment by petrleocompel** [comment]
I allready did that (forked, edited). Now I'm testing that. After testing i will make pull request. But thanks :slightly_smiling_face:  :+1: 

> Yes, but if the primary host doesn't respond, it's better to have your registrar backup MX than nothing. 

I'm talking about deploying 2 containers but not on same host. And with separate internet connection.

**Comment by hardware** [comment]
> I allready did that

Nice :+1:  Don't forget to add somes tests in `test/tests.bats`
