### ISSUE TITLE
Security and SSL/TLS MUA/MTA configuration

### ISSUE THREAD

**Issue by Wonderfall** [hardware/mailserver#8]
Actuellement, l'image est taillée pour la compatibilité, parfois au détriment de la sécurité dans l'absolu.
Par exemple pour le MUA on pourrait n'autoriser que TLS 1.2 et AESGCM : 
```
ssl = required
ssl_cert = <<FULLCHAIN>
ssl_key = <<KEYFILE>
ssl_protocols = !SSLv2 !SSLv3 !TLSv1 !TLSv1.1
ssl_cipher_list = AESGCM
ssl_prefer_server_ciphers = yes
ssl_dh_parameters_length = 2048
```

En plus édulcoré on pourrait faire : 
```
ssl_protocols = !SSLv2 !SSLv3
ssl_cipher_list = AES128+EECDH:AES128+EDH
```

Ensuite, pour le MTA : https://github.com/hardware/mailserver/blob/master/rootfs/etc/postfix/main.cf#L31-L69
Ne pourrait-on pas être un peu plus exigent quand même ? Déjà que la sécurité offerte par SMTP+STARTTLS est toute relative, autant faire le moins de concessions, toujours dans l'absolu sécuritaire.

Je pense qu'il est quand même utile d'au moins en discuter.

**Comment by hardware** [comment]
Au niveau du MUA, je peux effectivement renforcer le chiffrement, certains clients un peu anciens pourraient être exclus ne pouvant pas faire la négociation TLS , genre sous Android 2.x ou Outlook 2007.

Par contre côté MTA, c'est compliqué parce qu'il faut prendre en compte l'ensemble des serveurs mail potentiels, à ce niveau il y a un peu de tout et n'importe quoi niveau configuration. Par exemple chez Orange, je sais que leurs serveurs ne supportent pas une annonce via STARTTLS, d'où le fait que Postfix est actuellement configuré en mode "Opportunistic TLS" au lieu de "Mandatory TLS".

Des exemples comme ça il y en a un paquet, l'écosystème mail étant assez exotique, c'est pas évident. Récemment (2014), il était déconseillé de désactiver le protocole SSLv3, encore pour des raisons de compatibilité, les développeurs de Postfix ayant désactivés ce support par défaut que depuis mi-2015 à cause de POODLE.

Après ce qu'il faut bien comprendre c'est qu'à la base le protocole mail n'a pas été conçu pour être ultra-secure, c'est pour ça qu'une initiative du nom de DarkMail à vu le jour avec la spécification du protocole DIME (Dark Internet Mail Environment) reposant sur un chiffrement de bout en bout.

https://en.wikipedia.org/wiki/Dark_Mail_Alliance

Ce protocole n'est pas encore standardisé mais il le sera peut-être d'ici quelques années.
