### ISSUE TITLE
Anti-Abuse for servers at authentication time

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#80]
The goal of 'wforce' is to detect brute forcing of passwords across many
servers, services and instances.  In order to support the real world, brute
force detection policy can be tailored to deal with "bulk, but legitimate"
users of your service, as well as botnet-wide slowscans of passwords.
* https://github.com/PowerDNS/weakforced
* [lightweight C fail2ban](https://github.com/AdUser/f2b)

wforce is aimed to receive message from services like:

 * IMAP
 * POP3
 * Webmail logins
 * FTP logins
 * Authenticated SMTP
 * Self-service logins
 * Password recovery services

**Comment by hardware** [comment]
I have been using [ossec](https://ossec.github.io/) for 4 years, it's a great HIDS. I think it might be a good idea to use it to parse postfix and dovecot logs to prevent brute attack with composite rules and active response.

https://github.com/ossec/ossec-hids/blob/master/etc/rules/dovecot_rules.xml
https://github.com/ossec/ossec-hids/blob/master/etc/rules/postfix_rules.xml
https://ossec.github.io/docs/manual/ar/index.html

However, I will not add it in the docker image, ossec must be installed on the host level. I have to find a way to access the logs outside the container, if you have a suggestion...

**Comment by denji** [comment]
rspamd Multimap `redis://<hashkey>` ?

**Comment by denji** [comment]
https://github.com/vstakhov/rspamd.com/blob/master/doc/modules/multimap.md#map-types

ip - matches IP of the host that performed message handoff (against radix map)

**Comment by hardware** [comment]
@denji Rspamd multimap module is not designed to detect brute force at authentication time and prevent it. Please explain your point of view.

**Comment by denji** [comment]
Will need another daemon watching syslog/file to implement the send into redis, in any case, rspamd is a powerful system scripting in lua and implement a detailed list of prevention and anomaly detection.
