### ISSUE TITLE
Mail Archiving

### ISSUE THREAD

**Issue by msander** [hardware/mailserver#81]
In business context, there is often the requirement to archive all mails and prevent deletion and manipulation. (At least in Germany it's required by law from the beginning of this year, so that mails can be treated the same as paper documents)

I'm not sure if there's any existing Open Source solution to this, but I'd love to see one integrated in hardware/mailserver. If you are open to this suggestion, I would do a bit research about existing solutions and make a proposal.

**Comment by denji** [comment]
* [Mailman 3](https://wiki.list.org/Mailman3)
* [Mlmmj](http://mlmmj.org/)
* Ezmlm
* [Majordomo](http://www.greatcircle.com/majordomo/)
* …

**Comment by msander** [comment]
Thanks for your research!

I think the mailing list archives serve another purpose, which could be discussed as a separate thread. Mail   Piler looks good to me, based on a first glance at the feature list. I guess we should try it first before integrating it. 

From the architectural point of view:  Do you think it's generally a good idea to integrate it in this project? Another way could be to create a new docker project for mailpiler and write an integration manual.

**Comment by denji** [comment]
Such decisions are better integrated in individual containers that would be possible could limit the use of resources.

/cc @hardware

**Comment by hardware** [comment]
> Such decisions are better integrated in individual containers that would be possible could limit the use of resources.

I agree, Mail Piler must be in a separate container like rainloop and postfixadmin. It is an optional dependency, not everyone will use it.

**Comment by j-schumann** [comment]
@msander Did you have time to test mailpiler?

There is a (rudimentary?) docker container for mailpiler: https://hub.docker.com/r/heri16/piler-mail/
Haven't tested it. Still integration with the mail server would require changes to the postfix config:
<pre>
/etc/postfix/main.cf:
   smtpd_recipient_restrictions = reject_non_fqdn_recipient, ..., \
                     check_recipient_access pcre:$config_directory/x-add-envelope-to, ...
   always_bcc = archive@piler.yourdomain.com

/etc/postfix/x-add-envelope-to:
   /(.*)/   prepend X-Envelope-To: $1</pre>
(http://www.mailpiler.org/wiki/current:installation)

This requires at least using the custom.conf method as the <code>x-add-envelope-to</code> file could be stored next to the custom.conf so we don't have to add it to the rootfs of the container.

**Comment by outbackdingo** [comment]
looks nice ill look at this also

**Comment by jodumont** [comment]
@msander might be out of our scope but [loomio](https://www.loomio.org) offer a better way to keep track and take decision.

**Comment by denji** [comment]
@jodumont SaaS, PaaS...

**Comment by navossoc** [comment]
Any news on this?
Anyone using some good software? Any tips?

I'm also interested on it.

**Comment by sknight80** [comment]
I am using a bash script that archive each domains then upload to my S3. I don't think I need additional application for this, do I?

**Comment by navossoc** [comment]
@sknight80 I don't think this work as @msander has described.

> In business context, there is often the requirement to archive all mails and prevent deletion and manipulation.

**Comment by neuffer** [comment]
Is anybody using Mail Piler successfully or has anything else in use?

**Comment by sknight80** [comment]
@neuffer not yet, but I am planning to try this out in one of my mail servers.
