### ISSUE TITLE
Tags and Releases

### ISSUE THREAD

**Issue by maZahaca** [hardware/mailserver#82]
Hi,

Do you have a stable version of your mailserver?
How's about adding tags in the code and tag on docker hub. It's not a good practice to use "latest" there

Thanks

**Comment by hardware** [comment]
Latest tag and master branch are always stable, for experimental work i push to **dev** branch. And I haven't planned any major version upgrade in the future.

**Comment by maZahaca** [comment]
@hardware
I'm truly believe in master-stable way! However, if I have installed any soft on the production server and for some reason need to reinstall it, or install it on different environments, I want to be sure that it will be exactly the same version I had before. Current way doesn't allow this, "latest" tag will push me with new updates even I don't want them.

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/releases/tag/1.0
https://hub.docker.com/r/hardware/mailserver/tags/

 :tada: :champagne:

**Comment by maZahaca** [comment]
Thanks!
