### ISSUE TITLE
Database is empty

### ISSUE THREAD

**Issue by maZahaca** [hardware/mailserver#84]
I've created stack based on your `docker-compose.yml` file. 
But for some reason database is empty, which service have to create base structure of tables?

**Comment by hardware** [comment]
Same as : https://github.com/hardware/mailserver/issues/47

Create all postfix tables with postfixadmin setup and restart the mailserver container.

**Comment by maZahaca** [comment]
@hardware how I can do this? Shall I run some scrip or so?

**Comment by hardware** [comment]
https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration

**Comment by maZahaca** [comment]
Thanks a lot
