### ISSUE TITLE
Authentication-Results header

### ISSUE THREAD

**Issue by metro2030** [hardware/mailserver#86]
Hi there!

I have an issue similar to #61.
I don't know why in 'Authentication-Results' header DMARC=fail. I've already checked `/etc/opendmarc/IgnoreDomains`. My domain is listed there.

Can you suggest anything to fix?

**Comment by hardware** [comment]
I think it's a bug in OpenDMARC, which despite "IgnoreMailFrom" and "TrustedAuthservIDs" tries to apply DMARC policy to outgoing e-mails. But this behavior has no effect on the legitimacy of outgoing mails.

I hope this bug will be fixed in the next version of OpenDMARC with Debian Stretch.

**Comment by hardware** [comment]
Fixed in version 1.1.

Now using the [Rspamd DMARC module](https://rspamd.com/doc/modules/dmarc.html).
