### ISSUE TITLE
Mailserver certificate

### ISSUE THREAD

**Issue by acs-ferreira** [hardware/mailserver#90]
I'm having an issue trying to setup Thunderbird on Windows.

When i try to add an account, it can't retrieve the cert for `mail.domain.tld:993`

![image](https://cloud.githubusercontent.com/assets/12234510/23818596/dff956f8-05fc-11e7-914a-d0494f106bfe.png)

My certs had been added with let's Encrypt as described on https://github.com/hardware/mailserver#lets-encrypt-certificate-authority and when i test connections to `mail.domain.tld` or `postfixadmin.domain.tld` everything seems OK and the cert retrieved is coming from let's Encrypt authority.

As i can see, the cert is actually retrieved from https://github.com/hardware/mailserver/blob/00d562116a41871ba3953c4cdb3833c1461db049/rootfs/usr/local/bin/startup#L97

How can i bypass this to have my Let's Encrypt cert available?

Thanks.

**Comment by hardware** [comment]
Check your Let's Encrypt cert path :

https://github.com/hardware/mailserver/blob/00d562116a41871ba3953c4cdb3833c1461db049/rootfs/usr/local/bin/startup#L52

> LETS_ENCRYPT_LIVE_PATH = /etc/letsencrypt/live/**mail.domain.tld**

Let's encrypt live subfolder name must be egual to domainname & hostname values of docker-compose file.

**Comment by acs-ferreira** [comment]
Yes it was the case, i've simply restarted the container and it is good now, thanks.
