### ISSUE TITLE
Setup de MySQL?

### ISSUE THREAD

**Issue by izanagi1995** [hardware/mailserver#98]
Salut @hardware 

Je voudrais mettre ton serveur en place.

Je me demandais donc si il faut créer des tables spécifiques dans MySQL ou si tout est géré par ton Dockerfile?

Si il faut tout remplir manuellement, que dois-je mettre?

Merci :)

**Comment by hardware** [comment]
Bonjour @izanagi1995,

Les tables sont créées automatiquement lors du setup de postfixadmin, ensuite tu peux les remplir via l'interface en ajoutant un nouveau domaine et les mailbox associées.

**Comment by izanagi1995** [comment]
Okey okey merci et bon boulot, c'est une fameuse usine à gaz :D

**Comment by hardware** [comment]
C'est une machine bien rodée 👌 =D
