### ISSUE TITLE
How can I disable DKIM signature ?

### ISSUE THREAD

**Issue by aknik** [hardware/mailserver#99]

**Comment by hardware** [comment]
Disable DKIM milter :

```bash
# /mnt/docker/mail/postfix/custom.conf

smtpd_milters = $dmarc_milter
non_smtpd_milters = 
```

Disable DMARC milter :

```bash
# /mnt/docker/mail/postfix/custom.conf

smtpd_milters = $dkim_milter
```

Don't forget to remove your **mail._domainkey** and **_dmarc** TXT records.

http://www.postfix.org/MILTER_README.html

**Comment by aknik** [comment]
I just want to run the container without dkim signatures.

**Comment by hardware** [comment]
I gave you the simplest solution just above.

**Comment by aknik** [comment]
There is not a /mnt/docker/mail/postfix/ dir

**Comment by hardware** [comment]
```
mkdir -p /mnt/docker/mail/postfix
touch /mnt/docker/mail/postfix/custom.conf
```

https://github.com/hardware/mailserver#override-postfix-configuration

**Comment by aknik** [comment]
Thanks
